---
title: "analyzeNoise"
output: html_document
date: "2024-08-20"
---

```{r setup}
library(tidyverse)
library(CMTFtoolbox)
```

```{r helper functions}
matchComponents = function(inputFac, outputFac){
  matchingComponents = apply(abs(cor(inputFac[[1]], outputFac[[1]])), 2, which.max)
  return(matchingComponents)
}

resortComponents = function(Fac, matchedComponents){
  sortedFac = list()
  for(i in 1:length(Fac)){
    sortedFac[[i]] = Fac[[i]][,matchedComponents]
  }
  return(sortedFac)
}
```

# Tensor-matrix case

```{r load data}
inputFac = readRDS("./noise_sim_tensor_matrix_inputFac.RDS")
inputFacnorm = readRDS("./noise_sim_tensor_matrix_inputFacnorm.RDS")

Z_010 = readRDS("./noise_sim_tensor_matrix_Z_010.RDS")
Z_025 = readRDS("./noise_sim_tensor_matrix_Z_025.RDS")
Z_035 = readRDS("./noise_sim_tensor_matrix_Z_035.RDS")
Z_010_norm = readRDS("./noise_sim_tensor_matrix_Z_010_norm.RDS")
Z_025_norm = readRDS("./noise_sim_tensor_matrix_Z_025_norm.RDS")
Z_035_norm = readRDS("./noise_sim_tensor_matrix_Z_035_norm.RDS")
  
CMTF_010 = readRDS("./noise_sim_tensor_matrix_CMTF_010.RDS")
CMTF_025 = readRDS("./noise_sim_tensor_matrix_CMTF_025.RDS")
CMTF_035 = readRDS("./noise_sim_tensor_matrix_CMTF_035.RDS")
CMTF_010_norm = readRDS("./noise_sim_tensor_matrix_CMTF_010_norm.RDS")
CMTF_025_norm = readRDS("./noise_sim_tensor_matrix_CMTF_025_norm.RDS")
CMTF_035_norm = readRDS("./noise_sim_tensor_matrix_CMTF_035_norm.RDS")
```

```{r FMS against input}
inputFacSorted = vect_to_fac(unlist(inputFac), Z_010, sortComponents=TRUE)
FMS_010 = array(0L, c(length(CMTF_010), 2))
FMS_025 = array(0L, c(length(CMTF_010), 2))
FMS_035 = array(0L, c(length(CMTF_010), 2))
FMS_010_norm = array(0L, c(length(CMTF_010), 2))
FMS_025_norm = array(0L, c(length(CMTF_010), 2))
FMS_035_norm = array(0L, c(length(CMTF_010), 2))

for(i in 1:length(CMTF_010)){
  FMS_010[i,] = computeFMS(inputFacSorted, CMTF_010[[i]]$Fac, Z_010$modes)
  FMS_025[i,] = computeFMS(inputFacSorted, CMTF_025[[i]]$Fac, Z_010$modes)
  FMS_035[i,] = computeFMS(inputFacSorted, CMTF_035[[i]]$Fac, Z_010$modes)
  
  Fac_010 = resortComponents(CMTF_010_norm[[i]]$Fac, matchComponents(inputFacSorted, CMTF_010_norm[[i]]$Fac))
  Fac_025 = resortComponents(CMTF_025_norm[[i]]$Fac, matchComponents(inputFacSorted, CMTF_025_norm[[i]]$Fac))
  Fac_035 = resortComponents(CMTF_035_norm[[i]]$Fac, matchComponents(inputFacSorted, CMTF_035_norm[[i]]$Fac))
  
  FMS_010_norm[i,] = computeFMS(inputFacSorted, Fac_010, Z_010$modes)
  FMS_025_norm[i,] = computeFMS(inputFacSorted, Fac_025, Z_010$modes)
  FMS_035_norm[i,] = computeFMS(inputFacSorted, Fac_035, Z_010$modes)
}

colnames(FMS_010) = c("X1", "X2")
colnames(FMS_025) = c("X1", "X2")
colnames(FMS_035) = c("X1", "X2")
colnames(FMS_010_norm) = c("X1", "X2")
colnames(FMS_025_norm) = c("X1", "X2")
colnames(FMS_035_norm) = c("X1", "X2")

FMS_010 = FMS_010 %>% as_tibble() %>% mutate(sim="FMS_010")
FMS_025 = FMS_025 %>% as_tibble() %>% mutate(sim="FMS_025")
FMS_035 = FMS_035 %>% as_tibble() %>% mutate(sim="FMS_035")
FMS_010_norm = FMS_010_norm %>% as_tibble() %>% mutate(sim="FMS_010_norm")
FMS_025_norm = FMS_025_norm %>% as_tibble() %>% mutate(sim="FMS_025_norm")
FMS_035_norm = FMS_035_norm %>% as_tibble() %>% mutate(sim="FMS_035_norm")
```

```{r plot FMS}
rbind(FMS_010, FMS_025, FMS_035, FMS_010_norm, FMS_025_norm, FMS_035_norm) %>% as_tibble() %>% pivot_longer(-sim) %>% ggplot(aes(x=as.factor(sim),y=value)) + facet_wrap(~name) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Simulation") + ylab("Factor Match Score")
```

```{r check convergence reason}
convergence_010 = 1:length(CMTF_010)
convergence_025 = 1:length(CMTF_025)
convergence_035 = 1:length(CMTF_035)
convergence_010_norm = 1:length(CMTF_010_norm)
convergence_025_norm = 1:length(CMTF_025_norm)
convergence_035_norm = 1:length(CMTF_035_norm)

for(i in 1:length(CMTF_010)){
  convergence_010[i] = CMTF_010[[i]]$terminate$what
  convergence_025[i] = CMTF_025[[i]]$terminate$what
  convergence_035[i] = CMTF_035[[i]]$terminate$what
  convergence_010_norm[i] = CMTF_010_norm[[i]]$terminate$what
  convergence_025_norm[i] = CMTF_025_norm[[i]]$terminate$what
  convergence_035_norm[i] = CMTF_035_norm[[i]]$terminate$what
}

table(convergence_010)
table(convergence_025)
table(convergence_035)
table(convergence_010_norm)
table(convergence_025_norm)
table(convergence_035_norm)
```

# Tensor-tensor case

```{r load data}
inputFac = readRDS("./noise_sim_tensor_tensor_inputFac.RDS")
inputFacnorm = readRDS("./noise_sim_tensor_tensor_inputFacnorm.RDS")

Z_010 = readRDS("./noise_sim_tensor_tensor_Z_010.RDS")
Z_025 = readRDS("./noise_sim_tensor_tensor_Z_025.RDS")
Z_035 = readRDS("./noise_sim_tensor_tensor_Z_035.RDS")
Z_010_norm = readRDS("./noise_sim_tensor_tensor_Z_010_norm.RDS")
Z_025_norm = readRDS("./noise_sim_tensor_tensor_Z_025_norm.RDS")
Z_035_norm = readRDS("./noise_sim_tensor_tensor_Z_035_norm.RDS")
  
CMTF_010 = readRDS("./noise_sim_tensor_tensor_CMTF_010.RDS")
CMTF_025 = readRDS("./noise_sim_tensor_tensor_CMTF_025.RDS")
CMTF_035 = readRDS("./noise_sim_tensor_tensor_CMTF_035.RDS")
CMTF_010_norm = readRDS("./noise_sim_tensor_tensor_CMTF_010_norm.RDS")
CMTF_025_norm = readRDS("./noise_sim_tensor_tensor_CMTF_025_norm.RDS")
CMTF_035_norm = readRDS("./noise_sim_tensor_tensor_CMTF_035_norm.RDS")
```

```{r FMS against input}
inputFacSorted = vect_to_fac(unlist(inputFac), Z_010, sortComponents=TRUE)
FMS_010 = array(0L, c(length(CMTF_010), 2))
FMS_025 = array(0L, c(length(CMTF_010), 2))
FMS_035 = array(0L, c(length(CMTF_010), 2))
FMS_010_norm = array(0L, c(length(CMTF_010), 2))
FMS_025_norm = array(0L, c(length(CMTF_010), 2))
FMS_035_norm = array(0L, c(length(CMTF_010), 2))

for(i in 1:length(CMTF_010)){
  FMS_010[i,] = computeFMS(inputFacSorted, CMTF_010[[i]]$Fac, Z_010$modes)
  FMS_025[i,] = computeFMS(inputFacSorted, CMTF_025[[i]]$Fac, Z_010$modes)
  FMS_035[i,] = computeFMS(inputFacSorted, CMTF_035[[i]]$Fac, Z_010$modes)
  
  Fac_010 = resortComponents(CMTF_010_norm[[i]]$Fac, matchComponents(inputFacSorted, CMTF_010_norm[[i]]$Fac))
  Fac_025 = resortComponents(CMTF_025_norm[[i]]$Fac, matchComponents(inputFacSorted, CMTF_025_norm[[i]]$Fac))
  Fac_035 = resortComponents(CMTF_035_norm[[i]]$Fac, matchComponents(inputFacSorted, CMTF_035_norm[[i]]$Fac))
  
  FMS_010_norm[i,] = computeFMS(inputFacSorted, Fac_010, Z_010$modes)
  FMS_025_norm[i,] = computeFMS(inputFacSorted, Fac_025, Z_010$modes)
  FMS_035_norm[i,] = computeFMS(inputFacSorted, Fac_035, Z_010$modes)
}

colnames(FMS_010) = c("X1", "X2")
colnames(FMS_025) = c("X1", "X2")
colnames(FMS_035) = c("X1", "X2")
colnames(FMS_010_norm) = c("X1", "X2")
colnames(FMS_025_norm) = c("X1", "X2")
colnames(FMS_035_norm) = c("X1", "X2")

FMS_010 = FMS_010 %>% as_tibble() %>% mutate(sim="FMS_010")
FMS_025 = FMS_025 %>% as_tibble() %>% mutate(sim="FMS_025")
FMS_035 = FMS_035 %>% as_tibble() %>% mutate(sim="FMS_035")
FMS_010_norm = FMS_010_norm %>% as_tibble() %>% mutate(sim="FMS_010_norm")
FMS_025_norm = FMS_025_norm %>% as_tibble() %>% mutate(sim="FMS_025_norm")
FMS_035_norm = FMS_035_norm %>% as_tibble() %>% mutate(sim="FMS_035_norm")
```

```{r plot FMS}
rbind(FMS_010, FMS_025, FMS_035, FMS_010_norm, FMS_025_norm, FMS_035_norm) %>% as_tibble() %>% pivot_longer(-sim) %>% ggplot(aes(x=as.factor(sim),y=value)) + facet_wrap(~name) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Simulation") + ylab("Factor Match Score")
```

```{r check convergence reason}
convergence_010 = 1:length(CMTF_010)
convergence_025 = 1:length(CMTF_025)
convergence_035 = 1:length(CMTF_035)
convergence_010_norm = 1:length(CMTF_010_norm)
convergence_025_norm = 1:length(CMTF_025_norm)
convergence_035_norm = 1:length(CMTF_035_norm)

for(i in 1:length(CMTF_010)){
  convergence_010[i] = CMTF_010[[i]]$terminate$what
  convergence_025[i] = CMTF_025[[i]]$terminate$what
  convergence_035[i] = CMTF_035[[i]]$terminate$what
  convergence_010_norm[i] = CMTF_010_norm[[i]]$terminate$what
  convergence_025_norm[i] = CMTF_025_norm[[i]]$terminate$what
  convergence_035_norm[i] = CMTF_035_norm[[i]]$terminate$what
}

table(convergence_010)
table(convergence_025)
table(convergence_035)
table(convergence_010_norm)
table(convergence_025_norm)
table(convergence_035_norm)
```

# Matrix-tensor-matrix case

```{r load data}
inputFac = readRDS("./noise_sim_matrix_tensor_matrix_inputFac.RDS")
inputFacnorm = readRDS("./noise_sim_matrix_tensor_matrix_inputFacnorm.RDS")

Z_010 = readRDS("./noise_sim_matrix_tensor_matrix_Z_010.RDS")
Z_025 = readRDS("./noise_sim_matrix_tensor_matrix_Z_025.RDS")
Z_035 = readRDS("./noise_sim_matrix_tensor_matrix_Z_035.RDS")
Z_010_norm = readRDS("./noise_sim_matrix_tensor_matrix_Z_010_norm.RDS")
Z_025_norm = readRDS("./noise_sim_matrix_tensor_matrix_Z_025_norm.RDS")
Z_035_norm = readRDS("./noise_sim_matrix_tensor_matrix_Z_035_norm.RDS")
  
CMTF_010 = readRDS("./noise_sim_matrix_tensor_matrix_CMTF_010.RDS")
CMTF_025 = readRDS("./noise_sim_matrix_tensor_matrix_CMTF_025.RDS")
CMTF_035 = readRDS("./noise_sim_matrix_tensor_matrix_CMTF_035.RDS")
CMTF_010_norm = readRDS("./noise_sim_matrix_tensor_matrix_CMTF_010_norm.RDS")
CMTF_025_norm = readRDS("./noise_sim_matrix_tensor_matrix_CMTF_025_norm.RDS")
CMTF_035_norm = readRDS("./noise_sim_matrix_tensor_matrix_CMTF_035_norm.RDS")
```

```{r FMS against input - block 1 vs 2}
inputFacSorted = vect_to_fac(unlist(inputFac), Z_010, sortComponents=TRUE)
FMS_010 = array(0L, c(length(CMTF_010), 2))
FMS_025 = array(0L, c(length(CMTF_010), 2))
FMS_035 = array(0L, c(length(CMTF_010), 2))
FMS_010_norm = array(0L, c(length(CMTF_010), 2))
FMS_025_norm = array(0L, c(length(CMTF_010), 2))
FMS_035_norm = array(0L, c(length(CMTF_010), 2))

for(i in 1:length(CMTF_010)){
  FMS_010[i,] = computeFMS(inputFacSorted, CMTF_010[[i]]$Fac, Z_010$modes[1:2])
  FMS_025[i,] = computeFMS(inputFacSorted, CMTF_025[[i]]$Fac, Z_010$modes[1:2])
  FMS_035[i,] = computeFMS(inputFacSorted, CMTF_035[[i]]$Fac, Z_010$modes[1:2])
  
  Fac_010 = resortComponents(CMTF_010_norm[[i]]$Fac, matchComponents(inputFacSorted, CMTF_010_norm[[i]]$Fac))
  Fac_025 = resortComponents(CMTF_025_norm[[i]]$Fac, matchComponents(inputFacSorted, CMTF_025_norm[[i]]$Fac))
  Fac_035 = resortComponents(CMTF_035_norm[[i]]$Fac, matchComponents(inputFacSorted, CMTF_035_norm[[i]]$Fac))
  
  FMS_010_norm[i,] = computeFMS(inputFacSorted, Fac_010, Z_010$modes[1:2])
  FMS_025_norm[i,] = computeFMS(inputFacSorted, Fac_025, Z_010$modes[1:2])
  FMS_035_norm[i,] = computeFMS(inputFacSorted, Fac_035, Z_010$modes[1:2])
}

colnames(FMS_010) = c("X1", "X2")
colnames(FMS_025) = c("X1", "X2")
colnames(FMS_035) = c("X1", "X2")
colnames(FMS_010_norm) = c("X1", "X2")
colnames(FMS_025_norm) = c("X1", "X2")
colnames(FMS_035_norm) = c("X1", "X2")

FMS_010 = FMS_010 %>% as_tibble() %>% mutate(sim="FMS_010")
FMS_025 = FMS_025 %>% as_tibble() %>% mutate(sim="FMS_025")
FMS_035 = FMS_035 %>% as_tibble() %>% mutate(sim="FMS_035")
FMS_010_norm = FMS_010_norm %>% as_tibble() %>% mutate(sim="FMS_010_norm")
FMS_025_norm = FMS_025_norm %>% as_tibble() %>% mutate(sim="FMS_025_norm")
FMS_035_norm = FMS_035_norm %>% as_tibble() %>% mutate(sim="FMS_035_norm")

rbind(FMS_010, FMS_025, FMS_035, FMS_010_norm, FMS_025_norm, FMS_035_norm) %>% as_tibble() %>% pivot_longer(-sim) %>% ggplot(aes(x=as.factor(sim),y=value)) + facet_wrap(~name) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Simulation") + ylab("Factor Match Score")
```

```{r FMS against input - block 2 vs 3}
inputFacSorted = vect_to_fac(unlist(inputFac), Z_010, sortComponents=TRUE)
FMS_010 = array(0L, c(length(CMTF_010), 2))
FMS_025 = array(0L, c(length(CMTF_010), 2))
FMS_035 = array(0L, c(length(CMTF_010), 2))
FMS_010_norm = array(0L, c(length(CMTF_010), 2))
FMS_025_norm = array(0L, c(length(CMTF_010), 2))
FMS_035_norm = array(0L, c(length(CMTF_010), 2))

for(i in 1:length(CMTF_010)){
  FMS_010[i,] = computeFMS(inputFacSorted, CMTF_010[[i]]$Fac, Z_010$modes[2:3])
  FMS_025[i,] = computeFMS(inputFacSorted, CMTF_025[[i]]$Fac, Z_010$modes[2:3])
  FMS_035[i,] = computeFMS(inputFacSorted, CMTF_035[[i]]$Fac, Z_010$modes[2:3])
  
  Fac_010 = resortComponents(CMTF_010_norm[[i]]$Fac, matchComponents(inputFacSorted, CMTF_010_norm[[i]]$Fac))
  Fac_025 = resortComponents(CMTF_025_norm[[i]]$Fac, matchComponents(inputFacSorted, CMTF_025_norm[[i]]$Fac))
  Fac_035 = resortComponents(CMTF_035_norm[[i]]$Fac, matchComponents(inputFacSorted, CMTF_035_norm[[i]]$Fac))
  
  FMS_010_norm[i,] = computeFMS(inputFacSorted, Fac_010, Z_010$modes[2:3])
  FMS_025_norm[i,] = computeFMS(inputFacSorted, Fac_025, Z_010$modes[2:3])
  FMS_035_norm[i,] = computeFMS(inputFacSorted, Fac_035, Z_010$modes[2:3])
}

colnames(FMS_010) = c("X1", "X2")
colnames(FMS_025) = c("X1", "X2")
colnames(FMS_035) = c("X1", "X2")
colnames(FMS_010_norm) = c("X1", "X2")
colnames(FMS_025_norm) = c("X1", "X2")
colnames(FMS_035_norm) = c("X1", "X2")

FMS_010 = FMS_010 %>% as_tibble() %>% mutate(sim="FMS_010")
FMS_025 = FMS_025 %>% as_tibble() %>% mutate(sim="FMS_025")
FMS_035 = FMS_035 %>% as_tibble() %>% mutate(sim="FMS_035")
FMS_010_norm = FMS_010_norm %>% as_tibble() %>% mutate(sim="FMS_010_norm")
FMS_025_norm = FMS_025_norm %>% as_tibble() %>% mutate(sim="FMS_025_norm")
FMS_035_norm = FMS_035_norm %>% as_tibble() %>% mutate(sim="FMS_035_norm")

rbind(FMS_010, FMS_025, FMS_035, FMS_010_norm, FMS_025_norm, FMS_035_norm) %>% as_tibble() %>% pivot_longer(-sim) %>% ggplot(aes(x=as.factor(sim),y=value)) + facet_wrap(~name) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Simulation") + ylab("Factor Match Score")
```

```{r check convergence reason}
convergence_010 = 1:length(CMTF_010)
convergence_025 = 1:length(CMTF_025)
convergence_035 = 1:length(CMTF_035)
convergence_010_norm = 1:length(CMTF_010_norm)
convergence_025_norm = 1:length(CMTF_025_norm)
convergence_035_norm = 1:length(CMTF_035_norm)

for(i in 1:length(CMTF_010)){
  convergence_010[i] = CMTF_010[[i]]$terminate$what
  convergence_025[i] = CMTF_025[[i]]$terminate$what
  convergence_035[i] = CMTF_035[[i]]$terminate$what
  convergence_010_norm[i] = CMTF_010_norm[[i]]$terminate$what
  convergence_025_norm[i] = CMTF_025_norm[[i]]$terminate$what
  convergence_035_norm[i] = CMTF_035_norm[[i]]$terminate$what
}

table(convergence_010)
table(convergence_025)
table(convergence_035)
table(convergence_010_norm)
table(convergence_025_norm)
table(convergence_035_norm)
```
