---
title: "ACMTF_simulation"
output: html_document
date: "2024-08-22"
---

```{r setup, include=FALSE}
library(CMTFtoolbox)
library(tidyverse)
library(ggpubr)
```

# Case 1

```{r simulate data}
set.seed(123)

R = 3
I = 50
J = 30
K = 40
M = 20
modes = list(c(1,2,3), c(1,4))

A = array(rnorm(I*R), c(I, R))  # shared subject mode
Anorm = sweep(A, 2, apply(A, 2, function(x){norm(as.matrix(x), "F")}), FUN="/")
B = array(rnorm(J*R), c(J, R))  # distinct feature mode of X1
Bnorm = sweep(B, 2, apply(B, 2, function(x){norm(as.matrix(x), "F")}), FUN="/")
C = array(rnorm(K*R), c(K, R))  # distinct condition mode of X1
Cnorm = sweep(C, 2, apply(C, 2, function(x){norm(as.matrix(x), "F")}), FUN="/")
D = array(rnorm(M*R), c(M, R))  # distinct feature mode of X2
Dnorm = sweep(D, 2, apply(D, 2, function(x){norm(as.matrix(x), "F")}), FUN="/")

lambdas = array(c(1, 1, 0, 1, 1, 1), c(2,3))

df1 = array(0L, c(I, J, K))
df2 = array(0L, c(I, M))
for(i in 1:R){
  df1 = df1 + lambdas[1,i] * reinflateTensor(Anorm[,i], Bnorm[,i], Cnorm[,i])
  df2 = df2 + lambdas[2,i] * reinflateMatrix(Anorm[,i], Dnorm[,i])
}

datasets = list(df1, df2)
Z = setupCMTFdata(datasets, modes, normalize=TRUE)
```

```{r run models}
cmtf_result = cmtf_opt(Z, 3, nstart=100, numCores=12, allOutput=TRUE)
acmtf_result = acmtf_opt(Z, 3, nstart=100, numCores=12, allOutput=TRUE)
```

```{r create lambda plot}
acmtf_lambdas = abs(acmtf_result[[1]]$Fac[[5]])
colnames(acmtf_lambdas) = c("Component_1", "Component_2", "Component_3")
acmtf_lambdas = acmtf_lambdas %>% as_tibble() %>% pivot_longer(everything())

for(i in 2:length(acmtf_result)){
  temp = abs(acmtf_result[[i]]$Fac[[5]])
  colnames(temp) = c("Component_1", "Component_2", "Component_3")
  temp = temp %>% as_tibble() %>% pivot_longer(everything())
  acmtf_lambdas = rbind(acmtf_lambdas, temp)
}
```

```{r create match score plot}
Fac = acmtf_result[[1]]$Fac
numComponents = ncol(Fac[[1]])
matchScore = 1:numComponents

for(i in 1:numComponents){
  a_hat = Fac[[1]][,i]
  proposedMatchScore = 1:numComponents
  for(j in 1:numComponents){
    a = Anorm[,j]
    proposedMatchScore[j] = (t(a_hat) %*% a) / (norm(a_hat, "2") * norm(a, "2"))
  }
  matchScore[i] = max(proposedMatchScore)
}
```

```{r inspect models - CMTF}
# CMTF best result
plotlist_cmtf = list()
plotlist_cmtf[[1]]  = cbind(Anorm, cmtf_result$Fac[[1]]) %>% as_tibble() %>% ggplot(aes(x=V1, y=V4)) + geom_point() + ggtitle("Subject mode (shared)") + xlab("") + ylab("Modelled loading (Comp. 1)")
plotlist_cmtf[[2]]  = cbind(Bnorm, cmtf_result$Fac[[2]]) %>% as_tibble() %>% ggplot(aes(x=V1, y=V4)) + geom_point() + ggtitle("Feature mode X1") + xlab("") + ylab("")
plotlist_cmtf[[3]]  = cbind(Cnorm, cmtf_result$Fac[[3]]) %>% as_tibble() %>% ggplot(aes(x=V1, y=V4)) + geom_point() + ggtitle("Condition mode X1") + xlab("") + ylab("")
plotlist_cmtf[[4]]  = cbind(Dnorm, cmtf_result$Fac[[4]]) %>% as_tibble() %>% ggplot(aes(x=V1, y=V4)) + geom_point() + ggtitle("Feature mode X2") + xlab("") + ylab("")

plotlist_cmtf[[5]]  = cbind(Anorm, cmtf_result$Fac[[1]]) %>% as_tibble() %>% ggplot(aes(x=V2, y=V6)) + geom_point() + xlab("") + ylab("Modelled loading (Comp. 2)")
plotlist_cmtf[[6]]  = cbind(Bnorm, cmtf_result$Fac[[2]]) %>% as_tibble() %>% ggplot(aes(x=V2, y=V6)) + geom_point() + xlab("") + ylab("")
plotlist_cmtf[[7]]  = cbind(Cnorm, cmtf_result$Fac[[3]]) %>% as_tibble() %>% ggplot(aes(x=V2, y=V6)) + geom_point() + xlab("") + ylab("")
plotlist_cmtf[[8]]  = cbind(Dnorm, cmtf_result$Fac[[4]]) %>% as_tibble() %>% ggplot(aes(x=V2, y=V6)) + geom_point() + xlab("") + ylab("")

plotlist_cmtf[[9]]  = cbind(Anorm, cmtf_result$Fac[[1]]) %>% as_tibble() %>% ggplot(aes(x=V3, y=V5)) + geom_point() + xlab("Simulated loading") + ylab("Modelled loading (Comp. 3)")
plotlist_cmtf[[10]] = cbind(Bnorm, cmtf_result$Fac[[2]]) %>% as_tibble() %>% ggplot(aes(x=V3, y=V5)) + geom_point() + xlab("Simulated loading") + ylab("")
plotlist_cmtf[[11]] = cbind(Cnorm, cmtf_result$Fac[[3]]) %>% as_tibble() %>% ggplot(aes(x=V3, y=V5)) + geom_point() + xlab("Simulated loading") + ylab("")
plotlist_cmtf[[12]] = cbind(Dnorm, cmtf_result$Fac[[4]]) %>% as_tibble() %>% ggplot(aes(x=V3, y=V5)) + geom_point() + xlab("Simulated loading") + ylab("")

plot = ggarrange(plotlist=plotlist_cmtf, nrow=3, ncol=4)
annotate_figure(plot, top = text_grob("CMTF model"))

abs(t(cmtf_result$Fac[[1]][,1]) %*% Anorm[,1]) / (norm(as.matrix(cmtf_result$Fac[[1]][,1]), "F") * norm(as.matrix(Anorm[,1]), "F"))
abs(t(cmtf_result$Fac[[1]][,3]) %*% Anorm[,2]) / (norm(as.matrix(cmtf_result$Fac[[1]][,3]), "F") * norm(as.matrix(Anorm[,2]), "F"))
abs(t(cmtf_result$Fac[[1]][,2]) %*% Anorm[,3]) / (norm(as.matrix(cmtf_result$Fac[[1]][,2]), "F") * norm(as.matrix(Anorm[,3]), "F"))
```
```{r inspect models - ACMTF}
# CMTF best result
plotlist_acmtf = list()
plotlist_acmtf[[1]]  = cbind(Anorm, acmtf_result$Fac[[1]]) %>% as_tibble() %>% ggplot(aes(x=V1, y=V5)) + geom_point() + ggtitle("Subject mode (shared)") + xlab("") + ylab("Modelled loading (Comp. 1)")
plotlist_acmtf[[2]]  = cbind(Bnorm, acmtf_result$Fac[[2]]) %>% as_tibble() %>% ggplot(aes(x=V1, y=V5)) + geom_point() + ggtitle("Feature mode X1") + xlab("") + ylab("")
plotlist_acmtf[[3]]  = cbind(Cnorm, acmtf_result$Fac[[3]]) %>% as_tibble() %>% ggplot(aes(x=V1, y=V5)) + geom_point() + ggtitle("Condition mode X1") + xlab("") + ylab("")
plotlist_acmtf[[4]]  = cbind(Dnorm, acmtf_result$Fac[[4]]) %>% as_tibble() %>% ggplot(aes(x=V1, y=V5)) + geom_point() + ggtitle("Feature mode X2") + xlab("") + ylab("")

plotlist_acmtf[[5]]  = cbind(Anorm, acmtf_result$Fac[[1]]) %>% as_tibble() %>% ggplot(aes(x=V2, y=V6)) + geom_point() + xlab("") + ylab("Modelled loading (Comp. 2)")
plotlist_acmtf[[6]]  = cbind(Bnorm, acmtf_result$Fac[[2]]) %>% as_tibble() %>% ggplot(aes(x=V2, y=V6)) + geom_point() + xlab("") + ylab("")
plotlist_acmtf[[7]]  = cbind(Cnorm, acmtf_result$Fac[[3]]) %>% as_tibble() %>% ggplot(aes(x=V2, y=V6)) + geom_point() + xlab("") + ylab("")
plotlist_acmtf[[8]]  = cbind(Dnorm, acmtf_result$Fac[[4]]) %>% as_tibble() %>% ggplot(aes(x=V2, y=V6)) + geom_point() + xlab("") + ylab("")

plotlist_acmtf[[9]]  = cbind(Anorm, acmtf_result$Fac[[1]]) %>% as_tibble() %>% ggplot(aes(x=V3, y=V4)) + geom_point() + xlab("Simulated loading") + ylab("Modelled loading (Comp. 3)")
plotlist_acmtf[[10]] = cbind(Bnorm, acmtf_result$Fac[[2]]) %>% as_tibble() %>% ggplot(aes(x=V3, y=V4)) + geom_point() + xlab("Simulated loading") + ylab("")
plotlist_acmtf[[11]] = cbind(Cnorm, acmtf_result$Fac[[3]]) %>% as_tibble() %>% ggplot(aes(x=V3, y=V4)) + geom_point() + xlab("Simulated loading") + ylab("")
plotlist_acmtf[[12]] = cbind(Dnorm, acmtf_result$Fac[[4]]) %>% as_tibble() %>% ggplot(aes(x=V3, y=V4)) + geom_point() + xlab("Simulated loading") + ylab("")

plot = ggarrange(plotlist=plotlist_acmtf, nrow=3, ncol=4)
annotate_figure(plot, top = text_grob("acmtf model"))

abs(t(acmtf_result$Fac[[1]][,2]) %*% Anorm[,1]) / (norm(as.matrix(acmtf_result$Fac[[1]][,2]), "F") * norm(as.matrix(Anorm[,1]), "F"))
abs(t(acmtf_result$Fac[[1]][,3]) %*% Anorm[,2]) / (norm(as.matrix(acmtf_result$Fac[[1]][,3]), "F") * norm(as.matrix(Anorm[,2]), "F"))
abs(t(acmtf_result$Fac[[1]][,1]) %*% Anorm[,3]) / (norm(as.matrix(acmtf_result$Fac[[1]][,1]), "F") * norm(as.matrix(Anorm[,3]), "F"))
```
