---
title: "CMTF_noise_simulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CMTF_noise_simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 12,
  fig.height = 6
)
```

```{r setup}
library(CMTFtoolbox)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(rTensor)

set.seed(123)
```

```{r define helper functions}
FMS_to_simulation = function(inputFac, Fac, modes){
  numComponents = ncol(Fac[[1]])
  numModes = max(unlist(modes))
  numDatasets = length(modes)
  normalizedInputFac = normalizeFac(inputFac, modes)
  normalizedFac = normalizeFac(Fac, modes)
  
  FMS_result = 1:numComponents
  for(i in 1:numComponents){
    FMS = 1
    ksi = 0
    ksi_hat = 0
    
    for(j in 1:numModes){
      vect1 = normalizedInputFac$Fac[[j]][,i]
      vect2 = normalizedFac$Fac[[j]][,i]
      FMS = FMS * (t(vect1) %*% vect2)
    }
    
    for(j in 1:numDatasets){
      ksi = ksi + normalizedInputFac$normsPerDataset[j,i]
      ksi_hat = ksi_hat + normalizedFac$normsPerDataset[j,i]
    }
    ksi_term = ((abs(ksi - ksi_hat)) / max(ksi, ksi_hat))
    FMS_result[i] = (1 - ksi_term) * abs(FMS)
  }
  return(min(FMS_result))
}
```

# Robustness towards noise

## Tensor-matrix case

```{r simulate noisy tensor-matrix data}
R = 3
I = 50
J = 50
K = 50
L = 50
modes = list(c(1,2,3), c(1,4))

# Generate loading matrices, normalize each vector to 1
A = array(rnorm(I*R), c(I, R))  # shared subject mode
Anorm = sweep(A, 2, apply(A, 2, function(x){norm(as.matrix(x), "F")}), FUN="/")
B = array(rnorm(J*R), c(J, R))  # distinct feature mode of X1
Bnorm = sweep(B, 2, apply(B, 2, function(x){norm(as.matrix(x), "F")}), FUN="/")
C = array(rnorm(K*R), c(K, R))  # distinct condition mode of X1
Cnorm = sweep(C, 2, apply(C, 2, function(x){norm(as.matrix(x), "F")}), FUN="/")
D = array(rnorm(L*R), c(L, R))  # distinct feature mode of X2
Dnorm = sweep(D, 2, apply(D, 2, function(x){norm(as.matrix(x), "F")}), FUN="/")

# Generate datasets without noise
df1 = as.tensor(array(0L, c(I,J,K)))
df1norm = df1
df2 = as.tensor(array(0L, c(I,L)))
df2norm = df2
for(r in 1:R){
  X1_component_norm = as.tensor(reinflateTensor(Anorm[,r], Bnorm[,r], Cnorm[,r]))
  X2_component_norm = as.tensor(reinflateMatrix(Anorm[,r], Dnorm[,r]))
  
  df1 = df1 + (round(runif(1, min=0, max=25)) + 1) * X1_component_norm
  df1norm = df1norm + X1_component_norm
  df2 = df2 + (round(runif(1, min=0, max=25)) + 1) * X2_component_norm
  df2norm = df2norm + X2_component_norm
}

# Generate noise
df1_noise = as.tensor(array(rnorm(I*J*K), c(I,J,K)))
df2_noise = as.tensor(array(rnorm(I*L), c(I,L)))

# Create final datasets by adding the noise of different sizes to the generated data
X1_010 = df1 + 0.10 * df1_noise * fnorm(df1) / fnorm(df1_noise)
X1_025 = df1 + 0.25 * df1_noise * fnorm(df1) / fnorm(df1_noise)
X1_035 = df1 + 0.35 * df1_noise * fnorm(df1) / fnorm(df1_noise)

X2_010 = df2 + 0.10 * df2_noise * fnorm(df2) / fnorm(df2_noise)
X2_025 = df2 + 0.25 * df2_noise * fnorm(df2) / fnorm(df2_noise)
X2_035 = df2 + 0.35 * df2_noise * fnorm(df2) / fnorm(df2_noise)

X1_010_norm = df1norm + 0.10 * df1_noise * fnorm(df1norm) / fnorm(df1_noise)
X1_025_norm = df1norm + 0.25 * df1_noise * fnorm(df1norm) / fnorm(df1_noise)
X1_035_norm = df1norm + 0.35 * df1_noise * fnorm(df1norm) / fnorm(df1_noise)

X2_010_norm = df2norm + 0.10 * df2_noise * fnorm(df2norm) / fnorm(df2_noise)
X2_025_norm = df2norm + 0.25 * df2_noise * fnorm(df2norm) / fnorm(df2_noise)
X2_035_norm = df2norm + 0.35 * df2_noise * fnorm(df2norm) / fnorm(df2_noise)

# Prepare CMTF input
Z_010 = setupCMTFdata(list(X1_010_norm@data, X2_010_norm@data), modes, normalize=FALSE)
Z_025 = setupCMTFdata(list(X1_025_norm@data, X2_025_norm@data), modes, normalize=FALSE)
Z_035 = setupCMTFdata(list(X1_035_norm@data, X2_035_norm@data), modes, normalize=FALSE)

Z_010_norm = setupCMTFdata(list(X1_010_norm@data, X2_010_norm@data), modes, normalize=FALSE)
Z_025_norm = setupCMTFdata(list(X1_025_norm@data, X2_025_norm@data), modes, normalize=FALSE)
Z_035_norm = setupCMTFdata(list(X1_035_norm@data, X2_035_norm@data), modes, normalize=FALSE)
```

```{r run CMTF with noisy tensor-matrix data}
# Settings
nstart = 8 #30
rel_tol = 1e-8
grad_tol = 1e-8
max_fn = 10^4
max_iter = 10^3

CMTF_010 = cmtf_opt(Z_010, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
CMTF_025 = cmtf_opt(Z_025, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
CMTF_035 = cmtf_opt(Z_035, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)

CMTF_010_norm = cmtf_opt(Z_010_norm, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
CMTF_025_norm = cmtf_opt(Z_025_norm, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
CMTF_035_norm = cmtf_opt(Z_035_norm, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
```

```{r FMS calculation for noisy tensor-matrix data}
inputFac = list(Anorm,Bnorm,Cnorm,Dnorm)
inputFac = vect_to_fac(unlist(inputFac), Z_010, sortComponents=TRUE)

result_Tensor_Matrix = array(0L, c(6, length(CMTF_010)))
for(i in 1:length(CMTF_010)){
  result_Tensor_Matrix[1,i] = FMS_to_simulation(inputFac, CMTF_010[[i]]$Fac, Z_010$modes)
  result_Tensor_Matrix[2,i] = FMS_to_simulation(inputFac, CMTF_025[[i]]$Fac, Z_010$modes)
  result_Tensor_Matrix[3,i] = FMS_to_simulation(inputFac, CMTF_035[[i]]$Fac, Z_010$modes)
  
  result_Tensor_Matrix[4,i] = FMS_to_simulation(inputFac, CMTF_010_norm[[i]]$Fac, Z_010$modes)
  result_Tensor_Matrix[5,i] = FMS_to_simulation(inputFac, CMTF_025_norm[[i]]$Fac, Z_010$modes)
  result_Tensor_Matrix[6,i] = FMS_to_simulation(inputFac, CMTF_035_norm[[i]]$Fac, Z_010$modes)
}

result_Tensor_Matrix
rowSums((result_Tensor_Matrix > 0.99^4) / nstart) * 100
rowMeans(result_Tensor_Matrix)
```

## Tensor-tensor case

```{r simulate noisy tensor-tensor data}
R = 3
I = 100
J = 100
K = 100
L = 100
M = 100
modes = list(c(1,2,3), c(1,4,5))

# Generate loading matrices, normalize each vector to 1
A = array(rnorm(I*R), c(I, R))  # shared subject mode
Anorm = sweep(A, 2, apply(A, 2, function(x){norm(as.matrix(x), "F")}), FUN="/")
B = array(rnorm(J*R), c(J, R))  # distinct feature mode of X1
Bnorm = sweep(B, 2, apply(B, 2, function(x){norm(as.matrix(x), "F")}), FUN="/")
C = array(rnorm(K*R), c(K, R))  # distinct condition mode of X1
Cnorm = sweep(C, 2, apply(C, 2, function(x){norm(as.matrix(x), "F")}), FUN="/")
D = array(rnorm(L*R), c(L, R))  # distinct feature mode of X2
Dnorm = sweep(D, 2, apply(D, 2, function(x){norm(as.matrix(x), "F")}), FUN="/")
E = array(rnorm(M*R), c(M, R))  # distinct condition mode of X2
Enorm = sweep(E, 2, apply(E, 2, function(x){norm(as.matrix(x), "F")}), FUN="/")

# Generate datasets without noise
df1 = as.tensor(array(0L, c(I,J,K)))
df1norm = df1
df2 = as.tensor(array(0L, c(I,L,M)))
df2norm = df2
for(r in 1:R){
  X1_component_norm = as.tensor(reinflateTensor(Anorm[,r], Bnorm[,r], Cnorm[,r]))
  X2_component_norm = as.tensor(reinflateTensor(Anorm[,r], Dnorm[,r], Enorm[,r]))
  
  df1 = df1 + (round(runif(1, min=0, max=25)) + 1) * X1_component_norm
  df1norm = df1norm + X1_component_norm
  df2 = df2 + (round(runif(1, min=0, max=25)) + 1) * X2_component_norm
  df2norm = df2norm + X2_component_norm
}

# Generate noise
df1_noise = as.tensor(array(rnorm(I*J*K), c(I,J,K)))
df2_noise = as.tensor(array(rnorm(I*L*M), c(I,L,M)))

# Create final datasets by adding the noise of different sizes to the generated data
X1_010 = df1 + 0.10 * df1_noise * fnorm(df1) / fnorm(df1_noise)
X1_025 = df1 + 0.25 * df1_noise * fnorm(df1) / fnorm(df1_noise)
X1_035 = df1 + 0.35 * df1_noise * fnorm(df1) / fnorm(df1_noise)

X2_010 = df2 + 0.10 * df2_noise * fnorm(df2) / fnorm(df2_noise)
X2_025 = df2 + 0.25 * df2_noise * fnorm(df2) / fnorm(df2_noise)
X2_035 = df2 + 0.35 * df2_noise * fnorm(df2) / fnorm(df2_noise)

X1_010_norm = df1norm + 0.10 * df1_noise * fnorm(df1norm) / fnorm(df1_noise)
X1_025_norm = df1norm + 0.25 * df1_noise * fnorm(df1norm) / fnorm(df1_noise)
X1_035_norm = df1norm + 0.35 * df1_noise * fnorm(df1norm) / fnorm(df1_noise)

X2_010_norm = df2norm + 0.10 * df2_noise * fnorm(df2norm) / fnorm(df2_noise)
X2_025_norm = df2norm + 0.25 * df2_noise * fnorm(df2norm) / fnorm(df2_noise)
X2_035_norm = df2norm + 0.35 * df2_noise * fnorm(df2norm) / fnorm(df2_noise)

# Prepare CMTF input
Z_010 = setupCMTFdata(list(X1_010_norm@data, X2_010_norm@data), modes, normalize=FALSE)
Z_025 = setupCMTFdata(list(X1_025_norm@data, X2_025_norm@data), modes, normalize=FALSE)
Z_035 = setupCMTFdata(list(X1_035_norm@data, X2_035_norm@data), modes, normalize=FALSE)

Z_010_norm = setupCMTFdata(list(X1_010_norm@data, X2_010_norm@data), modes, normalize=FALSE)
Z_025_norm = setupCMTFdata(list(X1_025_norm@data, X2_025_norm@data), modes, normalize=FALSE)
Z_035_norm = setupCMTFdata(list(X1_035_norm@data, X2_035_norm@data), modes, normalize=FALSE)
```

```{r run CMTF with noisy tensor-tensor data}
# Settings
nstart = 8 #30
rel_tol = 1e-8
grad_tol = 1e-8
max_fn = 10^4
max_iter = 10^3

CMTF_010 = cmtf_opt(Z_010, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
CMTF_025 = cmtf_opt(Z_025, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
CMTF_035 = cmtf_opt(Z_035, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)

CMTF_010_norm = cmtf_opt(Z_010_norm, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
CMTF_025_norm = cmtf_opt(Z_025_norm, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
CMTF_035_norm = cmtf_opt(Z_035_norm, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
```

```{r FMS calculation for noisy tensor-matrix data}
inputFac = list(Anorm,Bnorm,Cnorm,Dnorm,Enorm)
inputFac = vect_to_fac(unlist(inputFac), Z_010, sortComponents=TRUE)

result_Tensor_Tensor = array(0L, c(6, length(CMTF_010)))
for(i in 1:length(CMTF_010)){
  result_Tensor_Tensor[1,i] = FMS_to_simulation(inputFac, CMTF_010[[i]]$Fac, Z_010$modes)
  result_Tensor_Tensor[2,i] = FMS_to_simulation(inputFac, CMTF_025[[i]]$Fac, Z_010$modes)
  result_Tensor_Tensor[3,i] = FMS_to_simulation(inputFac, CMTF_035[[i]]$Fac, Z_010$modes)
  
  result_Tensor_Tensor[4,i] = FMS_to_simulation(inputFac, CMTF_010_norm[[i]]$Fac, Z_010$modes)
  result_Tensor_Tensor[5,i] = FMS_to_simulation(inputFac, CMTF_025_norm[[i]]$Fac, Z_010$modes)
  result_Tensor_Tensor[6,i] = FMS_to_simulation(inputFac, CMTF_035_norm[[i]]$Fac, Z_010$modes)
}

result_Tensor_Tensor
rowSums((result_Tensor_Tensor > 0.99^5) / nstart) * 100
rowMeans(result_Tensor_Tensor)
```

## Matrix-tensor-matrix case
