---
title: "CMTF_missing_simulation"
output: html_document
date: "2024-08-19"
---

---
title: "CMTF_noise_simulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CMTF_noise_simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 12,
  fig.height = 6
)
```

```{r setup}
library(CMTFtoolbox)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(rTensor)

set.seed(123)
```

## Tensor-matrix case

```{r simulate noisy tensor-matrix data}
R = 3
I = 100
J = 100
K = 100
L = 100
modes = list(c(1,2,3), c(1,4))

# Generate loading matrices, normalize each vector to 1
A = array(rnorm(I*R), c(I, R))  # shared subject mode
B = array(rnorm(J*R), c(J, R))  # distinct feature mode of X1
C = array(rnorm(K*R), c(K, R))  # distinct condition mode of X1
D = array(rnorm(L*R), c(L, R))  # distinct feature mode of X2

# Generate datasets without noise
df1 = as.tensor(reinflateTensor(A, B, C))
df2 = as.tensor(reinflateMatrix(A, D))

# Set M% of data missing in df1
missingNess = c(seq(0.3, 0.9, 0.1), 0.95, 0.99)
missingIndices = list()
df1_list = list()
for(i in 1:length(missingNess)){
  outcome = produce_NA(df1@data, mechanism="MCAR", perc.missing=missingNess[i])
  df1_list[[i]] = as.tensor(outcome$data.incomp)
  missingIndices[[i]] = outcome$idx_newNA
}

# Prepare CMTF input
Z_010 = setupCMTFdata(list(X1_010_norm@data, X2_010_norm@data), modes, normalize=FALSE)
Z_025 = setupCMTFdata(list(X1_025_norm@data, X2_025_norm@data), modes, normalize=FALSE)
Z_035 = setupCMTFdata(list(X1_035_norm@data, X2_035_norm@data), modes, normalize=FALSE)

Z_010_norm = setupCMTFdata(list(X1_010_norm@data, X2_010_norm@data), modes, normalize=FALSE)
Z_025_norm = setupCMTFdata(list(X1_025_norm@data, X2_025_norm@data), modes, normalize=FALSE)
Z_035_norm = setupCMTFdata(list(X1_035_norm@data, X2_035_norm@data), modes, normalize=FALSE)
```

```{r run CMTF with noisy tensor-matrix data}
# Settings
nstart = 8 #30
rel_tol = 1e-8
grad_tol = 1e-8
max_fn = 10^4
max_iter = 10^3

CMTF_010 = cmtf_opt(Z_010, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
CMTF_025 = cmtf_opt(Z_025, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
CMTF_035 = cmtf_opt(Z_035, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)

CMTF_010_norm = cmtf_opt(Z_010_norm, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
CMTF_025_norm = cmtf_opt(Z_025_norm, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
CMTF_035_norm = cmtf_opt(Z_035_norm, R, initialization="random", rel_tol=rel_tol, grad_tol=grad_tol, max_fn=max_fn, max_iter=max_iter, nstart=nstart, numCores=8, allOutput=TRUE)
```

```{r FMS calculation for noisy tensor-matrix data}
inputFac = list(Anorm,Bnorm,Cnorm,Dnorm)
inputFac = vect_to_fac(unlist(inputFac), Z_010, sortComponents=TRUE)

result_Tensor_Matrix = array(0L, c(6, length(CMTF_010)))
for(i in 1:length(CMTF_010)){
  result_Tensor_Matrix[1,i] = FMS_to_simulation(inputFac, CMTF_010[[i]]$Fac, Z_010$modes)
  result_Tensor_Matrix[2,i] = FMS_to_simulation(inputFac, CMTF_025[[i]]$Fac, Z_010$modes)
  result_Tensor_Matrix[3,i] = FMS_to_simulation(inputFac, CMTF_035[[i]]$Fac, Z_010$modes)
  
  result_Tensor_Matrix[4,i] = FMS_to_simulation(inputFac, CMTF_010_norm[[i]]$Fac, Z_010$modes)
  result_Tensor_Matrix[5,i] = FMS_to_simulation(inputFac, CMTF_025_norm[[i]]$Fac, Z_010$modes)
  result_Tensor_Matrix[6,i] = FMS_to_simulation(inputFac, CMTF_035_norm[[i]]$Fac, Z_010$modes)
}

result_Tensor_Matrix
rowSums((result_Tensor_Matrix > 0.99^4) / nstart) * 100
rowMeans(result_Tensor_Matrix)
```
