---
title: "20241203_ACMTF_validation"
author: "G.R. van der Ploeg"
date: "2024-12-03"
output: html_document
---

# Preamble
```{r setup, include=FALSE}
library(rTensor)
library(CMTFtoolbox)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(scales)
```

```{r load input loadings}
inputLoadings = readRDS("./20241203_input_loadings_Y_inside.RDS")
```

```{r load datasets}
X1_final = readRDS("./20241203_X1_Y_inside.RDS")
X2_final = readRDS("./20241203_X2_Y_inside.RDS")
X3_final = readRDS("./20241203_X3_Y_inside.RDS")
```

```{r load ACMTF models}
ACMTF_models = readRDS("./20241203_ACMTF_models_Y_inside.RDS")
ACMTF_CV_models = readRDS("./20241203_ACMTF_CV_models_Y_inside.RDS")
ACMTF_CV_params = readRDS("./20241203_ACMTF_CV_params_Y_inside.RDS")
ACMTF_YAS_models = readRDS("./20241203_ACMTF_YAS_models_Y_inside.RDS")
ACMTFR_models = readRDS("./20241203_ACMTFR_models_Y_inside.RDS")
```

# Sanity checks
```{r plot loadings}
a = inputLoadings[[1]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% ggplot(aes(x=index,y=value,col=as.factor(name))) + geom_line() + xlab("Subject index") + ylab("Value") + scale_colour_manual(name="Component", labels=c("a_global1", "a_global2", "a_local1", "a_local2", "a_distinct1", "a_distinct2", "a_distinct3"), values=hue_pal()(7))

b = inputLoadings[[2]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% ggplot(aes(x=index,y=value,col=as.factor(name))) + geom_line() + xlab("Feature index") + ylab("Value") + scale_colour_manual(name="Component", labels=c("b_global1_X1", "b_global1_X2", "b_global1_X3", "b_global2_X1", "b_global2_X2", "b_global2_X3", "b_local1_X1", "b_local1_X2", "b_local2_X1", "b_local2_X2", "b_distinct1", "b_distinct2", "b_distinct3"), values=hue_pal()(13))

c = inputLoadings[[3]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% ggplot(aes(x=index,y=value,col=as.factor(name))) + geom_line() + xlab("Time index") + ylab("Value") + scale_colour_manual(name="Component", labels=c("c_global1_X1", "c_global1_X2", "c_global1_X3", "c_global2_X1", "c_global2_X2", "c_global2_X3", "c_local1_X1", "c_local1_X2", "c_local2_X1", "c_local2_X2", "c_distinct1", "c_distinct2", "c_distinct3"), values=hue_pal()(13))

ggarrange(a,b,c,nrow=3)
```

```{r parafac models of the X blocks}
set.seed(789)
pfac1 = parafac4microbiome::parafac(X1_final, 5)
pfac2 = parafac4microbiome::parafac(X2_final, 5)
pfac3 = parafac4microbiome::parafac(X3_final, 3)

cor(pfac1$Fac[[1]], inputLoadings[[1]])
cor(pfac2$Fac[[1]], inputLoadings[[1]])
cor(pfac3$Fac[[1]], inputLoadings[[1]])
```

```{r plot parafac models of the x blocks - subject loadings}
empty = ggplot()

# Block X1
a = cbind(inputLoadings[[1]][,1], pfac1$Fac[[1]][,4]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("PARAFAC") + ggtitle("Global 1")
b = cbind(inputLoadings[[1]][,2], pfac1$Fac[[1]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Global 2")
c = cbind(inputLoadings[[1]][,3], pfac1$Fac[[1]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Local 1")
d = cbind(inputLoadings[[1]][,4], pfac1$Fac[[1]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Local 2")
e = cbind(inputLoadings[[1]][,5], pfac1$Fac[[1]][,5]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Distinct 1")
f = empty + ggtitle("Distinct 2")
g = empty + ggtitle("Distinct 3")

# Block X2
h = cbind(inputLoadings[[1]][,1], pfac2$Fac[[1]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("PARAFAC")
i = cbind(inputLoadings[[1]][,2], pfac2$Fac[[1]][,5]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
j = cbind(inputLoadings[[1]][,3], pfac2$Fac[[1]][,4]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
k = cbind(inputLoadings[[1]][,4], pfac2$Fac[[1]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
l = empty
m = cbind(inputLoadings[[1]][,6], pfac2$Fac[[1]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
n = empty

# Block X3
o = cbind(inputLoadings[[1]][,1], pfac3$Fac[[1]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("PARAFAC")
p = cbind(inputLoadings[[1]][,2], pfac3$Fac[[1]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
q = empty
r = empty
s = empty
t = empty
u = cbind(inputLoadings[[1]][,7], pfac3$Fac[[1]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")

plot = ggarrange(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u, nrow=3, ncol=7)
annotate_figure(plot, top = text_grob("Subject loadings"))
```

```{r plot parafac models of the x blocks - feature loadings}
empty = ggplot()

# Block X1
a = cbind(inputLoadings[[2]][,1], pfac1$Fac[[2]][,4]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("PARAFAC") + ggtitle("Global 1")
b = cbind(inputLoadings[[2]][,4], pfac1$Fac[[2]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Global 2")
c = cbind(inputLoadings[[2]][,7], pfac1$Fac[[2]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Local 1")
d = cbind(inputLoadings[[2]][,9], pfac1$Fac[[2]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Local 2")
e = cbind(inputLoadings[[2]][,11], pfac1$Fac[[2]][,5]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Distinct 1")
f = empty + ggtitle("Distinct 2")
g = empty + ggtitle("Distinct 3")

# Block X2
h = cbind(inputLoadings[[2]][,2], pfac2$Fac[[2]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("PARAFAC")
i = cbind(inputLoadings[[2]][,5], pfac2$Fac[[2]][,5]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
j = cbind(inputLoadings[[2]][,8], pfac2$Fac[[2]][,4]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
k = cbind(inputLoadings[[2]][,10], pfac2$Fac[[2]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
l = empty
m = cbind(inputLoadings[[2]][,12], pfac2$Fac[[2]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
n = empty

# Block X3
o = cbind(inputLoadings[[2]][,3], pfac3$Fac[[2]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("PARAFAC")
p = cbind(inputLoadings[[2]][,6], pfac3$Fac[[2]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
q = empty
r = empty
s = empty
t = empty
u = cbind(inputLoadings[[2]][,13], pfac3$Fac[[2]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")

plot = ggarrange(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u, nrow=3, ncol=7)
annotate_figure(plot, top = text_grob("Feature loadings"))
```

```{r plot parafac models of the x blocks - time loadings}
empty = ggplot()

# Block X1
a = cbind(inputLoadings[[3]][,1], pfac1$Fac[[3]][,4]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("PARAFAC") + ggtitle("Global 1")
b = cbind(inputLoadings[[3]][,4], pfac1$Fac[[3]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Global 2")
c = cbind(inputLoadings[[3]][,7], pfac1$Fac[[3]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Local 1")
d = cbind(inputLoadings[[3]][,9], pfac1$Fac[[3]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Local 2")
e = cbind(inputLoadings[[3]][,11], pfac1$Fac[[3]][,5]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Distinct 1")
f = empty + ggtitle("Distinct 2")
g = empty + ggtitle("Distinct 3")

# Block X2
h = cbind(inputLoadings[[3]][,2], pfac2$Fac[[3]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("PARAFAC")
i = cbind(inputLoadings[[3]][,5], pfac2$Fac[[3]][,5]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
j = cbind(inputLoadings[[3]][,8], pfac2$Fac[[3]][,4]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
k = cbind(inputLoadings[[3]][,10], pfac2$Fac[[3]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
l = empty
m = cbind(inputLoadings[[3]][,12], pfac2$Fac[[3]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
n = empty

# Block X3
o = cbind(inputLoadings[[3]][,3], pfac3$Fac[[3]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("PARAFAC")
p = cbind(inputLoadings[[3]][,6], pfac3$Fac[[3]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
q = empty
r = empty
s = empty
t = empty
u = cbind(inputLoadings[[3]][,13], pfac3$Fac[[3]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")

plot = ggarrange(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u, nrow=3, ncol=7)
annotate_figure(plot, top = text_grob("Time loadings"))
```

# Analyze ACMTF results
```{r plot varExps for ACMTF}
ACMTF_varExps = do.call(rbind, lapply(ACMTF_models, FUN=function(x){(x$varExp)})) %>% as_tibble()
ACMTF_varExps = ACMTF_varExps * 100
colnames(ACMTF_varExps) = c("X1", "X2", "X3")
ACMTF_varExps = ACMTF_varExps %>% mutate(index=1:nrow(.))

correctModels = ACMTF_varExps %>% filter(X1 > 99, X2 > 99, X3 > 99) %>% select(index) %>% pull()
ACMTF_varExps = ACMTF_varExps %>% mutate(correct = index %in% correctModels)

ACMTF_models_correct = ACMTF_models[ACMTF_varExps$index %in% correctModels]
ACMTF_models_incorrect = ACMTF_models[!ACMTF_varExps$index %in% correctModels]

a = ACMTF_varExps %>% ggplot(aes(x=index,y=X1,fill=as.factor(correct))) + geom_bar(stat="identity") + xlab("") + ylab("varExp X1 (%)")
b = ACMTF_varExps %>% ggplot(aes(x=index,y=X2,fill=as.factor(correct))) + geom_bar(stat="identity") + xlab("") + ylab("varExp X2 (%)")
c = ACMTF_varExps %>% ggplot(aes(x=index,y=X3,fill=as.factor(correct))) + geom_bar(stat="identity") + xlab("Model index") + ylab("varExp X3 (%)")
ggarrange(a,b,c,nrow=3, common.legend=TRUE)
```

```{r inspect lambdas for ACMTF}
ACMTF_models_correct[[1]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Lambdas (correct model)")

ACMTF_models_incorrect[[1]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Lambdas (incorrect model)")

do.call(rbind, lapply(ACMTF_models, FUN=function(x){x$Fac[[8]]} %>% as_tibble() %>% mutate(index=1:nrow(.))))
```

```{r plot correct acmtf model loadings vs input - subject loadings}
model = ACMTF_models_correct[[1]]
cor(model$Fac[[1]], inputLoadings[[1]])

# Subject loadings
a = cbind(inputLoadings[[1]][,1], model$Fac[[1]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("ACMTF") + ggtitle("Global 1")
b = cbind(inputLoadings[[1]][,2], model$Fac[[1]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Global 2")
c = cbind(inputLoadings[[1]][,3], model$Fac[[1]][,4]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Local 1")
d = cbind(inputLoadings[[1]][,4], model$Fac[[1]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Local 2")
e = cbind(inputLoadings[[1]][,5], model$Fac[[1]][,6]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Distinct 1")
f = cbind(inputLoadings[[1]][,6], model$Fac[[1]][,7]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Distinct 2")
g = cbind(inputLoadings[[1]][,7], model$Fac[[1]][,5]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Distinct 3")

plot = ggarrange(a,b,c,d,e,f,g, nrow=1, ncol=7)
annotate_figure(plot, top = text_grob("Subject loadings (correct model)"))
```

```{r plot correct acmtf model loadings vs input - feature loadings}
model = ACMTF_models_correct[[1]]
empty = ggplot()

cor(model$Fac[[2]], inputLoadings[[2]])
cor(model$Fac[[4]], inputLoadings[[2]])
cor(model$Fac[[6]], inputLoadings[[2]])

# Block X1
a = cbind(inputLoadings[[2]][,1], model$Fac[[2]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("ACMTF") + ggtitle("Global 1")
b = cbind(inputLoadings[[2]][,4], model$Fac[[2]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Global 2")
c = cbind(inputLoadings[[2]][,7], model$Fac[[2]][,4]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Local 1")
d = cbind(inputLoadings[[2]][,9], model$Fac[[2]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Local 2")
e = cbind(inputLoadings[[2]][,11], model$Fac[[2]][,6]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Distinct 1")
f = empty + ggtitle("Distinct 2")
g = empty + ggtitle("Distinct 3")

# Block X2
h = cbind(inputLoadings[[2]][,2], model$Fac[[4]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("ACMTF")
i = cbind(inputLoadings[[2]][,5], model$Fac[[4]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
j = cbind(inputLoadings[[2]][,8], model$Fac[[4]][,4]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
k = cbind(inputLoadings[[2]][,10], model$Fac[[4]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
l = empty
m = cbind(inputLoadings[[2]][,12], model$Fac[[4]][,7]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
n = empty

# Block X3
o = cbind(inputLoadings[[2]][,3], model$Fac[[6]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("ACMTF")
p = cbind(inputLoadings[[2]][,6], model$Fac[[6]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
q = empty
r = empty
s = empty
t = empty
u = cbind(inputLoadings[[2]][,13], model$Fac[[6]][,5]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")

plot = ggarrange(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u, nrow=3, ncol=7)
annotate_figure(plot, top = text_grob("Feature loadings (correct model)"))
```

```{r plot correct acmtf model loadings vs input - time loadings}
model = ACMTF_models_correct[[1]]
empty = ggplot()

cor(model$Fac[[3]], inputLoadings[[3]])
cor(model$Fac[[5]], inputLoadings[[3]])
cor(model$Fac[[7]], inputLoadings[[3]])

# Block X1
a = cbind(inputLoadings[[3]][,1], model$Fac[[3]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("ACMTF") + ggtitle("Global 1")
b = cbind(inputLoadings[[3]][,4], model$Fac[[3]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Global 2")
c = cbind(inputLoadings[[3]][,7], model$Fac[[3]][,4]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Local 1")
d = cbind(inputLoadings[[3]][,9], model$Fac[[3]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Local 2")
e = cbind(inputLoadings[[3]][,11], model$Fac[[3]][,6]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("") + ggtitle("Distinct 1")
f = empty + ggtitle("Distinct 2")
g = empty + ggtitle("Distinct 3")

# Block X2
h = cbind(inputLoadings[[3]][,2], model$Fac[[5]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("ACMTF")
i = cbind(inputLoadings[[3]][,5], model$Fac[[5]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
j = cbind(inputLoadings[[3]][,8], model$Fac[[5]][,4]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
k = cbind(inputLoadings[[3]][,10], model$Fac[[5]][,3]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
l = empty
m = cbind(inputLoadings[[3]][,12], model$Fac[[5]][,7]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
n = empty

# Block X3
o = cbind(inputLoadings[[3]][,3], model$Fac[[7]][,2]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("ACMTF")
p = cbind(inputLoadings[[3]][,6], model$Fac[[7]][,1]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")
q = empty
r = empty
s = empty
t = empty
u = cbind(inputLoadings[[3]][,13], model$Fac[[7]][,5]) %>% as_tibble() %>% ggplot(aes(x=V1,y=V2)) + geom_point() + xlab("Input") + ylab("")

plot = ggarrange(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u, nrow=3, ncol=7)
annotate_figure(plot, top = text_grob("Time loadings (correct model)"))
```

```{r plot ACMTF of an incorrect model}
model = ACMTF_models_incorrect[[1]]

a = cor(model$Fac[[1]]) %>% as_tibble() %>% mutate(index=1:7) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(7,6,5,4,3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + ylab("Component number")

b = model$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Lambdas (incorrect model)")

c = cor(model$Fac[[1]], inputLoadings[[1]]) %>% as_tibble() %>% mutate(index=1:7) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(7,6,5,4,3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + ylab("Component number")

ggarrange(a,b,c)


# Make sense of this result
## Component 3
a = cbind(model$Fac[[1]][,3], inputLoadings[[1]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("a_global1") + ylab("Component 3")
b = cbind(model$Fac[[6]][,3], inputLoadings[[2]][,3]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("b_global1_X3") + ylab("")
c = cbind(model$Fac[[7]][,3], inputLoadings[[3]][,3]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("c_global1_X3") + ylab("")

## Component 5
d = cbind(model$Fac[[1]][,5], inputLoadings[[1]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("a_global1") + ylab("Component 5")
e = cbind(model$Fac[[4]][,5], inputLoadings[[2]][,2]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("b_global1_X2") + ylab("")
f = cbind(model$Fac[[5]][,5], inputLoadings[[3]][,2]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("c_global1_X2") + ylab("")

## Component 6
g = cbind(model$Fac[[1]][,6], inputLoadings[[1]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("a_global1") + ylab("Component 6")
h = cbind(model$Fac[[2]][,6], inputLoadings[[2]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("b_global1_X1") + ylab("")
i = cbind(model$Fac[[3]][,6], inputLoadings[[3]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("c_global1_X1") + ylab("")

ggarrange(a,b,c,d,e,f,g,h,i, nrow=3, ncol=3)
```

# ACMTF CV
```{r plot varExps for ACMTF CV}
ACMTF_CV_varExps = do.call(rbind, lapply(ACMTF_CV_models, FUN=function(x){(x$varExp)})) %>% as_tibble()
ACMTF_CV_varExps = ACMTF_CV_varExps * 100
colnames(ACMTF_CV_varExps) = c("X1", "X2", "X3")
ACMTF_CV_varExps = ACMTF_CV_varExps %>% mutate(beta = ACMTF_CV_params)

ACMTF_CV_varExps %>% pivot_longer(-beta) %>% ggplot(aes(x=as.factor(beta),y=value)) + facet_wrap(~name, nrow=3) + geom_boxplot() + xlab("beta") + ylab("Variance explained (%)")
```

```{r plot default ACMTF model from CV}
modelNumber = 30
model = ACMTF_CV_models[[30]]

a = cor(model$Fac[[1]]) %>% as_tibble() %>% mutate(index=1:7) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(7,6,5,4,3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + ylab("Component number")

b = model$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1"))

c = cor(model$Fac[[1]], inputLoadings[[1]]) %>% as_tibble() %>% mutate(index=1:7) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(7,6,5,4,3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Input", labels=c("Global1", "Global2", "Local1", "Local2", "Distinct1", "Distinct2", "Distinct3")) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + ylab("Component number")

ggarrange(a,b,c)

# Explain this result
## Component 1
a = cbind(model$Fac[[1]][,1], inputLoadings[[1]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("a_global1") + ylab("Component 1")
b = cbind(model$Fac[[2]][,1], inputLoadings[[2]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("b_global1_X1") + ylab("Component 1")
c = cbind(model$Fac[[3]][,1], inputLoadings[[3]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("c_global1_X1") + ylab("Component 1")
d = cbind(model$Fac[[4]][,1], inputLoadings[[2]][,2]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("b_global1_X2") + ylab("Component 1")
e = cbind(model$Fac[[5]][,1], inputLoadings[[3]][,2]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("c_global1_X2") + ylab("Component 1")
  
## Component 4
f = cbind(model$Fac[[1]][,4], inputLoadings[[1]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("a_global1") + ylab("Component 4")
g = cbind(model$Fac[[6]][,4], inputLoadings[[2]][,3]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("b_global1_X3") + ylab("Component 4")
h = cbind(model$Fac[[7]][,4], inputLoadings[[3]][,3]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("c_global1_X3") + ylab("Component 4")
i = empty
j = empty

ggarrange(a,b,c,d,e,f,g,h,i,j, nrow=2, ncol=5)
```

```{r plot beta 1 ACMTF model from CV}
modelNumber = 1
model = ACMTF_CV_models[[1]]

a = cor(model$Fac[[1]]) %>% as_tibble() %>% mutate(index=1:7) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(7,6,5,4,3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + ylab("Component number")

b = model$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1"))

c = cor(model$Fac[[1]], inputLoadings[[1]]) %>% as_tibble() %>% mutate(index=1:7) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(7,6,5,4,3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Input", labels=c("Global1", "Global2", "Local1", "Local2", "Distinct1", "Distinct2", "Distinct3")) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + ylab("Component number")

ggarrange(a,b,c)

# Explain this result
## Component 1
a = cbind(model$Fac[[1]][,1], inputLoadings[[1]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("a_global1") + ylab("Component 1")
b = cbind(model$Fac[[2]][,1], inputLoadings[[2]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("b_global1_X1") + ylab("Component 1")
c = cbind(model$Fac[[3]][,1], inputLoadings[[3]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("c_global1_X1") + ylab("Component 1")
d = cbind(model$Fac[[4]][,1], inputLoadings[[2]][,2]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("b_global1_X2") + ylab("Component 1")
e = cbind(model$Fac[[5]][,1], inputLoadings[[3]][,2]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("c_global1_X2") + ylab("Component 1")
  
## Component 4
f = cbind(model$Fac[[1]][,4], inputLoadings[[1]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("a_global1") + ylab("Component 4")
g = cbind(model$Fac[[6]][,4], inputLoadings[[2]][,3]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("b_global1_X3") + ylab("Component 4")
h = cbind(model$Fac[[7]][,4], inputLoadings[[3]][,3]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("c_global1_X3") + ylab("Component 4")
i = empty
j = empty

ggarrange(a,b,c,d,e,f,g,h,i,j, nrow=2, ncol=5)
```

```{r plot beta 1e-10 ACMTF model from CV}
modelNumber = 100
model = ACMTF_CV_models[[100]]

a = cor(model$Fac[[1]]) %>% as_tibble() %>% mutate(index=1:7) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(7,6,5,4,3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + ylab("Component number")

b = model$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1"))

c = cor(model$Fac[[1]], inputLoadings[[1]]) %>% as_tibble() %>% mutate(index=1:7) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(7,6,5,4,3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Input", labels=c("Global1", "Global2", "Local1", "Local2", "Distinct1", "Distinct2", "Distinct3")) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + ylab("Component number")

ggarrange(a,b,c,nrow=1)

# Explain this result
## Component 1
a = cbind(model$Fac[[1]][,1], inputLoadings[[1]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("a_global1") + ylab("Component 1")
b = cbind(model$Fac[[2]][,1], inputLoadings[[2]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("b_global1_X1") + ylab("Component 1")
c = cbind(model$Fac[[3]][,1], inputLoadings[[3]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("c_global1_X1") + ylab("Component 1")
d = cbind(model$Fac[[4]][,1], inputLoadings[[2]][,2]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("b_global1_X2") + ylab("Component 1")
e = cbind(model$Fac[[5]][,1], inputLoadings[[3]][,2]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("c_global1_X2") + ylab("Component 1")
  
## Component 4
f = cbind(model$Fac[[1]][,4], inputLoadings[[1]][,1]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("a_global1") + ylab("Component 4")
g = cbind(model$Fac[[6]][,4], inputLoadings[[2]][,3]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("b_global1_X3") + ylab("Component 4")
h = cbind(model$Fac[[7]][,4], inputLoadings[[3]][,3]) %>% as_tibble() %>% ggplot(aes(x=V2,y=V1)) + geom_point() + xlab("c_global1_X3") + ylab("Component 4")
i = empty
j = empty

ggarrange(a,b,c,d,e,f,g,h,i,j, nrow=2, ncol=5)
```

# ACMTF YAS
```{r plot varExps for ACMTF YAS}
ACMTF_YAS_varExps = do.call(rbind, lapply(ACMTF_YAS_models, FUN=function(x){(x$varExp)})) %>% as_tibble()
colnames(ACMTF_YAS_varExps) = c("X1", "X2", "X3", "Y")

a = ACMTF_YAS_varExps %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=X1)) + geom_bar(stat="identity")
b = ACMTF_YAS_varExps %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=X2)) + geom_bar(stat="identity")
c = ACMTF_YAS_varExps %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=X3)) + geom_bar(stat="identity")
d = ACMTF_YAS_varExps %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Y)) + geom_bar(stat="identity")
ggarrange(a,b,c,d,nrow=4)
```

# ACMTFR
```{r plot varExps for ACMTFR}
ACMTFR_varExps = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){(x$varExp)})) %>% as_tibble()
colnames(ACMTFR_varExps) = c("X1", "X2", "X3")

a = ACMTFR_varExps %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=X1)) + geom_bar(stat="identity")
b = ACMTFR_varExps %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=X2)) + geom_bar(stat="identity")
c = ACMTFR_varExps %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=X3)) + geom_bar(stat="identity")
ggarrange(a,b,c,nrow=3)
```
