---
title: "20241113_ACMTFR"
output: html_document
date: "2024-11-13"
---

```{r setup, include=FALSE}
library(rTensor)
library(CMTFtoolbox)
library(tidyverse)
library(ggplot2)
library(ggpubr)

set.seed(123)
```

```{r settings}
# Sizes of the blocks
numSubjects = 108
numFeatures = 100
numTimepoints = 10

# Settings
Ysize = 3
noiseOnX = 0.25 # Noise percentage on each X block
noiseOnY = 0.05 # Noise percentage on Y
w_global1 = 99
w_global2 = 99
w_local1 = 1
w_local2 = 1
w_distinct1 = 5
w_distinct2 = 5
w_distinct3 = 5

rho1 = 1
rho2 = 1
```

# Simulation
```{r subject loading generation}
r = array(rnorm(numSubjects*7), c(numSubjects, 7))
r = sweep(r, 2, colMeans(r), FUN="-")
U = svd(r)$u # creates orthogonal score vectors with norm 1 mean 0

a_global1 = U[,1]
a_global2 = U[,2]
a_local1 = U[,3]
a_local2 = U[,4]
a_distinct1 = U[,5]
a_distinct2 = U[,6]
a_distinct3 = U[,7]
```

```{r feature loading generation - different per block}
b_global1_X1 = array(0L, c(numFeatures, 1))
b_global1_X1[1:4] = 1
#b_global1_X1 = b_global1_X1 - mean(b_global1_X1)
b_global1_X1 = b_global1_X1 / norm(b_global1_X1, "2")

b_global2_X1 = array(0L, c(numFeatures, 1))
b_global2_X1[5:8] = 1
#b_global2_X1 = b_global2_X1 - mean(b_global2_X1)
b_global2_X1 = b_global2_X1 / norm(b_global2_X1, "2")

b_global1_X2 = array(0L, c(numFeatures, 1))
b_global1_X2[5:8] = 1
#b_global1_X2 = b_global1_X2 - mean(b_global1_X2)
b_global1_X2 = b_global1_X2 / norm(b_global1_X2, "2")

b_global2_X2 = array(0L, c(numFeatures, 1))
b_global2_X2[9:12] = 1
#b_global2_X2 = b_global2_X2 - mean(b_global2_X2)
b_global2_X2 = b_global2_X2 / norm(b_global2_X2, "2")

b_global1_X3 = array(0L, c(numFeatures, 1))
b_global1_X3[13:16] = 1
#b_global1_X3 = b_global1_X3 - mean(b_global1_X3)
b_global1_X3 = b_global1_X3 / norm(b_global1_X3, "2")

b_global2_X3 = array(0L, c(numFeatures, 1))
b_global2_X3[17:20] = 1
#b_global2_X3 = b_global2_X3 - mean(b_global2_X3)
b_global2_X3 = b_global2_X3 / norm(b_global2_X3, "2")

b_local1_X1 = array(0L, c(numFeatures, 1))
b_local1_X1[21:26] = 1
#b_local1_X1 = b_local1_X1 - mean(b_local1_X1)
b_local1_X1 = b_local1_X1 / norm(b_local1_X1, "2")

b_local2_X1 = array(0L, c(numFeatures, 1))
b_local2_X1[27:32] = 1
#b_local2_X1 = b_local2_X1 - mean(b_local2_X1)
b_local2_X1 = b_local2_X1 / norm(b_local2_X1, "2")

b_local1_X2 = array(0L, c(numFeatures, 1))
b_local1_X2[33:38] = 1
#b_local1_X2 = b_local1_X2 - mean(b_local1_X2)
b_local1_X2 = b_local1_X2 / norm(b_local1_X2, "2")

b_local2_X2 = array(0L, c(numFeatures, 1))
b_local2_X2[39:44] = 1
#b_local2_X2 = b_local2_X2 - mean(b_local2_X2)
b_local2_X2 = b_local2_X2 / norm(b_local2_X2, "2")

# Block 3 does not load onto the local component, as simplification

b_distinct1 = array(0L, c(numFeatures, 1))
b_distinct1[45:56] = 1
#b_distinct1 = b_distinct1 - mean(b_distinct1)
b_distinct1 = b_distinct1 / norm(b_distinct1, "2")

b_distinct2 = array(0L, c(numFeatures, 1))
b_distinct2[57:68] = 1
#b_distinct2 = b_distinct2 - mean(b_distinct2)
b_distinct2 = b_distinct2 / norm(b_distinct2, "2")

b_distinct3 = array(0L, c(numFeatures, 1))
b_distinct3[69:80] = 1
#b_distinct3 = b_distinct3 - mean(b_distinct3)
b_distinct3 = b_distinct3 / norm(b_distinct3, "2")
```

```{r time loading generation}
c_global1_X1 = t(exp(1:numTimepoints))
c_global1_X1 = c_global1_X1 - mean(c_global1_X1)
c_global1_X1 = c_global1_X1 / norm(c_global1_X1, "2")
c_global1_X1 = t(c_global1_X1)
c_global2_X1 = -1 * c_global1_X1

c_global1_X2 = t(sin(1:numTimepoints))
c_global1_X2 = c_global1_X2 - mean(c_global1_X2)
c_global1_X2 = c_global1_X2 / norm(c_global1_X2, "2")
c_global1_X2 = t(c_global1_X2)
c_global2_X2 = -1 * c_global1_X2

c_global1_X3 = t(cos(1:numTimepoints))
c_global1_X3 = c_global1_X3 - mean(c_global1_X3)
c_global1_X3 = c_global1_X3 / norm(c_global1_X3, "2")
c_global1_X3 = t(c_global1_X3)
c_global2_X3 = -1 * c_global1_X3

c_local1_X1 = t(sqrt(1:numTimepoints))
c_local1_X1 = c_local1_X1 - mean(c_local1_X1)
c_local1_X1 = c_local1_X1 / norm(c_local1_X1, "2")
c_local1_X1 = t(c_local1_X1)
c_local2_X1 = -1 * c_local1_X1

c_local1_X2 = t((1:numTimepoints)^2)
c_local1_X2 = c_local1_X2 - mean(c_local1_X2)
c_local1_X2 = c_local1_X2 / norm(c_local1_X2, "2")
c_local1_X2 = t(c_local1_X2)
c_local2_X2 = -1 * c_local1_X2

c_distinct1 = t(1:numTimepoints)
c_distinct1 = c_distinct1 - mean(c_distinct1)
c_distinct1 = c_distinct1 / norm(c_distinct1, "2")
c_distinct1 = t(c_distinct1)

c_distinct2 = t(1/(1:numTimepoints))
c_distinct2 = c_distinct2 - mean(c_distinct2)
c_distinct2 = c_distinct2 / norm(c_distinct2, "2")
c_distinct2 = t(c_distinct2)

c_distinct3 = t(log(1:numTimepoints))
c_distinct3 = c_distinct3 - mean(c_distinct3)
c_distinct3 = c_distinct3 / norm(c_distinct3, "2")
c_distinct3 = t(c_distinct3)
```

```{r simulation double check}

# Subject loadings
a = a_global1 %>% as_tibble() %>% mutate(index = 1:numSubjects) %>% ggplot(aes(x=index,y=value)) + geom_line() + ggtitle("a_global1") + xlab("") + ylab("")
b = a_global2 %>% as_tibble() %>% mutate(index = 1:numSubjects) %>% ggplot(aes(x=index,y=value)) + geom_line() + ggtitle("a_global2") + xlab("") + ylab("")
c = a_local1 %>% as_tibble() %>% mutate(index = 1:numSubjects) %>% ggplot(aes(x=index,y=value)) + geom_line() + ggtitle("a_local1") + xlab("") + ylab("")
d = a_local2 %>% as_tibble() %>% mutate(index = 1:numSubjects) %>% ggplot(aes(x=index,y=value)) + geom_line() + ggtitle("a_local2") + xlab("") + ylab("")
e = a_distinct1 %>% as_tibble() %>% mutate(index = 1:numSubjects) %>% ggplot(aes(x=index,y=value)) + geom_line() + ggtitle("a_distinct1") + xlab("") + ylab("")
f = a_distinct2 %>% as_tibble() %>% mutate(index = 1:numSubjects) %>% ggplot(aes(x=index,y=value)) + geom_line() + ggtitle("a_distinct2") + xlab("") + ylab("")
g = a_distinct3 %>% as_tibble() %>% mutate(index = 1:numSubjects) %>% ggplot(aes(x=index,y=value)) + geom_line() + ggtitle("a_distinct3") + xlab("") + ylab("")
ggarrange(a,b,c,d,e,f,g)

# Feature loadings
h = b_global1_X1 %>% as_tibble() %>% mutate(index = 1:numFeatures) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("b_global1_X1") + xlab("") + ylab("")
i = b_global2_X1 %>% as_tibble() %>% mutate(index = 1:numFeatures) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("b_global2_X1") + xlab("") + ylab("")
j = b_global1_X2 %>% as_tibble() %>% mutate(index = 1:numFeatures) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("b_global1_X2") + xlab("") + ylab("")
k = b_global2_X2 %>% as_tibble() %>% mutate(index = 1:numFeatures) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("b_global2_X2") + xlab("") + ylab("")
l = b_global1_X3 %>% as_tibble() %>% mutate(index = 1:numFeatures) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("b_global1_X3") + xlab("") + ylab("")
m = b_global1_X3 %>% as_tibble() %>% mutate(index = 1:numFeatures) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("b_global2_X3") + xlab("") + ylab("")
n = b_local1_X1 %>% as_tibble() %>% mutate(index = 1:numFeatures) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("b_local1_X1") + xlab("") + ylab("")
o = b_local2_X1 %>% as_tibble() %>% mutate(index = 1:numFeatures) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("b_local1_X1") + xlab("") + ylab("")
p = b_local1_X2 %>% as_tibble() %>% mutate(index = 1:numFeatures) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("b_local1_X2") + xlab("") + ylab("")
q = b_local2_X2 %>% as_tibble() %>% mutate(index = 1:numFeatures) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("b_local2_X2") + xlab("") + ylab("")
r = b_distinct1 %>% as_tibble() %>% mutate(index = 1:numFeatures) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("b_distinct1") + xlab("") + ylab("")
s = b_distinct2 %>% as_tibble() %>% mutate(index = 1:numFeatures) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("b_distinct2") + xlab("") + ylab("")
t = b_distinct3 %>% as_tibble() %>% mutate(index = 1:numFeatures) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("b_distinct3") + xlab("") + ylab("")
ggarrange(h,i,j,k,l,m,n,o,p,q,r,s,t)

# Time loadings
t1 = c_global1_X1 %>% as_tibble() %>% mutate(index = 1:numTimepoints) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("c_global1_X1") + xlab("") + ylab("")
t2 = c_global2_X1 %>% as_tibble() %>% mutate(index = 1:numTimepoints) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("c_global2_X1") + xlab("") + ylab("")
t3 = c_global1_X2 %>% as_tibble() %>% mutate(index = 1:numTimepoints) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("c_global1_X2") + xlab("") + ylab("")
t4 = c_global2_X2 %>% as_tibble() %>% mutate(index = 1:numTimepoints) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("c_global2_X2") + xlab("") + ylab("")
t5 = c_global1_X3 %>% as_tibble() %>% mutate(index = 1:numTimepoints) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("c_global1_X3") + xlab("") + ylab("")
t6 = c_global2_X3 %>% as_tibble() %>% mutate(index = 1:numTimepoints) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("c_global2_X3") + xlab("") + ylab("")
t7 = c_local1_X1 %>% as_tibble() %>% mutate(index = 1:numTimepoints) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("c_local1_X1") + xlab("") + ylab("")
t8 = c_local2_X1 %>% as_tibble() %>% mutate(index = 1:numTimepoints) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("c_local1_X1") + xlab("") + ylab("")
t9 = c_local1_X2 %>% as_tibble() %>% mutate(index = 1:numTimepoints) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("c_local1_X2") + xlab("") + ylab("")
t10 = c_local2_X2 %>% as_tibble() %>% mutate(index = 1:numTimepoints) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("c_local2_X2") + xlab("") + ylab("")
t11 = c_distinct1 %>% as_tibble() %>% mutate(index = 1:numTimepoints) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("c_distinct1") + xlab("") + ylab("")
t12 = c_distinct2 %>% as_tibble() %>% mutate(index = 1:numTimepoints) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("c_distinct2") + xlab("") + ylab("")
t13 = c_distinct3 %>% as_tibble() %>% mutate(index = 1:numTimepoints) %>% ggplot(aes(x=index,y=V1)) + geom_line() + ggtitle("c_distinct3") + xlab("") + ylab("")
ggarrange(t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13)
```
```{r create raw x blocks}
# Block X1
X1_term1 = parafac4microbiome::reinflateTensor(a_global1, b_global1_X1, c_global1_X1, returnAsTensor=TRUE) # rTensor::fnorm is 1
X1_term2 = parafac4microbiome::reinflateTensor(a_global2, b_global2_X1, c_global2_X1, returnAsTensor=TRUE) # rTensor::fnorm is 1
X1_term3 = parafac4microbiome::reinflateTensor(a_local1, b_local1_X1, c_local1_X1, returnAsTensor=TRUE) # rTensor::fnorm is 1
X1_term4 = parafac4microbiome::reinflateTensor(a_local2, b_local2_X1, c_local2_X1, returnAsTensor=TRUE) # rTensor::fnorm is 1
X1_term5 = parafac4microbiome::reinflateTensor(a_distinct1, b_distinct1, c_distinct1, returnAsTensor=TRUE) # rTensor::fnorm is 1

X1_raw = w_global1 * X1_term1 + w_global2 * X1_term2 + w_local1 * X1_term3 + w_local2 * X1_term4 + w_distinct1 * X1_term5

# Block X2
X2_term1 = parafac4microbiome::reinflateTensor(a_global1, b_global1_X2, c_global1_X2, returnAsTensor=TRUE) # rTensor::fnorm is 1
X2_term2 = parafac4microbiome::reinflateTensor(a_global2, b_global2_X2, c_global2_X2, returnAsTensor=TRUE) # rTensor::fnorm is 1
X2_term3 = parafac4microbiome::reinflateTensor(a_local1, b_local1_X2, c_local1_X2, returnAsTensor=TRUE) # rTensor::fnorm is 1
X2_term4 = parafac4microbiome::reinflateTensor(a_local2, b_local2_X2, c_local2_X2, returnAsTensor=TRUE) # rTensor::fnorm is 1
X2_term5 = parafac4microbiome::reinflateTensor(a_distinct2, b_distinct2, c_distinct2, returnAsTensor=TRUE) # rTensor::fnorm is 1

X2_raw = w_global1 * X2_term1 + w_global2 * X2_term2 + w_local1 * X2_term3 + w_local2 * X2_term4 + w_distinct2 * X2_term5

# Block X3
X3_term1 = parafac4microbiome::reinflateTensor(a_global1, b_global1_X3, c_global1_X3, returnAsTensor=TRUE) # rTensor::fnorm is 1
X3_term2 = parafac4microbiome::reinflateTensor(a_global2, b_global2_X3, c_global2_X3, returnAsTensor=TRUE) # rTensor::fnorm is 1
X3_term3 = parafac4microbiome::reinflateTensor(a_distinct3, b_distinct3, c_distinct3, returnAsTensor=TRUE) # rTensor::fnorm is 1

X3_raw = w_global1 * X3_term1 + w_global2 * X3_term2 + w_distinct3 * X3_term3
```

```{r add noise to x blocks}
# Create noise
noise1 = as.tensor(array(rnorm(numSubjects*numFeatures*numTimepoints), c(numSubjects, numFeatures, numTimepoints)))
noise2 = as.tensor(array(rnorm(numSubjects*numFeatures*numTimepoints), c(numSubjects, numFeatures, numTimepoints)))
noise3 = as.tensor(array(rnorm(numSubjects*numFeatures*numTimepoints), c(numSubjects, numFeatures, numTimepoints)))

# Center the noise
noise1 = parafac4microbiome::multiwayCenter(noise1)
noise2 = parafac4microbiome::multiwayCenter(noise2)
noise3 = parafac4microbiome::multiwayCenter(noise3)

# Scale the noise
noise1 = parafac4microbiome::multiwayScale(noise1)
noise2 = parafac4microbiome::multiwayScale(noise2)
noise3 = parafac4microbiome::multiwayScale(noise3)

# Put back into Tensor
noise1 = as.tensor(noise1)
noise2 = as.tensor(noise2)
noise3 = as.tensor(noise3)

# Make the noise the right frobenius norm
noise1 = fnorm(X1_raw) / (1/noiseOnX) * (noise1 / fnorm(noise1))
noise2 = fnorm(X2_raw) / (1/noiseOnX) * (noise2 / fnorm(noise2))
noise3 = fnorm(X3_raw) / (1/noiseOnX) * (noise3 / fnorm(noise3))

# Add noise to X blocks
X1_noise = X1_raw + noise1
X2_noise = X2_raw + noise2
X3_noise = X3_raw + noise3
```

```{r center and scale x blocks}
# Center
X1_cnt = parafac4microbiome::multiwayCenter(X1_noise)
X2_cnt = parafac4microbiome::multiwayCenter(X2_noise)
X3_cnt = parafac4microbiome::multiwayCenter(X3_noise)

# Scale
X1_cnt_scl = parafac4microbiome::multiwayScale(X1_cnt)
X2_cnt_scl = parafac4microbiome::multiwayScale(X2_cnt)
X3_cnt_scl = parafac4microbiome::multiwayScale(X3_cnt)

# Define final version of X
X1_final = X1_cnt_scl
X2_final = X2_cnt_scl
X3_final = X3_cnt_scl
```

```{r create Y}
Y = rho1 * a_global1 + rho2 * a_local1
noiseY = rnorm(numSubjects)
noiseY = noiseY - mean(noiseY)
noiseY = (norm(Y, "2") / (1/noiseOnY)) * (noiseY / norm(noiseY, "2"))
Ynoise = Y + noiseY
Ynorm = Ynoise / norm(Ynoise, "2")
Y_final = Ysize * Ynorm

# Quick sanity check of Y vs a_local
cbind(a_global1, Y_final) %>% as_tibble() %>% ggplot(aes(x=a_global1,y=Y_final)) + geom_point()
cbind(a_local1, Y_final) %>% as_tibble() %>% ggplot(aes(x=a_local1,y=Y_final)) + geom_point()

# Convert to Tensor
Y_final = as.tensor(Y_final)
```

# ACMTF
```{r ACMTF prepare Z}
datasets = list(X1_final, X2_final, X3_final)
modes = list(c(1,2,3), c(1,4,5), c(1,6,7))
Z = CMTFtoolbox::setupCMTFdata(datasets, modes, normalize=TRUE)
```

```{r run ACMTF}
model_ACMTF = acmtf_opt(Z, numComponents=7, beta=c(1e-3,1e-3,1e-3), abs_tol=1e-8, rel_tol=1e-8, nstart=1)
```

# ACMTF YAS

```{r ACMTF YAS prepare Z}
datasets_YAS = list(X1_final, X2_final, X3_final, as.matrix(Y_final@data))
modes_YAS = list(c(1,2,3), c(1,4,5), c(1,6,7), c(1,8))
Z_YAS = CMTFtoolbox::setupCMTFdata(datasets_YAS, modes_YAS, normalize=FALSE)
```

```{r run ACMTF YAS}
model_ACMTF_YAS = acmtf_opt(Z_YAS, numComponents=7, beta=c(1e-3,1e-3,1e-3), abs_tol=1e-6, rel_tol=1e-6, nstart=1)
```

# ACMTFR
```{r run ACMTFR}
model_ACMTFR = acmtfr_opt(Z, as.matrix(Y_final@data), numComponents=7, beta=c(1e-3,1e-3,1e-3), pi=0.9, abs_tol=1e-6, rel_tol=1e-6, nstart=1)
```

# Compare models with simulation

```{r ACMTF vs sim}
scores = cbind(a_global1, a_global2, a_local1, a_local2, a_distinct1, a_distinct2, a_distinct3)
cor(model_ACMTF$Fac[[1]], scores)
cor(model_ACMTF_YAS$Fac[[1]], scores)
cor(model_ACMTFR$Fac[[1]], scores)

selected_model_ACMTF = model_ACMTF
selected_model_ACMTF_YAS = model_ACMTF_YAS
selected_model_ACMTFR = model_ACMTFR

# ACMTF
a = cbind(selected_model_ACMTF$Fac[[1]][,2], a_global1) %>% as_tibble() %>% ggplot(aes(x=a_global1,y=V1)) + geom_point() + ggtitle("Common1") + xlab("Real scores") + ylab("ACMTF")
b = cbind(selected_model_ACMTF$Fac[[1]][,3], a_global2) %>% as_tibble() %>% ggplot(aes(x=a_global2,y=V1)) + geom_point() + ggtitle("Common2") + xlab("Real scores") + ylab("ACMTF")
c = cbind(selected_model_ACMTF$Fac[[1]][,1], a_local1) %>% as_tibble() %>% ggplot(aes(x=a_local1,y=V1)) + geom_point() + ggtitle("Local1") + xlab("Real scores") + ylab("ACMTF")
d = cbind(selected_model_ACMTF$Fac[[1]][,4], a_local2) %>% as_tibble() %>% ggplot(aes(x=a_local2,y=V1)) + geom_point() + ggtitle("Local2") + xlab("Real scores") + ylab("ACMTF")
e = cbind(selected_model_ACMTF$Fac[[1]][,7], a_distinct1) %>% as_tibble() %>% ggplot(aes(x=a_distinct1,y=V1)) + geom_point() + ggtitle("Distinct X1") + xlab("Real scores") + ylab("ACMTF")
f = cbind(selected_model_ACMTF$Fac[[1]][,6], a_distinct2) %>% as_tibble() %>% ggplot(aes(x=a_distinct2,y=V1)) + geom_point() + ggtitle("Distinct X2") + xlab("Real scores") + ylab("ACMTF")
g = cbind(selected_model_ACMTF$Fac[[1]][,5], a_distinct3) %>% as_tibble() %>% ggplot(aes(x=a_distinct3,y=V1)) + geom_point() + ggtitle("Distinct X3") + xlab("Real scores") + ylab("ACMTF")

# ACMTF YAS
h = cbind(selected_model_ACMTF_YAS$Fac[[1]][,2], a_global1) %>% as_tibble() %>% ggplot(aes(x=a_global1,y=V1)) + geom_point() + ggtitle("Common1") + xlab("Real scores") + ylab("ACMTF-YAS")
i = cbind(selected_model_ACMTF_YAS$Fac[[1]][,1], a_global2) %>% as_tibble() %>% ggplot(aes(x=a_global2,y=V1)) + geom_point() + ggtitle("Common2") + xlab("Real scores") + ylab("ACMTF-YAS")
j = cbind(selected_model_ACMTF_YAS$Fac[[1]][,3], a_local1) %>% as_tibble() %>% ggplot(aes(x=a_local1,y=V1)) + geom_point() + ggtitle("Local1") + xlab("Real scores") + ylab("ACMTF-YAS")
k = cbind(selected_model_ACMTF_YAS$Fac[[1]][,7], a_local2) %>% as_tibble() %>% ggplot(aes(x=a_local2,y=V1)) + geom_point() + ggtitle("Local2") + xlab("Real scores") + ylab("ACMTF-YAS")
l = cbind(selected_model_ACMTF_YAS$Fac[[1]][,5], a_distinct1) %>% as_tibble() %>% ggplot(aes(x=a_distinct1,y=V1)) + geom_point() + ggtitle("Distinct X1") + xlab("Real scores") + ylab("ACMTF-YAS")
m = cbind(selected_model_ACMTF_YAS$Fac[[1]][,6], a_distinct2) %>% as_tibble() %>% ggplot(aes(x=a_distinct2,y=V1)) + geom_point() + ggtitle("Distinct X2") + xlab("Real scores") + ylab("ACMTF-YAS")
n = cbind(selected_model_ACMTF_YAS$Fac[[1]][,4], a_distinct3) %>% as_tibble() %>% ggplot(aes(x=a_distinct3,y=V1)) + geom_point() + ggtitle("Distinct X3") + xlab("Real scores") + ylab("ACMTF-YAS")

# ACMTFR
o = cbind(selected_model_ACMTFR$Fac[[1]][,2], a_global1) %>% as_tibble() %>% ggplot(aes(x=a_global1,y=V1)) + geom_point() + ggtitle("Common1") + xlab("Real scores") + ylab("ACMTF-R")
p = cbind(selected_model_ACMTFR$Fac[[1]][,1], a_global2) %>% as_tibble() %>% ggplot(aes(x=a_global2,y=V1)) + geom_point() + ggtitle("Common2") + xlab("Real scores") + ylab("ACMTF-R")
q = cbind(selected_model_ACMTFR$Fac[[1]][,3], a_local1) %>% as_tibble() %>% ggplot(aes(x=a_local1,y=V1)) + geom_point() + ggtitle("Local1") + xlab("Real scores") + ylab("ACMTFR")
r = cbind(selected_model_ACMTFR$Fac[[1]][,7], a_local2) %>% as_tibble() %>% ggplot(aes(x=a_local2,y=V1)) + geom_point() + ggtitle("Local2") + xlab("Real scores") + ylab("ACMTF-R")
s = cbind(selected_model_ACMTFR$Fac[[1]][,5], a_distinct1) %>% as_tibble() %>% ggplot(aes(x=a_distinct1,y=V1)) + geom_point() + ggtitle("Distinct X1") + xlab("Real scores") + ylab("ACMTF-R")
t = cbind(selected_model_ACMTFR$Fac[[1]][,6], a_distinct2) %>% as_tibble() %>% ggplot(aes(x=a_distinct2,y=V1)) + geom_point() + ggtitle("Distinct X2") + xlab("Real scores") + ylab("ACMTF-R")
u = cbind(selected_model_ACMTFR$Fac[[1]][,4], a_distinct3) %>% as_tibble() %>% ggplot(aes(x=a_distinct3,y=V1)) + geom_point() + ggtitle("Distinct X3") + xlab("Real scores") + ylab("ACMTF-R")

# Combined plot
ggarrange(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u, nrow=3, ncol=7)
```
