---
title: "20241203_ACMTF_validation"
author: "G.R. van der Ploeg"
date: "2024-12-03"
output: html_document
---

# Preamble
```{r setup, include=FALSE}
library(rTensor)
library(CMTFtoolbox)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(scales)
library(clue)
```

```{r define FMS}

calculateFMS <- function(modelFac, realFac, numComponents) {
  
  # Project modelFac onto realFac to make sure components are not split
  # modelFac = modelFac %*% pracma::pinv(t(modelFac) %*% modelFac) %*% t(modelFac) %*% realFac
  
  # Create a similarity matrix for the pairwise comparison
  similarity_matrix <- matrix(0, nrow = ncol(modelFac), ncol = ncol(modelFac))
  
  # Compute pairwise cosine similarity across all modes
  for (k in 1:ncol(modelFac)) {
    for (l in 1:ncol(realFac)) {
      vect1 <- as.matrix(modelFac[, k])
      vect2 <- as.matrix(realFac[, l])
      
      # Cosine similarity
      similarity_matrix[k, l] <- abs(t(vect1) %*% vect2) / (norm(vect1, "F") * norm(vect2, "F"))
    }
  }
  
  # Use Hungarian algorithm to find the best matching
  assignment <- clue::solve_LSAP(similarity_matrix, maximum = TRUE)
  
  # Permute columns in the model to fit the input components
  # modelFac_perm <- modelFac[,assignment]
  
  # Calculate FMS based on the best matching
  FMS <- sum(similarity_matrix[cbind(seq_along(assignment), assignment)])
  
  # Average over the number of components
  FMS <- FMS / numComponents
  return(FMS)
}

```

```{r lambda similarity function}


lambda_similarity = function(lambda_hat, lambda_true=matrix(c(1,1,1,1,1,1,1,1,0,1,1,0,1,0,0,0,1,0,0,0,1), nrow=3, ncol=7)){
  lambda_hat = abs(lambda_hat)
  numComponents = ncol(lambda_true)
  
  similarity_matrix = matrix(NA, nrow=numComponents, ncol=numComponents)
  for(i in 1:numComponents){
    for(j in 1:numComponents){
      real = lambda_true[,i]
      hat = lambda_hat[,j]
      similarity_matrix[i,j] = sum((real - hat)^2)
    }
  }
  
  mapping = clue::solve_LSAP(similarity_matrix)
  lambda_hat_perm = lambda_hat[,mapping]
  SSR = sum((lambda_true - lambda_hat_perm)^2)
  return(SSR)
}
```

```{r load input loadings}
inputLoadings = readRDS("./Sim3_input_loadings_Y_outside.RDS")

# Reorganize into Fac object
inputLoadingsFac = inputLoadings
inputLoadingsFac[[2]] = inputLoadings[[2]][,c(1,4,7,9,11)]
inputLoadingsFac[[3]] = inputLoadings[[3]][,c(1,4,7,9,11)]
inputLoadingsFac[[4]] = inputLoadings[[2]][,c(2,5,8,10,12)]
inputLoadingsFac[[5]] = inputLoadings[[3]][,c(2,5,8,10,12)]
inputLoadingsFac[[6]] = inputLoadings[[2]][,c(3,6,13)]
inputLoadingsFac[[7]] = inputLoadings[[3]][,c(3,6,13)]

```

```{r load datasets}
X1_final = readRDS("./Sim3_X1_Y_outside.RDS")
X2_final = readRDS("./Sim3_X2_Y_outside.RDS")
X3_final = readRDS("./Sim3_X3_Y_outside.RDS")
Y_final = readRDS("./Sim3_Y_Y_outside.RDS")
```

# Analyze ACMTF results 7 components
```{r load ACMTF models}
ACMTFR_CV_models = readRDS("./Sim3_ACMTFR_CV_Y_outside.RDS")
ACMTFR_CV_params = readRDS("./Sim3_ACMTFR_CV_params_Y_outside.RDS")
```

# ACMTFR
```{r plot varExps for ACMTFR}
ACMTFR_CV_varExpX = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){(x$varExp)}))
ACMTFR_CV_varExpY = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){x$varExpY}))
ACMTFR_CV_varExps = cbind(ACMTFR_CV_varExpX, ACMTFR_CV_varExpY)
colnames(ACMTFR_CV_varExps) = c("X1", "X2", "X3", "Y")
ACMTFR_CV_varExps = ACMTFR_CV_varExps %>% as_tibble() %>% mutate(index=1:nrow(.), beta=ACMTFR_CV_params[,1], pi = ACMTFR_CV_params[,2])

ACMTFR_CV_f = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){x$f}))
ACMTFR_CV_f = ACMTFR_CV_f %>% as_tibble() %>% mutate(index=1:nrow(.), beta=ACMTFR_CV_params[,1], pi = ACMTFR_CV_params[,2])

ACMTFR_CV_FMS1 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[1]], inputLoadingsFac[[1]], numComponents=7)})) %>% as_tibble()
ACMTFR_CV_FMS2 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[2]], inputLoadingsFac[[2]], numComponents=5)})) %>% as_tibble()
ACMTFR_CV_FMS3 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[3]], inputLoadingsFac[[3]], numComponents=5)})) %>% as_tibble()
ACMTFR_CV_FMS4 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[4]], inputLoadingsFac[[4]], numComponents=5)})) %>% as_tibble()
ACMTFR_CV_FMS5 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[5]], inputLoadingsFac[[5]], numComponents=5)})) %>% as_tibble()
ACMTFR_CV_FMS6 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[6]], inputLoadingsFac[[6]], numComponents=3)})) %>% as_tibble()
ACMTFR_CV_FMS7 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[7]], inputLoadingsFac[[7]], numComponents=3)})) %>% as_tibble()

ACMTFR_FMS = cbind(ACMTFR_CV_FMS1, ACMTFR_CV_FMS2, ACMTFR_CV_FMS3, ACMTFR_CV_FMS4, ACMTFR_CV_FMS5, ACMTFR_CV_FMS6, ACMTFR_CV_FMS7)
colnames(ACMTFR_FMS) = c("FMS1", "FMS2", "FMS3", "FMS4", "FMS5", "FMS6", "FMS7")
ACMTFR_FMS = ACMTFR_FMS %>% as_tibble() %>% mutate(X1 = FMS1 * FMS2 * FMS3, X2 = FMS1 * FMS4 * FMS5, X3 = FMS1 * FMS6 * FMS7, beta=ACMTFR_CV_params[,1],pi = ACMTFR_CV_params[,2], index=1:length(pi))

ACMTFR_CV_lambda_similarity = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){lambda_similarity(x$Fac[[8]])}))
ACMTFR_CV_lambda_similarity = ACMTFR_CV_lambda_similarity %>% as_tibble() %>% mutate(index=1:nrow(.), beta=ACMTFR_CV_params[,1], pi = ACMTFR_CV_params[,2])

# Plots
ACMTFR_CV_varExps %>% filter(pi!=0) %>% select(-index) %>% pivot_longer(-c(beta,pi)) %>% ggplot(aes(x=as.factor(beta),y=value)) + facet_grid(vars(name),vars(pi)) + geom_boxplot() + xlab("Beta") + ylab("Variance explained (%)")

ACMTFR_CV_f %>% select(-index) %>% ggplot(aes(x=as.factor(beta),y=V1)) + facet_wrap(~pi) + geom_boxplot() + xlab("Beta") + ylab("Loss")

ACMTFR_FMS %>% select(X1,X2,X3,beta,pi) %>% pivot_longer(-c(beta,pi)) %>% ggplot(aes(x=as.factor(beta),y=value)) + facet_grid(vars(name),vars(pi)) + geom_boxplot() + xlab("Beta") + ylab("FMS")

ACMTFR_CV_lambda_similarity %>% ggplot(aes(x=as.factor(beta),y=V1)) + facet_wrap(~pi) + geom_boxplot() + xlab("Beta") + ylab("Lambda similarity") + scale_y_log10()

a=ACMTFR_FMS %>% mutate(lambda_similarity = ACMTFR_CV_lambda_similarity$V1) %>% filter(pi!=0,beta<0.5) %>% select(X1,beta,pi,lambda_similarity) %>% ggplot(aes(x=lambda_similarity,y=X1)) + facet_grid(vars(beta),vars(pi)) + geom_point() + xlab("Lambda similarity") + ylab("FMS") + ggtitle("X1") + scale_x_log10()
b=ACMTFR_FMS %>% mutate(lambda_similarity = ACMTFR_CV_lambda_similarity$V1) %>% filter(pi!=0,beta<0.5) %>% select(X2,beta,pi,lambda_similarity) %>% ggplot(aes(x=lambda_similarity,y=X2)) + facet_grid(vars(beta),vars(pi)) + geom_point() + xlab("Lambda similarity") + ylab("FMS") + ggtitle("X2") + scale_x_log10()
c=ACMTFR_FMS %>% mutate(lambda_similarity = ACMTFR_CV_lambda_similarity$V1) %>% filter(pi!=0,beta<0.5) %>% select(X3,beta,pi,lambda_similarity) %>% ggplot(aes(x=lambda_similarity,y=X3)) + facet_grid(vars(beta),vars(pi)) + geom_point() + xlab("Lambda similarity") + ylab("FMS") + ggtitle("X3") + scale_x_log10()
ggarrange(a,b,c,nrow=1)

ACMTFR_FMS %>% mutate(lambda_similarity = ACMTFR_CV_lambda_similarity$V1) %>% filter(pi!=0,beta<0.5) %>% select(X1,X2,X3,beta,pi,lambda_similarity) %>% mutate(correct = (lambda_similarity<=1) & (X1>=0.9) & (X2>=0.9) & (X3>=0.9)) %>% select(-X1,-X2,-X3,-lambda_similarity) %>% group_by(beta,pi) %>% summarize(fraction = sum(correct)/100) %>% ungroup() %>% ggplot(aes(x=as.factor(beta),y=as.factor(pi),fill=fraction)) + geom_tile(col="black") + labs(x="Beta",y="Pi",fill="Fraction correct")
```

```{r how often are the components found}
threshold = 0.95
colours = hue_pal()(4)

Yreal = readRDS("./Sim3_Y_Y_outside.RDS")
Yreal = Yreal@data
Yreal = as.matrix(Yreal)

global1 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,1])))}))
global2 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,2])))}))
local1 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,3])))}))
local2 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,4])))}))
distinct1 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,5])))}))
distinct2 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,6])))}))
distinct3 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,7])))}))
y_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){abs(cor(x$Yhat, Yreal))}))

componentShapes = cbind(ACMTFR_FMS, global1, global2, local1, local2, distinct1, distinct2, distinct3, y_found)

componentShapes %>% as_tibble() %>% select(beta, pi, global1, global2, local1, local2, distinct1, distinct2, distinct3, y_found) %>% pivot_longer(-c(beta,pi)) %>% mutate(Found = value > threshold) %>% ggplot(aes(x=as.factor(beta),fill=Found)) + facet_grid(vars(name),vars(pi)) + geom_bar()

componentShapes %>% as_tibble() %>% mutate(global1 = global1 < threshold, global2 = global2 < threshold, local1 = local1 < threshold, local2 = local2 < threshold, distinct1 = distinct1 < threshold, distinct2 = distinct2 < threshold, distinct3 = distinct3 < threshold, y_found = y_found < threshold) %>% mutate(Global = global1 + global2, Local = local1 + local2, Distinct = distinct1 + distinct2 + distinct3, Y = y_found) %>% select(beta, pi, Global, Local, Distinct, Y) %>% pivot_longer(-c(beta,pi)) %>% mutate(name = factor(name, levels=c("Global", "Local", "Distinct", "Y"))) %>% ggplot(aes(x=as.factor(beta),fill=as.factor(value))) + facet_grid(vars(pi), vars(name)) + geom_bar(col="black") + labs(x="Beta",y="Number of models",fill="Number of components lost")
```


```{r comparison of some models}
modelA = ACMTFR_CV_models[[13]] # pi 0.0
modelB = ACMTFR_CV_models[[14]] # pi 0.2
modelC = ACMTFR_CV_models[[15]] # pi 0.4
modelD = ACMTFR_CV_models[[70]] # pi 0.6
modelE = ACMTFR_CV_models[[17]] # pi 0.8
modelF = ACMTFR_CV_models[[18]] # pi 1.0

# Y
df = cbind(modelA$Yhat, modelB$Yhat, modelC$Yhat, modelD$Yhat, modelE$Yhat, modelF$Yhat, Yreal) %>% as_tibble()
colnames(df) = c("0.0", "0.2", "0.4", "0.6", "0.8", "1.0", "true")
df %>% pivot_longer(-true) %>% ggplot(aes(x=true,y=value,col=as.factor(name))) + geom_point() + xlab("Y") + ylab("Yhat") + labs(color="Pi")

# Test
y_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){(sum(x$Yhat * Yreal) / (norm(x$Yhat, "2") * norm(Yreal, "2")))}))
y_found = cbind(ACMTFR_CV_params, y_found) %>% as_tibble()
colnames(y_found) = c("beta", "pi", "cosine")
y_found %>% filter(beta==1e-3) %>% ggplot(aes(x=as.factor(pi),y=cosine)) + geom_boxplot() + stat_compare_means()
```

```{r test real difference}
# cosineOnly = function(Test, Ttrue){
#   bestMatch = which(abs(cor(Test, Ttrue)) == max(abs(cor(Test,Ttrue))))
#   Test = Test[,bestMatch]
#   similarity = abs(sum(Test * Ttrue)) / (norm(Test, "2") * norm(Ttrue, "2"))
#   return(similarity)
# }
# 
# global1_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,1])}))
# global2_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,2])}))
# local1_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,3])}))
# local2_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,4])}))
# distinct1_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,5])}))
# distinct2_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,6])}))
# distinct3_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,7])}))
# y_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){abs(sum(x$Yhat * Yreal) / (norm(x$Yhat, "2") * norm(Yreal, "2")))}))
# 
# df = cbind(ACMTFR_FMS, global1_found, global2_found, local1_found, local2_found, distinct1_found, distinct2_found, distinct3_found, y_found) %>% as_tibble()
# df %>% select(-FMS,-index) %>% pivot_longer(-c(beta,pi)) %>% ggplot(aes(x=as.factor(beta),y=value)) + facet_grid(vars(name),vars(pi)) + geom_boxplot()
```

# Analyze ACMTF results 8 components

```{r load ACMTF models}
ACMTFR_CV_models_8comp = readRDS("./Sim3_ACMTFR_CV_Y_outside_8comp.RDS")
ACMTFR_CV_params_8comp = readRDS("./Sim3_ACMTFR_CV_params_Y_outside_8comp.RDS")
```

# ACMTFR
```{r plot varExps for ACMTFR}
lambda_true_8comp = matrix(c(1,1,1,1,1,1,1,1,0,1,1,0,1,0,0,0,1,0,0,0,1,0,0,1), nrow=3, ncol=8)

ACMTFR_CV_varExpX_8comp = do.call(rbind, lapply(ACMTFR_CV_models_8comp, FUN=function(x){(x$varExp)}))
ACMTFR_CV_varExpY_8comp = do.call(rbind, lapply(ACMTFR_CV_models_8comp, FUN=function(x){x$varExpY}))
ACMTFR_CV_varExps_8comp = cbind(ACMTFR_CV_varExpX_8comp, ACMTFR_CV_varExpY_8comp)
colnames(ACMTFR_CV_varExps_8comp) = c("X1", "X2", "X3", "Y")
ACMTFR_CV_varExps_8comp = ACMTFR_CV_varExps_8comp %>% as_tibble() %>% mutate(index=1:nrow(.), beta=ACMTFR_CV_params_8comp[,1], pi = ACMTFR_CV_params_8comp[,2])

ACMTFR_CV_f_8comp = do.call(rbind, lapply(ACMTFR_CV_models_8comp, FUN=function(x){x$f}))
ACMTFR_CV_f_8comp = ACMTFR_CV_f %>% as_tibble() %>% mutate(index=1:nrow(.), beta=ACMTFR_CV_params_8comp[,1], pi = ACMTFR_CV_params_8comp[,2])

ACMTFR_CV_FMS1_8comp = do.call(rbind, lapply(ACMTFR_CV_models_8comp, FUN=function(x){calculateFMS(x$Fac[[1]], inputLoadingsFac[[1]], numComponents=7)})) %>% as_tibble()
ACMTFR_CV_FMS2_8comp = do.call(rbind, lapply(ACMTFR_CV_models_8comp, FUN=function(x){calculateFMS(x$Fac[[2]], inputLoadingsFac[[2]], numComponents=5)})) %>% as_tibble()
ACMTFR_CV_FMS3_8comp = do.call(rbind, lapply(ACMTFR_CV_models_8comp, FUN=function(x){calculateFMS(x$Fac[[3]], inputLoadingsFac[[3]], numComponents=5)})) %>% as_tibble()
ACMTFR_CV_FMS4_8comp = do.call(rbind, lapply(ACMTFR_CV_models_8comp, FUN=function(x){calculateFMS(x$Fac[[4]], inputLoadingsFac[[4]], numComponents=5)})) %>% as_tibble()
ACMTFR_CV_FMS5_8comp = do.call(rbind, lapply(ACMTFR_CV_models_8comp, FUN=function(x){calculateFMS(x$Fac[[5]], inputLoadingsFac[[5]], numComponents=5)})) %>% as_tibble()
ACMTFR_CV_FMS6_8comp = do.call(rbind, lapply(ACMTFR_CV_models_8comp, FUN=function(x){calculateFMS(x$Fac[[6]], inputLoadingsFac[[6]], numComponents=3)})) %>% as_tibble()
ACMTFR_CV_FMS7_8comp = do.call(rbind, lapply(ACMTFR_CV_models_8comp, FUN=function(x){calculateFMS(x$Fac[[7]], inputLoadingsFac[[7]], numComponents=3)})) %>% as_tibble()

ACMTFR_FMS_8comp = cbind(ACMTFR_CV_FMS1_8comp, ACMTFR_CV_FMS2_8comp, ACMTFR_CV_FMS3_8comp, ACMTFR_CV_FMS4_8comp, ACMTFR_CV_FMS5_8comp, ACMTFR_CV_FMS6_8comp, ACMTFR_CV_FMS7_8comp)
colnames(ACMTFR_FMS_8comp) = c("FMS1", "FMS2", "FMS3", "FMS4", "FMS5", "FMS6", "FMS7")
ACMTFR_FMS_8comp = ACMTFR_FMS_8comp %>% as_tibble() %>% mutate(X1 = FMS1 * FMS2 * FMS3, X2 = FMS1 * FMS4 * FMS5, X3 = FMS1 * FMS6 * FMS7, beta=ACMTFR_CV_params_8comp[,1],pi = ACMTFR_CV_params_8comp[,2], index=1:length(pi))

ACMTFR_CV_lambda_similarity_8comp = do.call(rbind, lapply(ACMTFR_CV_models_8comp, FUN=function(x){lambda_similarity(x$Fac[[8]], lambda_true=lambda_true_8comp)}))
ACMTFR_CV_lambda_similarity_8comp = ACMTFR_CV_lambda_similarity_8comp %>% as_tibble() %>% mutate(index=1:nrow(.), beta=ACMTFR_CV_params_8comp[,1], pi = ACMTFR_CV_params_8comp[,2])

# Plots
ACMTFR_CV_varExps_8comp %>% filter(pi!=0) %>% select(-index) %>% pivot_longer(-c(beta,pi)) %>% ggplot(aes(x=as.factor(beta),y=value)) + facet_grid(vars(name),vars(pi)) + geom_boxplot() + xlab("Beta") + ylab("Variance explained (%)")

ACMTFR_CV_f_8comp %>% select(-index) %>% ggplot(aes(x=as.factor(beta),y=V1)) + facet_wrap(~pi) + geom_boxplot() + xlab("Beta") + ylab("Loss")

ACMTFR_FMS_8comp %>% select(X1,X2,X3,beta,pi) %>% pivot_longer(-c(beta,pi)) %>% ggplot(aes(x=as.factor(beta),y=value)) + facet_grid(vars(name),vars(pi)) + geom_boxplot() + xlab("Beta") + ylab("FMS")

ACMTFR_CV_lambda_similarity_8comp %>% ggplot(aes(x=as.factor(beta),y=V1)) + facet_wrap(~pi) + geom_boxplot() + xlab("Beta") + ylab("Lambda similarity") + scale_y_log10()

a=ACMTFR_FMS_8comp %>% mutate(lambda_similarity = ACMTFR_CV_lambda_similarity_8comp$V1) %>% filter(pi!=0,beta<0.5) %>% select(X1,beta,pi,lambda_similarity) %>% ggplot(aes(x=lambda_similarity,y=X1)) + facet_grid(vars(beta),vars(pi)) + geom_point() + xlab("Lambda similarity") + ylab("FMS") + ggtitle("X1") + scale_x_log10()
b=ACMTFR_FMS_8comp %>% mutate(lambda_similarity = ACMTFR_CV_lambda_similarity_8comp$V1) %>% filter(pi!=0,beta<0.5) %>% select(X2,beta,pi,lambda_similarity) %>% ggplot(aes(x=lambda_similarity,y=X2)) + facet_grid(vars(beta),vars(pi)) + geom_point() + xlab("Lambda similarity") + ylab("FMS") + ggtitle("X2") + scale_x_log10()
c=ACMTFR_FMS_8comp %>% mutate(lambda_similarity = ACMTFR_CV_lambda_similarity_8comp$V1) %>% filter(pi!=0,beta<0.5) %>% select(X3,beta,pi,lambda_similarity) %>% ggplot(aes(x=lambda_similarity,y=X3)) + facet_grid(vars(beta),vars(pi)) + geom_point() + xlab("Lambda similarity") + ylab("FMS") + ggtitle("X3") + scale_x_log10()
ggarrange(a,b,c,nrow=1)

ACMTFR_FMS_8comp %>% mutate(lambda_similarity = ACMTFR_CV_lambda_similarity_8comp$V1) %>% filter(pi!=0,beta<0.5) %>% select(X1,X2,X3,beta,pi,lambda_similarity) %>% mutate(correct = (lambda_similarity<=1) & (X1>=0.9) & (X2>=0.9) & (X3>=0.9)) %>% select(-X1,-X2,-X3,-lambda_similarity) %>% group_by(beta,pi) %>% summarize(fraction = sum(correct)/100) %>% ungroup() %>% ggplot(aes(x=as.factor(beta),y=as.factor(pi),fill=fraction)) + geom_tile(col="black") + labs(x="Beta",y="Pi",fill="Fraction correct")
```

```{r how often are the components found}
threshold = 0.95
colours = hue_pal()(4)

Yreal = readRDS("./Sim3_Y_Y_outside.RDS")
Yreal = Yreal@data
Yreal = as.matrix(Yreal)

global1 = unlist(lapply(ACMTFR_CV_models_8comp, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,1])))}))
global2 = unlist(lapply(ACMTFR_CV_models_8comp, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,2])))}))
local1 = unlist(lapply(ACMTFR_CV_models_8comp, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,3])))}))
local2 = unlist(lapply(ACMTFR_CV_models_8comp, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,4])))}))
distinct1 = unlist(lapply(ACMTFR_CV_models_8comp, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,5])))}))
distinct2 = unlist(lapply(ACMTFR_CV_models_8comp, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,6])))}))
distinct3 = unlist(lapply(ACMTFR_CV_models_8comp, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,7])))}))
y_found = unlist(lapply(ACMTFR_CV_models_8comp, FUN=function(x){abs(cor(x$Yhat, Yreal))}))

componentShapes = cbind(ACMTFR_FMS_8comp, global1, global2, local1, local2, distinct1, distinct2, distinct3, y_found)

componentShapes %>% as_tibble() %>% select(beta, pi, global1, global2, local1, local2, distinct1, distinct2, distinct3, y_found) %>% pivot_longer(-c(beta,pi)) %>% mutate(Found = value > threshold) %>% ggplot(aes(x=as.factor(beta),fill=Found)) + facet_grid(vars(name),vars(pi)) + geom_bar()

componentShapes %>% as_tibble() %>% mutate(global1 = global1 < threshold, global2 = global2 < threshold, local1 = local1 < threshold, local2 = local2 < threshold, distinct1 = distinct1 < threshold, distinct2 = distinct2 < threshold, distinct3 = distinct3 < threshold, y_found = y_found < threshold) %>% mutate(Global = global1 + global2, Local = local1 + local2, Distinct = distinct1 + distinct2 + distinct3, Y = y_found) %>% select(beta, pi, Global, Local, Distinct, Y) %>% pivot_longer(-c(beta,pi)) %>% mutate(name = factor(name, levels=c("Global", "Local", "Distinct", "Y"))) %>% ggplot(aes(x=as.factor(beta),fill=as.factor(value))) + facet_grid(vars(pi), vars(name)) + geom_bar(col="black") + labs(x="Beta",y="Number of models",fill="Number of components lost")
```


```{r comparison of some models}
modelA = ACMTFR_CV_models[[13]] # pi 0.0
modelB = ACMTFR_CV_models[[14]] # pi 0.2
modelC = ACMTFR_CV_models[[15]] # pi 0.4
modelD = ACMTFR_CV_models[[70]] # pi 0.6
modelE = ACMTFR_CV_models[[17]] # pi 0.8
modelF = ACMTFR_CV_models[[18]] # pi 1.0

# Y
df = cbind(modelA$Yhat, modelB$Yhat, modelC$Yhat, modelD$Yhat, modelE$Yhat, modelF$Yhat, Yreal) %>% as_tibble()
colnames(df) = c("0.0", "0.2", "0.4", "0.6", "0.8", "1.0", "true")
df %>% pivot_longer(-true) %>% ggplot(aes(x=true,y=value,col=as.factor(name))) + geom_point() + xlab("Y") + ylab("Yhat") + labs(color="Pi")

# Test
y_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){(sum(x$Yhat * Yreal) / (norm(x$Yhat, "2") * norm(Yreal, "2")))}))
y_found = cbind(ACMTFR_CV_params, y_found) %>% as_tibble()
colnames(y_found) = c("beta", "pi", "cosine")
y_found %>% filter(beta==1e-3) %>% ggplot(aes(x=as.factor(pi),y=cosine)) + geom_boxplot() + stat_compare_means()
```

```{r test real difference}
cosineOnly = function(Test, Ttrue){
  bestMatch = which(abs(cor(Test, Ttrue)) == max(abs(cor(Test,Ttrue))))
  Test = Test[,bestMatch]
  similarity = abs(sum(Test * Ttrue)) / (norm(Test, "2") * norm(Ttrue, "2"))
  return(similarity)
}

global1_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,1])}))
global2_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,2])}))
local1_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,3])}))
local2_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,4])}))
distinct1_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,5])}))
distinct2_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,6])}))
distinct3_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,7])}))
y_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){abs(sum(x$Yhat * Yreal) / (norm(x$Yhat, "2") * norm(Yreal, "2")))}))

df = cbind(ACMTFR_FMS, global1_found, global2_found, local1_found, local2_found, distinct1_found, distinct2_found, distinct3_found, y_found) %>% as_tibble()
df %>% select(-FMS,-index) %>% pivot_longer(-c(beta,pi)) %>% ggplot(aes(x=as.factor(beta),y=value)) + facet_grid(vars(name),vars(pi)) + geom_boxplot()
```
