---
title: "The effect of the embedding of Y"
output: html_document
date: "2025-01-26"
---

# Preamble
```{r setup, include=FALSE}
library(rTensor)
library(CMTFtoolbox)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(scales)
library(clue)
```

```{r model evaluation function}
modelEvaluation = function(modelFac, realFac, lambda_hat, lambda_true=matrix(c(1,1,1,1,1,1,1,1,0,1,1,0,1,0,0,0,1,0,0,0,1),nrow=3,ncol=7)){
  
  # FMS
  FMS1 = calculateFMS(modelFac[[1]], realFac[[1]])
  FMS2 = calculateFMS(modelFac[[2]], realFac[[2]])
  FMS3 = calculateFMS(modelFac[[3]], realFac[[3]])
  FMS4 = calculateFMS(modelFac[[4]], realFac[[4]])
  FMS5 = calculateFMS(modelFac[[5]], realFac[[5]])
  FMS6 = calculateFMS(modelFac[[6]], realFac[[6]])
  FMS7 = calculateFMS(modelFac[[7]], realFac[[7]])
  
  # Repair the distinct components to appear in the correct column
  FMS2 = cbind(FMS2, matrix(rnorm(7*2), nrow=7, ncol=2))
  FMS3 = cbind(FMS3, matrix(rnorm(7*2), nrow=7, ncol=2))
  FMS4 = cbind(FMS4[,1:4], rnorm(7), FMS4[,5], rnorm(7))
  FMS5 = cbind(FMS5[,1:4], rnorm(7), FMS5[,5], rnorm(7))
  FMS6 = cbind(FMS6[,1:2], matrix(rnorm(7*4), nrow=7, ncol=4), FMS6[,3])
  FMS7 = cbind(FMS7[,1:2], matrix(rnorm(7*4), nrow=7, ncol=4), FMS7[,3])
  
  # LSI
  lambda_hat = abs(lambda_hat)
  LSI = calculateLSI(lambda_hat, lambda_true)
  
  # Combine similarity matrices equally
  similarityMatrix = (FMS1 + LSI)/2
  
  # Find best combination
  mapping = clue::solve_LSAP(similarityMatrix, maximum=TRUE)
  
  # Return metrics
  mappingMatrix = cbind(seq_along(mapping), mapping)
  
  mappingMatrix1 = mappingMatrix[mappingMatrix[,2] %in% c(1,2,3,4,5),]
  mappingMatrix2 = mappingMatrix[mappingMatrix[,2] %in% c(1,2,3,4,6),]
  mappingMatrix3 = mappingMatrix[mappingMatrix[,2] %in% c(1,2,7),]

  FMS1 = (sum(FMS1[mappingMatrix])) / 7
  FMS2 = (sum(FMS2[mappingMatrix1])) / 5
  FMS3 = (sum(FMS3[mappingMatrix1])) / 5
  FMS4 = (sum(FMS4[mappingMatrix2])) / 5
  FMS5 = (sum(FMS5[mappingMatrix2])) / 5
  FMS6 = (sum(FMS6[mappingMatrix3])) / 3
  FMS7 = (sum(FMS7[mappingMatrix3])) / 3

  FMS_overall = FMS1 * FMS2 * FMS3 * FMS4 * FMS5 * FMS6 * FMS7
  
  lambda_hat_perm = lambda_hat[,mapping]
  SSR = sum((lambda_true - lambda_hat_perm)^2)
  LSI = 1 / (1 + SSR)
  
  result = list("FMS"=FMS_overall,
                "FMS1"=FMS1,
                "FMS2"=FMS2,
                "FMS3"=FMS3,
                "FMS4"=FMS4,
                "FMS5"=FMS5,
                "FMS6"=FMS6,
                "FMS7"=FMS7,
                "LSI"=LSI)
  return(result)
}

calculateFMS = function(modelFac, realFac){
  
  similarityMatrix = matrix(0, nrow = ncol(modelFac), ncol = ncol(realFac))
  
  for (k in 1:ncol(modelFac)) {
    for (l in 1:ncol(realFac)) {
      vect1 = as.matrix(modelFac[, k])
      vect2 = as.matrix(realFac[, l])
      
      # Cosine similarity
      similarityMatrix[k, l] = abs(t(vect1) %*% vect2) / (norm(vect1, "F") * norm(vect2, "F"))
    }
  }
  
  return(similarityMatrix)
}

calculateLSI = function(lambda_hat, lambda_true){

  similarityMatrix = matrix(NA, nrow=7, ncol=7)
  
  for(k in 1:7){
    for(l in 1:7){
      real = lambda_true[,k]
      hat = lambda_hat[,l]
      similarityMatrix[k,l] = 1 / (1 + sum((real - hat)^2))
    }
  }
  
  return(similarityMatrix)
}
```

```{r load input loadings}
inputLoadings = readRDS("./Sim2b_input_loadings_Y_inside.RDS")

# Reorganize into Fac object
inputLoadingsFac = inputLoadings
inputLoadingsFac[[2]] = inputLoadings[[2]][,c(1,4,7,9,11)]
inputLoadingsFac[[3]] = inputLoadings[[3]][,c(1,4,7,9,11)]
inputLoadingsFac[[4]] = inputLoadings[[2]][,c(2,5,8,10,12)]
inputLoadingsFac[[5]] = inputLoadings[[3]][,c(2,5,8,10,12)]
inputLoadingsFac[[6]] = inputLoadings[[2]][,c(3,6,13)]
inputLoadingsFac[[7]] = inputLoadings[[3]][,c(3,6,13)]

```

```{r load datasets}
X1_final = readRDS("./Sim2b_X1_Y_inside.RDS")
X2_final = readRDS("./Sim2b_X2_Y_inside.RDS")
X3_final = readRDS("./Sim2b_X3_Y_inside.RDS")
# Y_final = readRDS("./Sim2_Y_Y_inside.RDS") # This is different every time
```

# Analyze ACMTFR results
```{r load ACMTF models}
ACMTFR_CV_models = readRDS("./Sim2b_ACMTFR_CV_Y_inside.RDS")
# ACMTFR_CV_params = readRDS("./Sim2b_ACMTFR_CV_params_Y_inside.RDS") # NOT SAVED PROPERLY

noises = seq(0, 1, length.out=11)
pis = c(0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 1.0)
simSettings = cbind(rep(noises, each=13), rep(pis, 11))
simSettings = do.call(rbind, replicate(100, simSettings, simplify=FALSE))
ACMTFR_CV_params = simSettings
```

```{r briefly check convergence reason}
what = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){x$terminate$what}))

df = cbind(what, ACMTFR_CV_params) %>% as_tibble()
colnames(df) = c("what", "embedding", "pi")

df %>%
  as_tibble() %>%
  filter(embedding==0.5) %>%
  select(-embedding) %>%
  ggplot(aes(x=as.factor(pi),fill=as.factor(what))) +
  geom_bar(col="black") +
  xlab(expression(pi)) +
  ylab("Number of models") +
  scale_fill_manual(name="Reason", labels=c("Absolute loss value", "Maximum number of function evaluations", "Relative change in loss value", "Absolute change in parameter update"), values=hue_pal()(4)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

# ACMTFR
```{r plot varExps}
ACMTF_CV_varExpsX = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){x$varExp})) %>% as_tibble()
ACMTF_CV_varExpsY = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){(x$varExpY)})) %>% as_tibble()
colnames(ACMTF_CV_varExpsX) = c("X1", "X2", "X3")
ACMTF_CV_varExpsX = ACMTF_CV_varExpsX %>% mutate(pi = ACMTFR_CV_params[,2], embedding = ACMTFR_CV_params[,1])
ACMTF_CV_varExps = ACMTF_CV_varExpsX %>% as_tibble() %>% mutate(Y=ACMTF_CV_varExpsY$V1)

ACMTF_CV_varExps %>% filter(pi>0) %>% pivot_longer(-c(pi,embedding)) %>% ggplot(aes(x=as.factor(pi),y=value)) + facet_grid(vars(name),vars(embedding)) + geom_boxplot() + xlab("Pi") + ylab("Variance explained (%)") + ylim(0,100)

ACMTF_CV_varExps %>% filter(pi==1) %>% select(embedding, Y) %>% ggplot(aes(x=as.factor(embedding),y=Y)) + geom_boxplot() + xlab("Noise on Y") + ylab("Variance explained (%)") + ggtitle("Pi=1")

ACMTF_CV_varExps %>% filter(embedding==0.8) %>% select(pi, Y) %>% ggplot(aes(x=as.factor(pi),y=Y)) + geom_boxplot() + xlab("Pi") + ylab("Variance explained (%)") + ggtitle("Noise on Y = 80%")

ACMTF_CV_varExps %>% filter(embedding==0.8) %>% select(pi, X1, X2, X3) %>% pivot_longer(-pi) %>% ggplot(aes(x=as.factor(pi),y=value)) + facet_wrap(~name, nrow=3) + geom_boxplot() + xlab("Pi") + ylab("Variance explained (%)") + ggtitle("Noise on Y = 80%") + ylim(0,100)

ACMTF_CV_varExps %>%
  filter(embedding==0.5) %>%
  select(-embedding) %>%
  pivot_longer(-pi) %>%
  ggplot(aes(x=as.factor(pi),y=value)) +
  facet_wrap(~name, ncol=4) +
  geom_violin(scale="width") +
  geom_jitter(width=0.05, size=0.5) +
  stat_summary(fun = median, geom = "point", color = "red", size = 2) +
  xlab(expression(pi)) +
  ylab("Variance explained (%)") +
  ylim(0,100) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```
```{r calculate model metrics}
result = lapply(ACMTFR_CV_models, FUN = function(x) {modelEvaluation(x$Fac, inputLoadingsFac, x$Fac[[8]])})
```

```{r plot lambda similarity}
ACMTF_CV_lambda_similarity = do.call(rbind, lapply(result, FUN=function(x){x$LSI}))
ACMTF_CV_lambda_similarity = ACMTF_CV_lambda_similarity %>% as_tibble() %>% mutate(pi = ACMTFR_CV_params[,2], embedding = ACMTFR_CV_params[,1], index=1:nrow(.))

ACMTF_CV_lambda_similarity %>% ggplot(aes(x=as.factor(pi),y=V1)) + facet_wrap(~embedding) + geom_boxplot() + scale_y_log10()

ACMTF_CV_lambda_similarity %>%
  filter(embedding==0.5) %>% 
  select(-embedding) %>%
  ggplot(aes(x = as.factor(pi), y = V1)) +
  geom_violin(scale="width") +
  geom_jitter(width=0.1, size=0.75) +
  stat_summary(fun = median, geom = "point", color = "red", size = 2) +
  xlab(expression(pi)) +
  ylab("Lambda Similarity Index") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

ACMTF_CV_lambda_similarity %>% filter(embedding==0.5) %>% select(-embedding) %>% ggplot(aes(x=V1)) + facet_wrap(~pi) + geom_histogram() + ylim(0,100) + xlab("Lambda Similarity Index") + ylab("Number of models")
```

```{r plot some lambda matrix examples}
a=ACMTFR_CV_models[[10]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Pi=1") + theme(legend.position="none")

b=ACMTFR_CV_models[[78]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Pi=0.8") + theme(legend.position="none")

c=ACMTFR_CV_models[[143]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Pi=0.4") + theme(legend.position="none")


ggarrange(a,b,c)
```
```{r plot fms}
ACMTF_CV_FMS1 = do.call(rbind, lapply(result, FUN=function(x){x$FMS1})) %>% as_tibble()
ACMTF_CV_FMS2 = do.call(rbind, lapply(result, FUN=function(x){x$FMS2})) %>% as_tibble()
ACMTF_CV_FMS3 = do.call(rbind, lapply(result, FUN=function(x){x$FMS3})) %>% as_tibble()
ACMTF_CV_FMS4 = do.call(rbind, lapply(result, FUN=function(x){x$FMS4})) %>% as_tibble()
ACMTF_CV_FMS5 = do.call(rbind, lapply(result, FUN=function(x){x$FMS5})) %>% as_tibble()
ACMTF_CV_FMS6 = do.call(rbind, lapply(result, FUN=function(x){x$FMS6})) %>% as_tibble()
ACMTF_CV_FMS7 = do.call(rbind, lapply(result, FUN=function(x){x$FMS7})) %>% as_tibble()

ACMTF_CV_FMS = cbind(ACMTF_CV_FMS1, ACMTF_CV_FMS2, ACMTF_CV_FMS3, ACMTF_CV_FMS4, ACMTF_CV_FMS5, ACMTF_CV_FMS6, ACMTF_CV_FMS7)
colnames(ACMTF_CV_FMS) = c("FMS1", "FMS2", "FMS3", "FMS4", "FMS5", "FMS6", "FMS7")
ACMTF_CV_FMS = ACMTF_CV_FMS %>% as_tibble() %>% mutate(X1 = FMS1 * FMS2 * FMS3, X2 = FMS1 * FMS4 * FMS5, X3 = FMS1 * FMS6 * FMS7, pi=ACMTFR_CV_params[,2], embedding=ACMTFR_CV_params[,1], index=1:length(pi))

ACMTF_CV_FMS %>% select(X1,X2,X3,pi,embedding) %>% pivot_longer(-c(pi,embedding)) %>% ggplot(aes(x=as.factor(pi),y=value)) + facet_grid(vars(name),vars(embedding)) + geom_boxplot()

ACMTF_CV_FMS %>% select(X1,X2,X3,pi,embedding) %>% pivot_longer(-c(pi,embedding)) %>% filter(embedding %in% c(0, 0.5, 1)) %>% ggplot(aes(x=as.factor(pi),y=value)) + facet_grid(vars(name),vars(embedding)) + geom_boxplot() + xlab("Pi") + ylab("FMS")

ACMTF_CV_FMS %>% 
  select(X1,X2,X3,pi,embedding) %>%
  filter(embedding==0.5) %>%
  select(-embedding) %>%
  pivot_longer(-pi) %>%
  ggplot(aes(x=as.factor(pi),y=value)) +
  facet_wrap(~name, ncol=3) +
  geom_violin(scale="width") +
  geom_jitter(width=0.05, size=0.5) +
  stat_summary(fun = median, geom = "point", color = "red", size = 2) +
  xlab(expression(pi)) +
  ylab("Factor Match Score") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

ACMTF_CV_FMS %>% select(X1,X2,X3,pi,embedding) %>% filter(embedding==0.5) %>% select(-embedding) %>% pivot_longer(-pi) %>% ggplot(aes(x=value)) + facet_grid(vars(pi),vars(name)) + geom_histogram() + ylim(0,100) + xlab("Factor Match Score") + ylab("Number of models")
```

```{r plot iter}
ACMTF_CV_iter = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){x$iter}))
ACMTF_CV_iter = ACMTF_CV_iter %>% as_tibble() %>% mutate(pi=ACMTFR_CV_params[,2], embedding=ACMTFR_CV_params[,1], index=1:length(pi))

```

```{r plot loss}
ACMTF_CV_f = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){x$f}))
ACMTF_CV_f = ACMTF_CV_f %>% as_tibble() %>% mutate(pi=ACMTFR_CV_params[,2], embedding=ACMTFR_CV_params[,1], index=1:length(pi))

ACMTF_CV_f %>% ggplot(aes(x=as.factor(pi),y=V1)) + facet_wrap(~embedding) + geom_boxplot() + xlab("Pi") + ylab("Loss value") + scale_y_log10()
```

```{r plot FMS vs lambda similarity}
ACMTF_CV_FMS %>% mutate(lambda_similarity = ACMTF_CV_lambda_similarity$V1) %>% select(X1, pi, lambda_similarity, embedding) %>% ggplot(aes(x=lambda_similarity,y=X1)) + facet_grid(vars(pi),vars(embedding)) + geom_point() + scale_x_log10()

ACMTF_CV_FMS %>% mutate(lambda_similarity = ACMTF_CV_lambda_similarity$V1) %>% select(X2, pi, lambda_similarity, embedding) %>% ggplot(aes(x=lambda_similarity,y=X2)) + facet_grid(vars(pi),vars(embedding)) + geom_point() + scale_x_log10()

ACMTF_CV_FMS %>% mutate(lambda_similarity = ACMTF_CV_lambda_similarity$V1) %>% select(X3, pi, lambda_similarity, embedding) %>% ggplot(aes(x=lambda_similarity,y=X3)) + facet_grid(vars(pi),vars(embedding)) + geom_point() + scale_x_log10()
```

```{r fraction of correct models}
lambda_sim_threshold = 0.9
fms_threshold = 0.9

ACMTF_CV_FMS %>% mutate(lambda_similarity = ACMTF_CV_lambda_similarity$V1) %>% mutate(correct = (lambda_similarity >= lambda_sim_threshold) & (X1 >= fms_threshold) & (X2 >= fms_threshold) & (X3 >= fms_threshold)) %>% ggplot(aes(x=as.factor(pi),fill=correct)) + geom_bar(col="black") + xlab("Noise level") + ylab("Number of models")
```

```{r how often are the components found}
threshold = 0.95
colours = hue_pal()(4)

Yreal = readRDS("./Sim2b_Y_Y_inside_0.RDS")
Yreal = Yreal@data
Yreal = as.matrix(Yreal)

global1 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,1])))}))
global2 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,2])))}))
local1 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,3])))}))
local2 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,4])))}))
distinct1 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,5])))}))
distinct2 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,6])))}))
distinct3 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,7])))}))
y_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){abs(cor(x$Yhat, Yreal))}))

componentShapes = cbind(ACMTF_CV_FMS, global1, global2, local1, local2, distinct1, distinct2, distinct3, y_found)

# NEW
df = componentShapes %>%
    as_tibble() %>%
    mutate(global1 = global1 < threshold, global2 = global2 < threshold, local1 = local1 < threshold, local2 = local2 < threshold, distinct1 = distinct1 < threshold, distinct2 = distinct2 < threshold, distinct3 = distinct3 < threshold) %>%
    filter(embedding == 0.5) %>%
    select(global1,global2,local1,local2,distinct1,distinct2,distinct3,pi) %>%
    pivot_longer(-pi) %>%
    filter(value==FALSE) %>%
    mutate(X1=0,X2=0,X3=0) %>%
    select(-value)

# Common
df[df$name=="global1", "X1"] = 1
df[df$name=="global1", "X2"] = 1
df[df$name=="global1", "X3"] = 1

df[df$name=="global2", "X1"] = 1
df[df$name=="global2", "X2"] = 1
df[df$name=="global2", "X3"] = 1

# Local
df[df$name=="local1", "X1"] = 1
df[df$name=="local1", "X2"] = 1

df[df$name=="local2", "X1"] = 1
df[df$name=="local2", "X2"] = 1

# Distinct
df[df$name=="distinct1", "X1"] = 1
df[df$name=="distinct2", "X2"] = 1
df[df$name=="distinct3", "X3"] = 1

# Plot part A - bar plot
df %>% mutate(name = factor(name, levels=c("global1", "global2", "local1", "local2", "distinct1", "distinct2", "distinct3"))) %>% ggplot(aes(x=as.factor(name),fill=as.factor(pi))) + geom_bar(position=position_dodge(),col="black") + scale_x_discrete(labels=c(expression(C[123]), expression(C[123]), expression(L[12]), expression(L[12]), expression(D[1]), expression(D[2]), expression(D[3]))) + xlab("") + ylab("Number of models") + theme(legend.position="none")

# # Plot part B - upset sets
# upset_data = df %>% filter(beta==0.001) %>% as.data.frame()
# upset(upset_data, intersect=c("X1", "X2", "X3"))

# Plot part C - legend
df %>% mutate(name = factor(name, levels=c("global1", "global2", "local1", "local2", "distinct1", "distinct2", "distinct3"))) %>% ggplot(aes(x=as.factor(name),fill=as.factor(pi))) + geom_bar(position=position_dodge(),col="black") + scale_x_discrete(labels=c(expression(C[123]), expression(C[123]), expression(L[12]), expression(L[12]), expression(D[1]), expression(D[2]), expression(D[3]))) + xlab("") + ylab("Number of models") + theme(legend.position="right") + guides(fill=guide_legend("Pi"))


# END NEW

componentShapes %>% as_tibble() %>% select(pi, embedding, global1, global2, local1, local2, distinct1, distinct2, distinct3, y_found) %>% pivot_longer(-c(pi,embedding)) %>% mutate(Found = value > threshold) %>% ggplot(aes(x=as.factor(pi),fill=Found)) + facet_grid(vars(name),vars(pi)) + geom_bar()

componentShapes %>% as_tibble() %>% mutate(global1 = global1 < threshold, global2 = global2 < threshold, local1 = local1 < threshold, local2 = local2 < threshold, distinct1 = distinct1 < threshold, distinct2 = distinct2 < threshold, distinct3 = distinct3 < threshold) %>% mutate(Global = global1 + global2, Local = local1 + local2, Distinct = distinct1 + distinct2 + distinct3) %>% select(pi, embedding, Global, Local, Distinct) %>% pivot_longer(-c(pi,embedding)) %>% mutate(name = factor(name, levels=c("Global", "Local", "Distinct"))) %>% ggplot(aes(x=as.factor(pi),fill=as.factor(value))) + facet_grid(vars(name),vars(embedding)) + geom_bar(col="black") + labs(x="Pi",y="Number of models",fill="Number of components lost") + theme(legend.position="top")

componentShapes %>%
  as_tibble() %>%
  mutate(global1 = global1 < threshold, global2 = global2 < threshold, local1 = local1 < threshold, local2 = local2 < threshold, distinct1 = distinct1 < threshold, distinct2 = distinct2 < threshold, distinct3 = distinct3 < threshold) %>%
  mutate(Global = global1 + global2, Local = local1 + local2, Distinct = distinct1 + distinct2 + distinct3) %>%
  select(pi, embedding, Global, Local, Distinct) %>%
  filter(embedding==0.5) %>%
  pivot_longer(-pi) %>%
  mutate(name = factor(name, levels=c("Global", "Local", "Distinct"))) %>%
  ggplot(aes(x=as.factor(pi),fill=as.factor(value))) +
  facet_wrap(~name, nrow=3) +
  geom_bar(col="black") +
  labs(x=expression(pi),y="Number of models",fill="Number of components lost") +
  theme(legend.position="none") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

```{r grab the best local1 component from every model}
threshold = 0.95

noises = seq(0, 1, length.out=11)
noises = noises / (1 - noises)
noises[11] = 999
pis = c(0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 1.0)
simSettings = cbind(rep(noises, each=13), rep(pis, 11))
simSettings = do.call(rbind, replicate(100, simSettings, simplify=FALSE))

local_comp = inputLoadingsFac[[1]][,3]

y_orth = matrix(NA, nrow=50, ncol=nrow(simSettings))
for(i in 1:nrow(simSettings)){
  noise = simSettings[i,1]
  y = readRDS(paste0("./Sim2b_Y_Y_inside_", noise, ".RDS"))
  y = y@data
  y = as.matrix(y)
  
  dot_y_v <- sum(y * local_comp)           # crossprod(y, local_comp) in matrix form
  dot_v_v <- sum(local_comp * local_comp)  # crossprod(local_comp, local_comp)
  y_proj <- (dot_y_v / dot_v_v) * local_comp
  y_orth[,i] <- y - y_proj
}

Y_found_outside = rep(NA, length(ACMTFR_CV_models))
for(i in 1:length(ACMTFR_CV_models)){
  Y_found_outside[i] = max(abs(cor(ACMTFR_CV_models[[i]]$Fac[[1]], y_orth[,i])))
}


Y_found_inside = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,3])))}))
# Y_found_outside = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], Youtside)))}))

componentShapes = cbind(ACMTF_CV_FMS, Y_found_inside, Y_found_outside)

# NEW
df = componentShapes %>%
    as_tibble() %>%
    mutate(global1 = global1 < threshold, global2 = global2 < threshold, local1 = local1 < threshold, local2 = local2 < threshold, distinct1 = distinct1 < threshold, distinct2 = distinct2 < threshold, distinct3 = distinct3 < threshold, y_inside=Y_found_inside < threshold, y_outside=Y_found_outside<threshold) %>%
    filter(embedding == 0.5) %>%
    select(global1,global2,local1,local2,distinct1,distinct2,distinct3,y_outside,pi) %>%
    pivot_longer(-pi) %>%
    filter(value==FALSE) %>%
    mutate(X1=0,X2=0,X3=0) %>%
    select(-value)

# Common
df[df$name=="global1", "X1"] = 1
df[df$name=="global1", "X2"] = 1
df[df$name=="global1", "X3"] = 1

df[df$name=="global2", "X1"] = 1
df[df$name=="global2", "X2"] = 1
df[df$name=="global2", "X3"] = 1

# Local
df[df$name=="local1", "X1"] = 1
df[df$name=="local1", "X2"] = 1

df[df$name=="local2", "X1"] = 1
df[df$name=="local2", "X2"] = 1

# Distinct
df[df$name=="distinct1", "X1"] = 1
df[df$name=="distinct2", "X2"] = 1
df[df$name=="distinct3", "X3"] = 1

# Plot part A - bar plot
df %>% mutate(name = factor(name, levels=c("global1", "global2", "local1", "local2", "distinct1", "distinct2", "distinct3", "y_outside"))) %>% ggplot(aes(x=as.factor(name),fill=as.factor(pi))) + geom_bar(position=position_dodge(),col="black") + scale_x_discrete(labels=c(expression(C[123]), expression(C[123]), expression(L[12]), expression(L[12]), expression(D[1]), expression(D[2]), expression(D[3]), expression(y["outside"]))) + xlab("") + ylab("Number of models") + theme(legend.position="none")

# # Plot part B - upset sets
# upset_data = df %>% filter(beta==0.001) %>% as.data.frame()
# upset(upset_data, intersect=c("X1", "X2", "X3"))

# Plot part C - legend
df %>% mutate(name = factor(name, levels=c("global1", "global2", "local1", "local2", "distinct1", "distinct2", "distinct3"))) %>% ggplot(aes(x=as.factor(name),fill=as.factor(pi))) + geom_bar(position=position_dodge(),col="black") + scale_x_discrete(labels=c(expression(C[123]), expression(C[123]), expression(L[12]), expression(L[12]), expression(D[1]), expression(D[2]), expression(D[3]))) + xlab("") + ylab("Number of models") + theme(legend.position="right") + guides(fill=guide_legend("Pi"))


# END NEW

componentShapes %>% as_tibble() %>% select(pi, embedding, local1, y_found) %>% group_by(pi, embedding) %>% summarize(m1 = median(local1), y1 = median(y_found)) %>% ungroup() %>% pivot_longer(-c(pi,embedding)) %>% ggplot(aes(x=as.factor(pi),y=value,group=as.factor(name),col=as.factor(name))) + facet_wrap(~embedding) + geom_line() + geom_point() + xlab("Pi") + ylab("Maximum correlation") + scale_color_manual(name="Component", labels=c("Local1", "Y"), values=hue_pal()(2))

df %>% as_tibble() %>% ggplot(aes(x=Y_found_inside,y=Y_found_outside)) + facet_grid(vars(pi),vars(embedding)) + geom_point() + xlim(0,1) + ylim(0,1) + xlab("Local1") + ylab("Y noise") + geom_abline()

df %>% as_tibble() %>% select(pi, embedding, Y_found_inside, Y_found_outside) %>% pivot_longer(-c(pi,embedding)) %>% ggplot(aes(x=as.factor(pi),y=value)) + facet_grid(vars(embedding),vars(name)) + geom_boxplot()

df %>% as_tibble() %>% select(pi, embedding, Y_found_inside, Y_found_outside) %>% group_by(pi, embedding) %>% summarize(m1 = median(local1), y1 = median(y_found)) %>% ungroup() %>% pivot_longer(-c(pi,embedding)) %>% ggplot(aes(x=as.factor(pi),y=value,group=as.factor(name),col=as.factor(name))) + facet_wrap(~embedding) + geom_line() + geom_point() + xlab("Pi") + ylab("Maximum correlation") + scale_color_manual(name="Component", labels=c("Local1", "Y"), values=hue_pal()(2))

df %>% as_tibble() %>% select(pi, embedding, Y_found_inside, Y_found_outside) %>% pivot_longer(-c(pi,embedding)) %>% ggplot(aes(x=as.factor(pi),y=value,fill=as.factor(name))) + facet_wrap(~embedding) + geom_boxplot() + xlab("Pi") + ylab("Maximum correlation") + scale_fill_manual(name="Component", labels=c("Y_inside", "Y_outside"), values=hue_pal()(2)) + theme(legend.position="top")

df %>% 
  as_tibble() %>%
  select(pi, embedding, Y_found_inside, Y_found_outside) %>% 
  filter(embedding==0.5) %>%
  select(-embedding) %>%
  pivot_longer(-pi) %>%
  ggplot(aes(x=as.factor(pi),y=value,fill=as.factor(name))) +
  geom_violin(scale="width") +
  geom_point(size=0.5,position=position_jitterdodge(jitter.width=0.1)) +
  xlab(expression(pi)) +
  ylab("Maximum correlation") +
  scale_fill_manual(name="Component", labels=c("Y_inside", "Y_outside"), values=hue_pal()(2)) +
  theme(legend.position="none")
```

```{r number of iterations}
df = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){x$iter})) %>% as_tibble()

df %>% mutate(pi=ACMTFR_CV_params[,2], embedding = ACMTFR_CV_params[,1]) %>% filter(embedding==0.5) %>% ggplot(aes(x=V1)) + facet_wrap(~pi) + geom_histogram() + scale_x_log10() + xlab("Number of iterations") + ylab("Number of models")
```
