---
title: "20241203_ACMTF_validation"
author: "G.R. van der Ploeg"
date: "2024-12-03"
output: html_document
---

# Preamble
```{r setup, include=FALSE}
library(rTensor)
library(CMTFtoolbox)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(scales)
```

```{r define FMS}

calculateFMS <- function(modelFac, realFac, numComponents) {
  
  # Project modelFac onto realFac to make sure components are not split
  modelFac = modelFac %*% pracma::pinv(t(modelFac) %*% modelFac) %*% t(modelFac) %*% realFac
  
  # Create a similarity matrix for the pairwise comparison
  similarity_matrix <- matrix(0, nrow = ncol(modelFac), ncol = ncol(modelFac))
  
  # Compute pairwise cosine similarity across all modes
  for (k in 1:ncol(modelFac)) {
    for (l in 1:ncol(realFac)) {
      vect1 <- as.matrix(modelFac[, k])
      vect2 <- as.matrix(realFac[, l])
      
      # Cosine similarity
      similarity_matrix[k, l] <- abs(t(vect1) %*% vect2) / (norm(vect1, "F") * norm(vect2, "F"))
    }
  }
  
  # Use Hungarian algorithm to find the best matching
  assignment <- solve_LSAP(similarity_matrix, maximum = TRUE)
  
  # Permute columns in the model to fit the input components
  # modelFac_perm <- modelFac[,assignment]
  
  # Calculate FMS based on the best matching
  FMS <- sum(similarity_matrix[cbind(seq_along(assignment), assignment)])
  
  # Average over the number of components
  FMS <- FMS / numComponents
  return(FMS)
}

```

```{r load input loadings}
inputLoadings = readRDS("./Sim1b_input_loadings_Y_inside.RDS")

# Reorganize into Fac object
inputLoadingsFac = inputLoadings
inputLoadingsFac[[2]] = inputLoadings[[2]][,c(1,4,7,9,11)]
inputLoadingsFac[[3]] = inputLoadings[[3]][,c(1,4,7,9,11)]
inputLoadingsFac[[4]] = inputLoadings[[2]][,c(2,5,8,10,12)]
inputLoadingsFac[[5]] = inputLoadings[[3]][,c(2,5,8,10,12)]
inputLoadingsFac[[6]] = inputLoadings[[2]][,c(3,6,13)]
inputLoadingsFac[[7]] = inputLoadings[[3]][,c(3,6,13)]

```

# Analyze ACMTF results
```{r load ACMTF models}
ACMTF_CV_models = readRDS("./Sim1b_ACMTF_CV_models_Y_inside.RDS")
ACMTF_CV_params = readRDS("./Sim1b_ACMTF_CV_params_Y_inside.RDS")
```

```{r plot varExps for ACMTF}
defaultModels = which(ACMTF_CV_params == 0.4)
ACMTF_models = ACMTF_CV_models[defaultModels]
numModes = length(ACMTF_models[[1]]$Fac) - 1

ACMTF_FMS1 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[1]], inputLoadingsFac[[1]], numComponents=7)})) %>% as_tibble()
ACMTF_FMS2 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[2]], inputLoadingsFac[[2]], numComponents=5)})) %>% as_tibble()
ACMTF_FMS3 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[3]], inputLoadingsFac[[3]], numComponents=5)})) %>% as_tibble()
ACMTF_FMS4 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[4]], inputLoadingsFac[[4]], numComponents=5)})) %>% as_tibble()
ACMTF_FMS5 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[5]], inputLoadingsFac[[5]], numComponents=5)})) %>% as_tibble()
ACMTF_FMS6 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[6]], inputLoadingsFac[[6]], numComponents=3)})) %>% as_tibble()
ACMTF_FMS7 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[7]], inputLoadingsFac[[7]], numComponents=3)})) %>% as_tibble()

ACMTF_f = do.call(rbind, lapply(ACMTF_models, FUN=function(x){x$f}))
correctModels = ACMTF_f %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% filter(V1 < 1.05) %>% select(index) %>% pull()

ACMTF_FMS = cbind(ACMTF_FMS1, ACMTF_FMS2, ACMTF_FMS3, ACMTF_FMS4, ACMTF_FMS5, ACMTF_FMS6, ACMTF_FMS7)
colnames(ACMTF_FMS) = c("ACMTF_FMS1", "ACMTF_FMS2", "ACMTF_FMS3", "ACMTF_FMS4", "ACMTF_FMS5", "ACMTF_FMS6", "ACMTF_FMS7")

ACMTF_FMS = ACMTF_FMS %>%
  as_tibble() %>%
  mutate(index=1:nrow(.)) %>%
  mutate(correct = index %in% correctModels,
         FMS_X1 = ACMTF_FMS1 * ACMTF_FMS2 * ACMTF_FMS3,
         FMS_X2 = ACMTF_FMS1 * ACMTF_FMS4 * ACMTF_FMS5,
         FMS_X3 = ACMTF_FMS1 * ACMTF_FMS6 * ACMTF_FMS7)

ACMTF_FMS %>% as_tibble() %>%
  select(-FMS_X1, -FMS_X2, -FMS_X3) %>%
  pivot_longer(-c(index,correct)) %>%
  ggplot(aes(x=index,y=value,fill=as.factor(correct))) +
  facet_wrap(~name) +
  geom_bar(stat="identity")

ACMTF_FMS %>%
  select(index, correct, FMS_X1, FMS_X2, FMS_X3) %>%
  pivot_longer(-c(index,correct)) %>%
  ggplot(aes(x=index,y=value,fill=as.factor(correct))) +
  facet_wrap(~name) +
  geom_bar(stat="identity")

ACMTF_FMS %>% 
  select(-FMS_X1, -FMS_X2, -FMS_X3) %>%
  pivot_longer(-index) %>%
  ggplot(aes(x=as.factor(name),y=value)) +
  geom_boxplot()

ACMTF_FMS %>% 
  select(index, FMS_X1, FMS_X2, FMS_X3) %>%
  pivot_longer(-index) %>%
  ggplot(aes(x=as.factor(name),y=value)) +
  geom_boxplot()

ACMTF_varExps = do.call(rbind, lapply(ACMTF_models, FUN=function(x){(x$varExp)})) %>% as_tibble()
ACMTF_varExps = ACMTF_varExps * 100
colnames(ACMTF_varExps) = c("X1", "X2", "X3")
ACMTF_varExps = ACMTF_varExps %>% mutate(index=1:nrow(.))

# correctModels = ACMTF_varExps %>% filter(X1 > 99, X2 > 99, X3 > 99) %>% select(index) %>% pull()
ACMTF_varExps = ACMTF_varExps %>% mutate(correct = index %in% correctModels)

ACMTF_models_correct = ACMTF_models[ACMTF_varExps$index %in% correctModels]
ACMTF_models_incorrect = ACMTF_models[!ACMTF_varExps$index %in% correctModels]

a = ACMTF_varExps %>% ggplot(aes(x=index,y=X1,fill=as.factor(correct))) + geom_bar(stat="identity") + xlab("") + ylab("varExp X1 (%)")
b = ACMTF_varExps %>% ggplot(aes(x=index,y=X2,fill=as.factor(correct))) + geom_bar(stat="identity") + xlab("") + ylab("varExp X2 (%)")
c = ACMTF_varExps %>% ggplot(aes(x=index,y=X3,fill=as.factor(correct))) + geom_bar(stat="identity") + xlab("Model index") + ylab("varExp X3 (%)")
ggarrange(a,b,c,nrow=3, common.legend=TRUE)
```

```{r inspect lambdas for ACMTF}
ACMTF_models_correct[[1]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Lambdas (correct model)")

ACMTF_models_incorrect[[1]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Lambdas (incorrect model)")

do.call(rbind, lapply(ACMTF_models, FUN=function(x){x$Fac[[8]]} %>% as_tibble() %>% mutate(index=1:nrow(.))))
```

# ACMTF CV
```{r plot varExps for ACMTF CV}
ACMTF_CV_f = do.call(rbind, lapply(ACMTF_CV_models, FUN=function(x){x$f}))
ACMTF_CV_f = ACMTF_CV_f %>% as_tibble() %>% mutate(noise=ACMTF_CV_params, index=1:length(noise))

ACMTF_CV_FMS = do.call(rbind, lapply(ACMTF_CV_models, FUN=function(x){calculateFMS(x$Fac[[1]], inputLoadingsFac[[1]], 7) * calculateFMS(x$Fac[[2]], inputLoadingsFac[[2]], 5) * calculateFMS(x$Fac[[3]], inputLoadingsFac[[3]], 5) * calculateFMS(x$Fac[[4]], inputLoadingsFac[[4]], 5) * calculateFMS(x$Fac[[5]], inputLoadingsFac[[5]], 5) * calculateFMS(x$Fac[[6]], inputLoadingsFac[[6]], 3) * calculateFMS(x$Fac[[7]], inputLoadingsFac[[7]], 3)}))
ACMTF_CV_FMS = ACMTF_CV_FMS %>% as_tibble() %>% mutate(noise=ACMTF_CV_params, index=1:length(noise))

ACMTF_CV_f %>% ggplot(aes(x=as.factor(noise),y=V1)) + geom_boxplot() + xlab("Noise on X") + ylab("Loss value")
ACMTF_CV_FMS %>% ggplot(aes(x=as.factor(noise),y=V1)) + geom_boxplot()
ACMTF_CV_FMS %>% ggplot(aes(x=as.factor(noise),y=V1)) + geom_boxplot() + ylim(c(0.9,1.0)) + xlab("Noise level on X") + ylab("Overall FMS") + geom_hline(yintercept=0.999, col="red")

ACMTF_CV_FMS %>% mutate(correct = V1 > 0.999) %>% ggplot(aes(x=as.factor(noise),fill=as.factor(correct))) + geom_bar(col="black")
```
```{r how often are the components found}
projectAndCosine = function(Test, Ttrue){
  Tproj = Test %*% pracma::pinv(t(Test) %*% Test) %*% t(Test) %*% Ttrue
  similarity = sum(Tproj * Ttrue) / (norm(Tproj, "2") * norm(Ttrue, "2"))
  return(similarity)
}

threshold = 0.99
global1_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,1]) > threshold}))
global2_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,2]) > threshold}))
local1_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,3]) > threshold}))
local2_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,4]) > threshold}))
distinct1_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,5]) > threshold}))
distinct2_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,6]) > threshold}))
distinct3_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,7]) > threshold}))

componentShapes = cbind(ACMTF_CV_FMS, global1_found, global2_found, local1_found, local2_found, distinct1_found, distinct2_found, distinct3_found) %>% as_tibble()

componentShapes %>% select(-V1,-index) %>% pivot_longer(-noise) %>% ggplot(aes(x=as.factor(noise),fill=as.factor(value))) + facet_wrap(~name,nrow=7) + geom_bar()

```
```{r comparison of two models}
modelA = ACMTF_CV_models[[301]]$Fac # 30% noise
modelB = ACMTF_CV_models[[601]]$Fac # 60% noise
modelC = ACMTF_CV_models[[901]]$Fac # 90% noise

# Global 1
df = cbind(modelA[[1]][,2], modelB[[1]][,2], modelC[[1]][,2], inputLoadingsFac[[1]][,1]) %>% as_tibble() 
colnames(df) = c("Low", "Medium", "High", "True")
a = df %>% pivot_longer(-True) %>% ggplot(aes(x=True,y=value,col=as.factor(name))) + geom_point() + geom_abline() + ggtitle("Global 1")

# Global 2
df = cbind(modelA[[1]][,1], -1*modelB[[1]][,1], modelC[[1]][,1], inputLoadingsFac[[1]][,2]) %>% as_tibble() 
colnames(df) = c("Low", "Medium", "High", "True")
b = df %>% pivot_longer(-True) %>% ggplot(aes(x=True,y=value,col=as.factor(name))) + geom_point() + geom_abline() + ggtitle("Global 2")

# Local 1
df = cbind(-1*modelA[[1]][,3], -1*modelB[[1]][,3], -1*modelC[[1]][,3], inputLoadingsFac[[1]][,3]) %>% as_tibble() 
colnames(df) = c("Low", "Medium", "High", "True")
c = df %>% pivot_longer(-True) %>% ggplot(aes(x=True,y=value,col=as.factor(name))) + geom_point() + geom_abline() + ggtitle("Local 1")

# Local 2
df = cbind(-1*modelA[[1]][,4], modelB[[1]][,4], modelC[[1]][,4], inputLoadingsFac[[1]][,4]) %>% as_tibble() 
colnames(df) = c("Low", "Medium", "High", "True")
d = df %>% pivot_longer(-True) %>% ggplot(aes(x=True,y=value,col=as.factor(name))) + geom_point() + geom_abline() + ggtitle("Local 2")

# Distinct 1
df = cbind(modelA[[1]][,7], modelB[[1]][,7], modelC[[1]][,7], inputLoadingsFac[[1]][,5]) %>% as_tibble() 
colnames(df) = c("Low", "Medium", "High", "True")
e = df %>% pivot_longer(-True) %>% ggplot(aes(x=True,y=value,col=as.factor(name))) + geom_point() + geom_abline() + ggtitle("Distinct 1")

# Distinct 2
df = cbind(modelA[[1]][,6], -1*modelB[[1]][,6], modelC[[1]][,6], inputLoadingsFac[[1]][,6]) %>% as_tibble() 
colnames(df) = c("Low", "Medium", "High", "True")
f = df %>% pivot_longer(-True) %>% ggplot(aes(x=True,y=value,col=as.factor(name))) + geom_point() + geom_abline() + ggtitle("Distinct 2")

# Distinct 3
df = cbind(modelA[[1]][,5], -1*modelB[[1]][,5], modelC[[1]][,5], inputLoadingsFac[[1]][,7]) %>% as_tibble() 
colnames(df) = c("Low", "Medium", "High", "True")
g = df %>% pivot_longer(-True) %>% ggplot(aes(x=True,y=value,col=as.factor(name))) + geom_point() + geom_abline() + ggtitle("Distinct 3")

ggarrange(a,b,c,d,e,f,g, common.legend=TRUE)
```

```{r test projected difference}
global1_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,1])}))
global2_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,2])}))
local1_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,3])}))
local2_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,4])}))
distinct1_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,5])}))
distinct2_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,6])}))
distinct3_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,7])}))

df = cbind(ACMTF_CV_FMS, global1_found, global2_found, local1_found, local2_found, distinct1_found, distinct2_found, distinct3_found) %>% as_tibble()
df %>% select(-V1) %>% pivot_longer(-c(noise,index)) %>% ggplot(aes(x=as.factor(noise),y=value)) + facet_wrap(~name) + geom_boxplot() + ylim(0.9975, 1.0) + xlab("Noise on X") + ylab("Cosine similarity")
# Removed 130 values
```

```{r test real difference}
cosineOnly = function(Test, Ttrue){
  bestMatch = which(abs(cor(Test, Ttrue)) == max(abs(cor(Test,Ttrue))))
  Test = Test[,bestMatch]
  similarity = abs(sum(Test * Ttrue)) / (norm(Test, "2") * norm(Ttrue, "2"))
  return(similarity)
}

global1_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,1])}))
global2_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,2])}))
local1_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,3])}))
local2_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,4])}))
distinct1_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,5])}))
distinct2_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,6])}))
distinct3_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,7])}))

df = cbind(ACMTF_CV_FMS, global1_found, global2_found, local1_found, local2_found, distinct1_found, distinct2_found, distinct3_found) %>% as_tibble()
df %>% select(-V1) %>% pivot_longer(-c(noise,index)) %>% ggplot(aes(x=as.factor(noise),y=value)) + facet_wrap(~name) + geom_boxplot() + ylim(0.9975, 1.0) + xlab("Noise on X") + ylab("Cosine similarity")
# Removed 1000 values
```
