---
title: "Rasmus"
output: html_document
date: "2024-08-22"
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(ggpattern)
library(ggrepel)
library(stringr)
library(parafac4microbiome)
library(NPLStoolbox)
library(CMTFtoolbox)
library(scales)
library(vegan)
```

```{r define colours}

# Old approach
# Needed colours: BMI groups (3) and phyla levels (6)
# colours = hue_pal()(9)
# #show_col(colours)
# BMI_cols = colours[c(1,4,7)]
# phylum_cols = colours[-c(1,4,7)]

# Rasmus's suggestion
colours = RColorBrewer:: brewer.pal(8, "Dark2")
BMI_cols = c("darkgreen","darkgoldenrod","darkred") #colours[1:3]
WHZ_cols = c("darkgreen", "darkgoldenrod", "dodgerblue4")
phylum_cols = colours
```

```{r process and homogenize data}
homogenizedSamples = intersect(intersect(NPLStoolbox::Jakobsen2025$faeces$mode1$subject, NPLStoolbox::Jakobsen2025$milkMicrobiome$mode1$subject), NPLStoolbox::Jakobsen2025$milkMetabolomics$mode1$subject)

# Faeces
newFaeces = NPLStoolbox::Jakobsen2025$faeces

mask = newFaeces$mode1$subject %in% homogenizedSamples
newFaeces$data = newFaeces$data[mask,,]
newFaeces$mode1 = newFaeces$mode1[mask,]
processedFaeces = parafac4microbiome::processDataCube(newFaeces, sparsityThreshold = 0.75, centerMode=1, scaleMode=2)

# Milk
newMilk = NPLStoolbox::Jakobsen2025$milkMicrobiome

mask = newMilk$mode1$subject %in% homogenizedSamples
newMilk$data = newMilk$data[mask,,]
newMilk$mode1 = newMilk$mode1[mask,]
processedMilk = parafac4microbiome::processDataCube(newMilk, sparsityThreshold=0.85, centerMode=1, scaleMode=2)

# Milk metab
newMilkMetab = NPLStoolbox::Jakobsen2025$milkMetabolomics

mask = newMilkMetab$mode1$subject %in% homogenizedSamples
newMilkMetab$data = newMilkMetab$data[mask,,]
newMilkMetab$mode1 = newMilkMetab$mode1[mask,]
processedMilkMetab = parafac4microbiome::processDataCube(newMilkMetab, CLR=FALSE, centerMode=1, scaleMode=2)
```

```{r prepare y}
Y = processedFaeces$mode1$BMI
Ycnt = Y - mean(Y)
Ynorm = Ycnt / norm(Ycnt, "2")
```

```{r make NPLS models of the data}
# CV_faecal = NPLStoolbox::ncrossreg(processedFaeces$data, Ynorm)

# a=CV_faecal$varExp %>% pivot_longer(-numComponents) %>% ggplot(aes(x=as.factor(numComponents),y=value,col=as.factor(name),group=as.factor(name))) + geom_line() + geom_point() + xlab("Number of components") + ylab("Variance explained (%)") + theme(legend.position="none")
# b=CV_faecal$RMSE %>% ggplot(aes(x=numComponents,y=RMSE)) + geom_line() + geom_point() + xlab("Number of components") + ylab("RMSECV")
# ggarrange(a,b)

NPLS_faecal = NPLStoolbox::triPLS1(processedFaeces$data, Ynorm, 1)

# CV_milk = NPLStoolbox::ncrossreg(processedMilk$data, Ynorm)
# 
# a=CV_milk$varExp %>% pivot_longer(-numComponents) %>% ggplot(aes(x=as.factor(numComponents),y=value,col=as.factor(name),group=as.factor(name))) + geom_line() + geom_point() + xlab("Number of components") + ylab("Variance explained (%)") + theme(legend.position="none")
# b=CV_milk$RMSE %>% ggplot(aes(x=numComponents,y=RMSE)) + geom_line() + geom_point() + xlab("Number of components") + ylab("RMSECV")
# ggarrange(a,b)

NPLS_milk = NPLStoolbox::triPLS1(processedMilk$data, Ynorm, 1)
# 
# CV_milkMetab = NPLStoolbox::ncrossreg(processedMilkMetab$data, Ynorm)
# 
# a=CV_milkMetab$varExp %>% pivot_longer(-numComponents) %>% ggplot(aes(x=as.factor(numComponents),y=value,col=as.factor(name),group=as.factor(name))) + geom_line() + geom_point() + xlab("Number of components") + ylab("Variance explained (%)") + theme(legend.position="none")
# b=CV_milkMetab$RMSE %>% ggplot(aes(x=numComponents,y=RMSE)) + geom_line() + geom_point() + xlab("Number of components") + ylab("RMSECV")
# ggarrange(a,b)

NPLS_milkMetab = NPLStoolbox::triPLS1(processedMilkMetab$data, Ynorm, 1) # two components is better but the second component explains little biology
```

```{r create Z object for fitting ACMTF}
datasets = list(processedFaeces$data, processedMilk$data, processedMilkMetab$data)
modes = list(c(1,2,3), c(1,4,5), c(1,6,7))
Z = setupCMTFdata(datasets, modes, normalize=TRUE)

# model = CMTFtoolbox::acmtfr_opt(Z, Ynorm, numComponents=2, pi=1, nstart=1)
```

```{r check best pi}
# CV_pi_models = readRDS("./CV_BMI_pi_models.RDS")
# pis = c(0.2, 0.5, 0.6, 0.7, 0.725, 0.75, 0.775, 0.8, 0.825, 0.85, 0.875, 0.9, 1)
# 
# repaired_CV_pi_models = list()
# for(i in 1:length(pis)){
#   models = CV_pi_models[[i]]
#   loss = do.call(rbind, lapply(models, FUN=function(x){x$f}))
#   index = which(loss == min(loss))
#   repaired_CV_pi_models[[i]] = models[[index]]
# }
# 
# varExpsY = do.call(rbind, lapply(repaired_CV_pi_models, FUN=function(x){x$varExpY}))
# df = cbind(varExpsY, pis)
# colnames(df) = c("varExpY", "pi")
# df = df %>% as_tibble() %>% mutate(numComponents=1)
# 
# CV_pi_models2 = readRDS("./CV_BMI_pi_models2.RDS")
# pis2 = c(0.25, 0.5, 0.75, 0.875, 0.88, 0.885, 0.89, 0.895, 0.9, 0.905, 0.91, 0.915, 0.92, 0.925, 0.95, 0.975, 1)
# 
# varExpsY2 = do.call(rbind, lapply(CV_pi_models2, FUN=function(x){x$varExpY}))
# df2 = cbind(varExpsY2, pis2) %>% as_tibble()
# colnames(df2) = c("varExpY", "pi")
# df2 = df2 %>% mutate(numComponents=2)
# 
# df = rbind(df, df2)
# 
# df %>% ggplot(aes(x=pi,y=varExpY,col=as.factor(numComponents))) + geom_line() + geom_point() + xlab(expression(pi)) + ylab("Variance explained in Y (%)") + guides(color=guide_legend(title="Number of components")) + theme(legend.position="top")

```

```{r check CV}
# BMI1_small = readRDS("./CV_small_BMI_0.8.RDS")
# BMI2_small = readRDS("./CV_small_BMI_0.85.RDS")
# BMI3_small = readRDS("./CV_small_BMI_0.9.RDS")
# BMI4_small = readRDS("./CV_small_BMI_0.95.RDS")

# investigateFMS(lapply(Jakobsen2025$Z$object, FUN=function(x){x@data}), Jakobsen2025$Z$modes, sharedMode=1, numCores=16, method="L-BFGS")
```

```{r plot the things}
plotCV = function(result){
  varExpData = result$varExp
  RMSEdata = result$RMSE
  FMSdata = result$FMS
  
  a = varExpData %>%
    pivot_longer(-numComponents) %>%
    ggplot(ggplot2::aes(x = numComponents,y = value, col = as.factor(name))) +
    geom_path() +
    geom_point() +
    labs(x="Number of components", y="Variance explained (%)", color="Block") +
    scale_x_continuous(breaks=varExpData$numComponents) +
    theme(legend.position="na") +
    ylim(min(varExpData),100)
  b = RMSEdata %>%
    ggplot(ggplot2::aes(x = numComponents, y = RMSE)) +
    geom_path() +
    geom_point() +
    labs(x = "Number of components", y = "RMSECV") +
    scale_x_continuous(breaks = RMSEdata$numComponents)
  c = FMSdata %>%
    pivot_longer(-numComponents) %>%
    ggplot(aes(x=as.factor(numComponents),y=value)) +
    facet_wrap(~name) +
    geom_boxplot() +
    labs(x="Number of components",y="Factor Match Score")
  ggarrange(a,b,c,nrow=1)
}

plotCV_old = function(result){
  varExpData = result$varExp
  RMSEdata = result$RMSE
  a = varExpData %>%
    pivot_longer(-numComponents) %>%
    ggplot(ggplot2::aes(x = numComponents,y = value, col = as.factor(name))) +
    geom_path() +
    geom_point() +
    labs(x="Number of components", y="Variance explained (%)", color="Block") +
    scale_x_continuous(breaks=varExpData$numComponents) +
    theme(legend.position="na") +
    ylim(min(varExpData),100)
  b = RMSEdata %>%
    ggplot(ggplot2::aes(x = numComponents, y = RMSE)) +
    geom_path() +
    geom_point() +
    labs(x = "Number of components", y = "RMSE") +
    scale_x_continuous(breaks = RMSEdata$numComponents)
  ggarrange(a,b)
}

# plotCV(BMI1_small)
# plotCV(BMI2_small)
# plotCV(BMI3_small)
# plotCV(BMI4_small)
# plotCV(BMI5_small)
# plotCV(BMI6_small)
# plotCV(BMI7_small)
# plotCV(BMI8_small)

# plotCV(BMI1)
# plotCV(BMI2)
# plotCV(BMI3)
# plotCV(BMI4)
# plotCV(BMI5)
# plotCV(BMI6)
```

```{r find acmtf model}
ACMTFR_models = readRDS("./ACMTF_model.RDS")

iter = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$iter}))
loss = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$f}))
varExpX = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$varExp}))
varExpY = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$varExpY}))

df = cbind(loss, varExpX, varExpY) %>% as_tibble()
colnames(df) = c("Loss", "varExpX1", "varExpX2", "varExpX3", "varExpY")

df %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(name=factor(name, levels=c("varExpX1", "varExpX2", "varExpX3", "Loss", "varExpY"))) %>% ggplot(aes(x=index,y=value)) + facet_wrap(~name,scale="free_y") + geom_bar(stat="identity") + scale_y_log10()

df %>% mutate(index=1:nrow(.)) %>% arrange(Loss)

bestIndex = 37
model_ACMTF = ACMTFR_models[[bestIndex]]
```

```{r find best model pi=0.80}
ACMTFR_models = readRDS("./ACMTFR_model_bmi80.RDS")

iter = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$iter}))
loss = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$f}))
varExpX = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$varExp}))
varExpY = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$varExpY}))
# cor1_2 = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){cor(x$Fac[[1]][,1],x$Fac[[1]][,2])}))

df = cbind(loss, varExpX, varExpY) %>% as_tibble()
colnames(df) = c("Loss", "varExpX1", "varExpX2", "varExpX3", "varExpY")

df %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% ggplot(aes(x=index,y=value)) + facet_wrap(~name,scale="free_y") + geom_bar(stat="identity")

df %>% mutate(index=1:nrow(.)) %>% arrange(Loss)

bestIndex = 60
model_bmi80 = ACMTFR_models[[bestIndex]]
```

```{r find best model pi=0.85}
ACMTFR_models = readRDS("./ACMTFR_model_bmi85.RDS")

iter = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$iter}))
loss = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$f}))
varExpX = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$varExp}))
varExpY = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$varExpY}))
# cor1_2 = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){cor(x$Fac[[1]][,1],x$Fac[[1]][,2])}))

df = cbind(loss, varExpX, varExpY) %>% as_tibble()
colnames(df) = c("Loss", "varExpX1", "varExpX2", "varExpX3", "varExpY")

df %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% ggplot(aes(x=index,y=value)) + facet_wrap(~name,scale="free_y") + geom_bar(stat="identity")

df %>% mutate(index=1:nrow(.)) %>% arrange(Loss)

bestIndex = 54
model_bmi85 = ACMTFR_models[[bestIndex]]
```

```{r find best model pi=0.90}
ACMTFR_models = readRDS("./ACMTFR_model_bmi90.RDS")

iter = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$iter}))
loss = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$f}))
varExpX = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$varExp}))
varExpY = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$varExpY}))
# cor1_2 = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){cor(x$Fac[[1]][,1],x$Fac[[1]][,2])}))

df = cbind(loss, varExpX, varExpY) %>% as_tibble()
colnames(df) = c("Loss", "varExpX1", "varExpX2", "varExpX3", "varExpY")

df %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% ggplot(aes(x=index,y=value)) + facet_wrap(~name,scale="free_y") + geom_bar(stat="identity")

df %>% mutate(index=1:nrow(.)) %>% arrange(Loss)

bestIndex = 63
model_bmi90 = ACMTFR_models[[bestIndex]]
```

```{r find best model pi=0.95}
ACMTFR_models = readRDS("./ACMTFR_model_bmi95.RDS")

iter = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$iter}))
loss = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$f}))
varExpX = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$varExp}))
varExpY = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){x$varExpY}))
# cor1_2 = do.call(rbind, lapply(ACMTFR_models, FUN=function(x){cor(x$Fac[[1]][,1],x$Fac[[1]][,2])}))

df = cbind(loss, varExpX, varExpY) %>% as_tibble()
colnames(df) = c("Loss", "varExpX1", "varExpX2", "varExpX3", "varExpY")

df %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% ggplot(aes(x=index,y=value)) + facet_wrap(~name,scale="free_y") + geom_bar(stat="identity")

df %>% mutate(index=1:nrow(.)) %>% arrange(Loss)

bestIndex = 70
model_bmi95 = ACMTFR_models[[bestIndex]]
```

```{r plot the model}

plotModel = function(model, comp=1){
  a = processedFaeces$mode1 %>%
    mutate(loading = model$Fac[[1]][,comp]) %>%
    mutate(BMI.group=factor(BMI.group,levels=c("NW","OW","OB"))) %>%
    arrange(BMI.group) %>%
    mutate(index=1:nrow(.)) %>%
    ggplot(aes(x=index,y=loading,fill=as.factor(BMI.group))) +
    geom_bar(stat="identity") +
    scale_fill_manual(name="BMI group", labels=c("Normal", "Overweight", "Obese"), values=BMI_cols) +
    theme(legend.position = "na") +
    ylab(paste0("Component ", comp)) +
    xlab("Subject index") +
    ggtitle("Subject mode")

    b = abs(model$Fac[[8]][,comp]) %>%
    as_tibble() %>%
    mutate(Block = paste0("X", 1:nrow(.))) %>%
    ggplot(aes(x=Block,y=value)) +
    geom_bar(stat="identity") +
    ylab(expression(lambda)) +
    ggtitle("Lambda")
  
  c = processedFaeces$mode2 %>%
    mutate(loading = model$Fac[[2]][,comp]) %>%
    arrange(V3) %>%
    mutate(index=1:nrow(.)) %>%
    ggplot(aes(x=index,y=loading,fill=as.factor(V3))) +
    geom_bar(stat="identity") +
    scale_fill_manual(name="Phylum", labels=c("Actinobacteriota", "Bacteroidota", "Firmicutes", "Proteobacteria", "Verrucomicrobiota"), values=phylum_cols[c(1,2,4,5,6)]) +
    theme(legend.position = "na") +
    ylab(paste0("Component ", comp)) +
    xlab("Feature index") +
    ggtitle("Faecal microbiota")
  
  d = model$Fac[[3]][,comp] %>%
    as_tibble() %>%
    mutate(index=1:nrow(.)) %>%
    ggplot(aes(x=index,y=value)) +
    geom_line() + geom_point() +
    ylab(paste0("Component ", comp)) +
    scale_x_continuous(name="Time point [days]", breaks=c(1:3), labels=c(30,60,90)) +
    ggtitle("Faecal microbiota")
  
  e = processedMilk$mode2 %>%
    mutate(loading = model$Fac[[4]][,comp]) %>%
    arrange(V3) %>%
    mutate(index=1:nrow(.)) %>%
    ggplot(aes(x=index,y=loading,fill=as.factor(V3))) +
    geom_bar(stat="identity") +
    scale_fill_manual(name="Phylum", labels=c("Actinobacteriota", "Bacteroidota", "Cyanobacteria", "Firmicutes", "Proteobacteria", "Verrucomicrobiota"), values=phylum_cols[1:6]) +
    theme(legend.position = "na") +
    ylab(paste0("Component ", comp)) +
    xlab("Feature index") +
    ggtitle("HM microbiota")
  
  f = model$Fac[[5]][,comp] %>%
    as_tibble() %>%
    mutate(index=1:nrow(.)) %>%
    ggplot(aes(x=index,y=value)) +
    geom_line() +
    geom_point() +
    ylab(paste0("Component ", comp)) +
    scale_x_continuous(name="Time point [days]", breaks=c(1:4), labels=c(3,30,60,90)) +
    ggtitle("HM microbiota")
  
  g = processedMilkMetab$mode2 %>%
    mutate(loading = model$Fac[[6]][,comp]) %>%
    arrange(Class,Metabolite) %>%
    mutate(index=1:nrow(.)) %>%
    ggplot(aes(x=index,y=loading,fill=as.factor(Class))) +
    geom_bar(stat="identity") +
    scale_fill_manual(name="Metabolite class", labels=c("Amino acids and derivatives", "Energy related", "Fatty acids and derivatives", "Food derived", "Microbially derived", "Oligosaccharides", "Pharmaceuticals", "Sugars"), values=phylum_cols) +
    theme(legend.position = "na") +
    ylab(paste0("Component ", comp)) +
    xlab("Feature index") +
    ggtitle("HM metabolomics")
  
  h = model$Fac[[7]][,comp] %>%
    as_tibble() %>%
    mutate(index=1:nrow(.)) %>%
    ggplot(aes(x=index,y=value)) +
    geom_line() +
    geom_point() +
    ylab(paste0("Component ", comp)) +
    scale_x_continuous(name="Time point [days]", breaks=c(1:4), labels=c(3,30,60,90)) +
    ggtitle("HM metabolomics")
  
  ggarrange(a,b,c,d,e,f,g,h, nrow=4, ncol=2)
}

plotModel(model_ACMTF, 1)

plotModel(model_bmi95, 1)

plotModel(model_bmi90, 1)

plotModel(model_bmi85, 1)
plotModel(model_bmi85, 2)

plotModel(model_bmi80, 1)
plotModel(model_bmi80, 2)
```

```{r plot the NPLS models}
# Faecal
a=processedFaeces$mode1 %>% mutate(Component_1=NPLS_faecal$Fac[[1]][,1]) %>% arrange(BMI.group,subject) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(BMI.group))) + geom_bar(stat="identity") + scale_fill_manual(name="BMI group", labels=c("Normal", "Overweight", "Obese"), values=BMI_cols) + theme(legend.position="none") + xlab("Subject index") + ylab("Component 1")

b=processedFaeces$mode2 %>% mutate(Component_1=NPLS_faecal$Fac[[2]][,1]) %>% arrange(V3,V4,V5,V6,V7,V8,V1) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(V3))) + geom_bar(stat="identity") + scale_fill_manual(name="Phylum", labels=c("Actinobacteriota", "Bacteroidota", "Firmicutes", "Proteobacteria", "Verrucomicrobiota"), values=phylum_cols[c(1,2,4,5,6)]) + theme(legend.position="none") + xlab("Feature index") + ylab("Component 1")

c=processedFaeces$mode3 %>% mutate(Component_1=NPLS_faecal$Fac[[3]][,1]) %>% ggplot(aes(x=timepoint,y=Component_1)) + geom_line() + geom_point()+ xlab("Time point [days]") + ylab("Component 1")

# Milk
d=processedMilk$mode1 %>% mutate(Component_1=NPLS_milk$Fac[[1]][,1]) %>% arrange(BMI.group,subject) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(BMI.group))) + geom_bar(stat="identity") + scale_fill_manual(name="BMI group", labels=c("Normal", "Overweight", "Obese"), values=BMI_cols) + theme(legend.position="none") + xlab("Subject index") + ylab("Component 1")

e=processedMilk$mode2 %>% mutate(Component_1=NPLS_milk$Fac[[2]][,1]) %>% arrange(V3,V4,V5,V6,V7,V8,V1) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(V3))) + geom_bar(stat="identity") + scale_fill_manual(name="Phylum", labels=c("Actinobacteriota", "Bacteroidota", "Cyanobacteria", "Firmicutes", "Proteobacteria", "Verrucomicrobiota"), values=phylum_cols[1:6]) + theme(legend.position="none") + xlab("Feature index") + ylab("Component 1")

f=processedMilk$mode3 %>% mutate(Component_1=NPLS_milk$Fac[[3]][,1]) %>% ggplot(aes(x=timepoint,y=Component_1)) + geom_line() + geom_point() + xlab("Time point [days]") + ylab("Component 1")

# MilkMetab
g=processedMilkMetab$mode1 %>% mutate(Component_1=NPLS_milkMetab$Fac[[1]][,1]) %>% arrange(BMI.group,subject) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(BMI.group))) + geom_bar(stat="identity") + scale_fill_manual(name="BMI group", labels=c("Normal", "Overweight", "Obese"), values=BMI_cols) +theme(legend.position="none") + xlab("Subject index") + ylab("Component 1")

h=processedMilkMetab$mode2 %>% mutate(Component_1=NPLS_milkMetab$Fac[[2]][,1]) %>% arrange(Class,Metabolite) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(Class))) + geom_bar(stat="identity") + scale_fill_manual(name="Metabolite class", labels=c("Amino acids and derivatives", "Energy related", "Fatty acids and derivatives", "Food derived", "Microbially derived", "Oligosaccharides", "Pharmaceuticals", "Sugars"), values=phylum_cols) + theme(legend.position="none") + xlab("Feature index") + ylab("Component 1")

i=processedMilkMetab$mode3 %>% mutate(Component_1=NPLS_milkMetab$Fac[[3]][,1]) %>% ggplot(aes(x=timepoint,y=Component_1)) + geom_line() + geom_point() + xlab("Time point [days]") + ylab("Component 1")

ggarrange(a,b,c,d,e,f,g,h,i, nrow=3, ncol=3)
```

```{r check associations of the subject mode}

# 
# checkAssociations = function(loadings, comp=1){
#   a = Jakobsen2025$subjectMeta_BMI %>% mutate(loading = loadings) %>% ggplot(aes(x=loading,y=BMI)) + geom_point() + stat_cor()
#   b = Jakobsen2025$subjectMeta_BMI %>% mutate(loading = loadings) %>% ggplot(aes(x=as.factor(BMI.group),y=loading)) + geom_boxplot()
#   c = Jakobsen2025$subjectMeta_BMI %>% mutate(loading = loadings) %>% ggplot(aes(x=loading,y=whz.6m)) + geom_point() + stat_cor()
#   d = Jakobsen2025$subjectMeta_BMI %>% mutate(loading = loadings) %>% filter(C.section != "NA") %>% ggplot(aes(x=as.factor(C.section),y=loading)) + geom_boxplot() + stat_compare_means()
#   e = Jakobsen2025$subjectMeta_BMI %>% mutate(loading = loadings) %>% filter(Secretor != "NA") %>% ggplot(aes(x=as.factor(Secretor),y=loading)) + geom_boxplot() + stat_compare_means()
#   f = Jakobsen2025$subjectMeta_BMI %>% mutate(loading = loadings) %>% filter(Lewis != "NA") %>% ggplot(aes(x=as.factor(Lewis),y=loading)) + geom_boxplot() + stat_compare_means()
#   ggarrange(a,b,c,d,e,f)
# }
# 
# checkAssociations(model_bmiX_2$Fac[[1]][,1])
# checkAssociations(model_bmiX_2$Fac[[1]][,2])
# 
# checkAssociations(model_bmi25$Fac[[1]][,1])
# checkAssociations(model_bmi25$Fac[[1]][,2])
# 
# checkAssociations(model_bmi50$Fac[[1]][,1])
# checkAssociations(model_bmi50$Fac[[1]][,2])
# 
# checkAssociations(model_bmi75$Fac[[1]][,1])
# checkAssociations(model_bmi75$Fac[[1]][,2])

# NPLS
# checkAssociations(Jakobsen2025$homogenizedSubjectMetadata %>% left_join(NPLS_faeces_mode1 %>% mutate(subject = as.character(subject))) %>% select(loading) %>% pull())
# checkAssociations(Jakobsen2025$homogenizedSubjectMetadata %>% left_join(NPLS_milk_mode1 %>% mutate(subject = as.character(subject))) %>% select(loading) %>% pull())
# checkAssociations(Jakobsen2025$homogenizedSubjectMetadata %>% left_join(NPLS_milkMetab_mode1 %>% mutate(subject = as.character(subject))) %>% select(loading) %>% pull())
```

```{r test overall associations using PERMANOVA}
# set.seed(123)
# 
# testOverallAssociations = function(model){
#   mask = !is.na(Jakobsen2025$subjectMeta_BMI$C.section)
# 
#   # PERMANOVA for each metadata variable
#   adonis_birth <- adonis2(model$Fac[[1]][mask,] ~ Jakobsen2025$subjectMeta_BMI$C.section[mask], method="euclidean")
#   adonis_secretor <- adonis2(model$Fac[[1]] ~ Jakobsen2025$subjectMeta_BMI$Secretor, method="euclidean")
#   adonis_lewis <- adonis2(model$Fac[[1]] ~ Jakobsen2025$subjectMeta_BMI$Lewis, method="euclidean")
#   
#   # Print results
#   return(c(adonis_birth$`Pr(>F)`[1], adonis_secretor$`Pr(>F)`[1], adonis_lewis$`Pr(>F)`[1]))
# }
# 
# result = matrix(NA, nrow=6, ncol=3)
# result[1,] = testOverallAssociations(model_bmi25)
# result[2,] = testOverallAssociations(model_bmi50)
# result[3,] = testOverallAssociations(model_bmi75)
# result[4,] = testOverallAssociations(model_bmi90)
# result[5,] = testOverallAssociations(model_bmi95)
# result[6,] = testOverallAssociations(model_bmiX_2)
# 
# adjusted_result = matrix(p.adjust(result, "BH"), nrow=6, ncol=3)
```

```{r test associations per component}
# Import NPLS subject loadings
# NPLS_faeces_mode1 = read.csv("./Data/NPLS_faeces_bmi_mode1.csv", header=FALSE) %>% as_tibble()
# NPLS_milk_mode1 = read.csv("./Data/NPLS_milk_bmi_mode1.csv", header=FALSE) %>% as_tibble()
# NPLS_milkMetab_mode1 = read.csv("./Data/NPLS_milkMetab_bmi_mode1.csv", header=FALSE) %>% as_tibble()
# colnames(NPLS_faeces_mode1) = c("loading", "subject", "BMI.group")
# colnames(NPLS_milk_mode1) = c("loading", "subject", "BMI.group")
# colnames(NPLS_milkMetab_mode1) = c("loading", "subject", "BMI.group")
# 
# NPLS_faeces_bmi = list()
# NPLS_faeces_bmi$Fac = list()
# NPLS_faeces_bmi$Fac[[1]] = processedFaeces$mode1 %>% left_join(NPLS_faeces_mode1 %>% mutate(subject = as.character(subject))) %>% select(loading) %>% as.matrix()
# 
# NPLS_milk_bmi = list()
# NPLS_milk_bmi$Fac = list()
# NPLS_milk_bmi$Fac[[1]] = processedMilk$mode1 %>% left_join(NPLS_milk_mode1 %>% mutate(subject = as.character(subject))) %>% select(loading) %>% as.matrix()
# 
# NPLS_milkMetab_bmi = list()
# NPLS_milkMetab_bmi$Fac = list()
# NPLS_milkMetab_bmi$Fac[[1]] = processedMilkMetab$mode1 %>% left_join(NPLS_milkMetab_mode1 %>% mutate(subject = as.character(subject))) %>% select(loading) %>% as.matrix()


testAssociationsPerComponent = function(model){
  numComponents = ncol(model$Fac[[1]])
  
  result = matrix(NA, nrow=numComponents, ncol=5)
  
  for(i in 1:numComponents){
    result[i,1] = cor.test(model$Fac[[1]][,i], processedFaeces$mode1$BMI, method="spearman")$p.value
    result[i,2] = cor.test(model$Fac[[1]][,i], processedFaeces$mode1$whz.6m, method="spearman")$p.value
    
    mask = !is.na(processedFaeces$mode1$C.section)
    temp = model$Fac[[1]][mask,i]
    tempMeta = processedFaeces$mode1[mask,]
    mask1 = tempMeta$C.section == 1
    mask2 = tempMeta$C.section == 2
    
    result[i,3] = wilcox.test(temp[mask1], temp[mask2])$p.value
    
    mask1 = processedFaeces$mode1$Secretor == 0
    mask2 = processedFaeces$mode1$Secretor == 1
    result[i,4] = wilcox.test(model$Fac[[1]][mask1,i], model$Fac[[1]][mask2,i])$p.value
    
    mask1 = processedFaeces$mode1$Lewis == 0
    mask2 = processedFaeces$mode1$Lewis == 1
    result[i,5] = wilcox.test(model$Fac[[1]][mask1,i], model$Fac[[1]][mask2,i])$p.value
  }
  
  return(result)
}

result_NPLS1 = testAssociationsPerComponent(NPLS_faecal)
result_NPLS2 = testAssociationsPerComponent(NPLS_milk)
result_NPLS3 = testAssociationsPerComponent(NPLS_milkMetab)

result_bmi80 = testAssociationsPerComponent(model_bmi80)
result_bmi850 = testAssociationsPerComponent(model_bmi85)
result_bmi90 = testAssociationsPerComponent(model_bmi90)
result_bmi95 = testAssociationsPerComponent(model_bmi95)

result_bmi1 = testAssociationsPerComponent(model_ACMTF)

df = rbind(result_NPLS1, result_NPLS2, result_NPLS3, result_bmi80, result_bmi850, result_bmi90, result_bmi95, result_bmi1)

corrected_df = signif(matrix(p.adjust(df, "BH"), dim(df)), 2)
```

```{r pictures for age}
a=cbind(NPLS_faecal$Fac[[1]], processedFaeces$mode1$BMI) %>% as_tibble() %>% ggplot(aes(y=V1,x=V2)) + geom_point() + stat_cor() + ylab("Component 1") + xlab("ppBMI") + ggtitle("NPLS faeces")
b=cbind(NPLS_milk$Fac[[1]], processedFaeces$mode1$BMI) %>% as_tibble() %>% ggplot(aes(y=V1,x=V2)) + geom_point() + stat_cor() + ylab("Component 1") + xlab("ppBMI") + ggtitle("NPLS milk")
c=cbind(NPLS_milkMetab$Fac[[1]], processedFaeces$mode1$BMI) %>% as_tibble() %>% ggplot(aes(y=V1,x=V2)) + geom_point() + stat_cor() + ylab("Component 1") + xlab("ppBMI") + ggtitle("NPLS milkMetab")

d=cbind(model_bmi80$Fac[[1]][,1], processedFaeces$mode1$BMI) %>% as_tibble() %>% ggplot(aes(y=V1,x=V2)) + geom_point() + stat_cor() + ylab("Component 1") + xlab("ppBMI") + ggtitle("pi=0.80 (1)")
e=cbind(model_bmi80$Fac[[1]][,2], processedFaeces$mode1$BMI) %>% as_tibble() %>% ggplot(aes(y=V1,x=V2)) + geom_point() + stat_cor() + ylab("Component 2") + xlab("ppBMI") + ggtitle("pi=0.80 (2)")

f=cbind(model_bmi85$Fac[[1]][,1], processedFaeces$mode1$BMI) %>% as_tibble() %>% ggplot(aes(y=V1,x=V2)) + geom_point() + stat_cor() + ylab("Component 1") + xlab("ppBMI") + ggtitle("pi=0.85 (1)")
g=cbind(model_bmi85$Fac[[1]][,2], processedFaeces$mode1$BMI) %>% as_tibble() %>% ggplot(aes(y=V1,x=V2)) + geom_point() + stat_cor() + ylab("Component 2") + xlab("ppBMI") + ggtitle("pi=0.85 (2)")

h=cbind(model_bmi90$Fac[[1]], processedFaeces$mode1$BMI) %>% as_tibble() %>% ggplot(aes(y=V1,x=V2)) + geom_point() + stat_cor() + ylab("Component 1") + xlab("ppBMI") + ggtitle("pi=0.90 (1)")

i=cbind(model_bmi95$Fac[[1]], processedFaeces$mode1$BMI) %>% as_tibble() %>% ggplot(aes(y=V1,x=V2)) + geom_point() + stat_cor() + ylab("Component 1") + xlab("ppBMI") + ggtitle("pi=0.95 (1)")

j=cbind(model_ACMTF$Fac[[1]], processedFaeces$mode1$BMI) %>% as_tibble() %>% ggplot(aes(y=V1,x=V2)) + geom_point() + stat_cor() + ylab("Component 1") + xlab("ppBMI") + ggtitle("pi=1 (1)")

ggarrange(a,b,c,d,e,f,g,h,i,j)
```

```{r pictures for age 2}
a=cbind(NPLS_faecal$Fac[[1]], processedFaeces$mode1$Secretor) %>% as_tibble() %>% ggplot(aes(y=V1,x=as.factor(V2))) + geom_boxplot() + stat_compare_means(comparisons=list(c("0","1")),label="p.signif") + ylab("Component 1") + xlab("Secretor status") + ggtitle("NPLS faeces")
b=cbind(NPLS_milk$Fac[[1]], processedFaeces$mode1$Secretor) %>% as_tibble() %>% ggplot(aes(y=V1,x=as.factor(V2))) + geom_boxplot() + stat_compare_means(comparisons=list(c("0","1")),label="p.signif") + ylab("Component 1") + xlab("Secretor status") + ggtitle("NPLS milk")
c=cbind(NPLS_milkMetab$Fac[[1]], processedFaeces$mode1$Secretor) %>% as_tibble() %>% ggplot(aes(y=V1,x=as.factor(V2))) + geom_boxplot() + stat_compare_means(comparisons=list(c("0","1")),label="p.signif") + ylab("Component 1") + xlab("Secretor status") + ggtitle("NPLS milkMetab")

d=cbind(model_bmi80$Fac[[1]][,1], processedFaeces$mode1$Secretor) %>% as_tibble() %>% ggplot(aes(y=V1,x=as.factor(V2))) + geom_boxplot() + stat_compare_means(comparisons=list(c("0","1")),label="p.signif") + ylab("Component 1") + xlab("Secretor status") + ggtitle("pi=0.80 (1)")
e=cbind(model_bmi80$Fac[[1]][,2], processedFaeces$mode1$Secretor) %>% as_tibble() %>% ggplot(aes(y=V1,x=as.factor(V2))) + geom_boxplot() + stat_compare_means(comparisons=list(c("0","1")),label="p.signif") + ylab("Component 2") + xlab("Secretor status") + ggtitle("pi=0.80 (2)")

f=cbind(model_bmi85$Fac[[1]][,1], processedFaeces$mode1$Secretor) %>% as_tibble() %>% ggplot(aes(y=V1,x=as.factor(V2))) + geom_boxplot() + stat_compare_means(comparisons=list(c("0","1")),label="p.signif") + ylab("Component 1") + xlab("Secretor status") + ggtitle("pi=0.85 (1)")
g=cbind(model_bmi85$Fac[[1]][,2], processedFaeces$mode1$Secretor) %>% as_tibble() %>% ggplot(aes(y=V1,x=as.factor(V2))) + geom_boxplot() + stat_compare_means(comparisons=list(c("0","1")),label="p.signif") + ylab("Component 2") + xlab("Secretor status") + ggtitle("pi=0.85 (2)")

h=cbind(model_bmi90$Fac[[1]], processedFaeces$mode1$Secretor) %>% as_tibble() %>% ggplot(aes(y=V1,x=as.factor(V2))) + geom_boxplot() + stat_compare_means(comparisons=list(c("0","1")),label="p.signif") + ylab("Component 1") + xlab("Secretor status") + ggtitle("pi=0.90 (1)")

i=cbind(model_bmi95$Fac[[1]], processedFaeces$mode1$Secretor) %>% as_tibble() %>% ggplot(aes(y=V1,x=as.factor(V2))) + geom_boxplot() + stat_compare_means(comparisons=list(c("0","1")),label="p.signif") + ylab("Component 1") + xlab("Secretor status") + ggtitle("pi=0.95 (1)")

j=cbind(model_ACMTF$Fac[[1]], processedFaeces$mode1$Secretor) %>% as_tibble() %>% ggplot(aes(y=V1,x=as.factor(V2))) + geom_boxplot() + stat_compare_means(comparisons=list(c("0","1")),label="p.signif") + ylab("Component 1") + xlab("Secretor status") + ggtitle("pi=1 (1)")

ggarrange(a,b,c,d,e,f,g,h,i,j)
```

```{r compare Y predictions}
cbind(model_bmi80$Yhat, model_bmi85$Yhat, model_bmi90$Yhat, model_bmi95$Yhat, Ynorm) %>%
  as_tibble() %>%
  pivot_longer(-Ynorm) %>%
  ggplot(aes(x=Ynorm,y=value,col=as.factor(name))) +
  geom_point() +
  xlab("Centered and normalized maternal ppBMI") +
  ylab("Yhat") +
  scale_color_manual(name="Model", labels=c("ACMTF-R (pi=0.80)", "ACMTF-R (pi=0.85)", "ACMTF-R (pi=0.90)", "ACMTF-R (pi=0.95)"), values=hue_pal()(5))
```

```{r comparisons of factors}
tucker_congruence <- function(x, y, ignore_sign = TRUE) {
  # x, y are numeric vectors of the same length
  if (length(x) != length(y)) stop("Vectors must have same length")
  
  numerator <- sum(x * y)
  denom_x   <- sqrt(sum(x^2))
  denom_y   <- sqrt(sum(y^2))
  
  if (denom_x < 1e-15 || denom_y < 1e-15) {
    # handle near-zero norms
    return(NA_real_)
  }
  
  phi <- numerator / (denom_x * denom_y)
  
  if (ignore_sign) {
    # Return the maximum of + or - correlation
    return(max(phi, -phi))
  } else {
    # Keep sign
    return(phi)
  }
}
```

```{r plot lambdas per model}
methods = c("pi=0.80 (1)","pi=0.80 (2)", "pi=0.85 (1)", "pi=0.85 (2)", "pi=0.90 (1)","pi=0.95 (1)","pi=1 (1)")

cbind(model_bmi80$Fac[[8]], model_bmi85$Fac[[8]], model_bmi90$Fac[[8]], model_bmi95$Fac[[8]], model_ACMTF$Fac[[8]]) %>%
  t() %>%
  as_tibble() %>%
  mutate(model=1:7) %>%
  pivot_longer(-model) %>% 
  mutate(value=abs(value)) %>%
  ggplot(aes(x=as.factor(model),y=value,fill=as.factor(name))) +
  geom_bar(stat="identity",position=position_dodge(),col="black") +
  xlab("Model + component") +
  ylab(expression(lambda)) +
  scale_x_discrete(name="", labels=methods) +
  scale_fill_manual(name="Block", labels=c("Infant faecal microbiome", "HM microbiome", "HM metabolome"), values=hue_pal()(3)) +
  theme(legend.position="none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text=element_text(size=16))
```

```{r tucker congruence for subject loadings}
df = cbind(NPLS_faecal$Fac[[1]], NPLS_milk$Fac[[1]], NPLS_milkMetab$Fac[[1]], model_bmi80$Fac[[1]], model_bmi85$Fac[[1]], model_bmi90$Fac[[1]], model_bmi95$Fac[[1]], model_ACMTF$Fac[[1]])

congruence_matrix = matrix(NA, ncol=ncol(df), nrow=ncol(df))

for(i in 1:ncol(df)){
  for(j in 1:ncol(df)){
    congruence_matrix[i,j] = tucker_congruence(df[,i], df[,j])
  }
}

methods = c("NPLS Faecal (1)", "NPLS Milk (1)", "NPLS MilkMetab (1)", "pi=0.80 (1)","pi=0.80 (2)","pi=0.85 (1)","pi=0.85 (2)", "pi=0.90 (1)", "pi=0.95 (1)", "pi=1 (1)")

congruence_matrix %>%
  as_tibble() %>%
  mutate(index=1:length(methods)) %>%
  pivot_longer(-index) %>%
  mutate(name = factor(name, levels=paste0("V",1:length(methods)))) %>%
  ggplot(aes(x=as.factor(index),y=name,fill=value)) +
  geom_tile(col="black") +
  # geom_text(aes(label=round(value,2))) +
  scale_y_discrete(name="", labels=methods) +
  scale_x_discrete(name="",labels=methods) +
  scale_fill_gradient(limits=c(0,1.01)) +
  theme(legend.position="na", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text=element_text(size=16))
```

```{r tucker congruence for faecal microbiome}
# NPLS_faeces_mode2 = read.csv("./Data/NPLS_milk_bmi_mode2.csv", header=FALSE) %>% as_tibble()

df = cbind(NPLS_faecal$Fac[[2]], model_bmi80$Fac[[2]], model_bmi85$Fac[[2]], model_bmi90$Fac[[2]], model_bmi95$Fac[[2]], model_ACMTF$Fac[[2]])

congruence_matrix = matrix(NA, ncol=ncol(df), nrow=ncol(df))

for(i in 1:ncol(df)){
  for(j in 1:ncol(df)){
    congruence_matrix[i,j] = tucker_congruence(df[,i], df[,j])
  }
}

methods = c("NPLS Faecal (1)", "pi=0.80 (1)","pi=0.80 (2)","pi=0.85 (1)","pi=0.85 (2)", "pi=0.90 (1)", "pi=0.95 (1)", "pi=1 (1)")

congruence_matrix %>%
  as_tibble() %>%
  mutate(index=1:length(methods)) %>%
  pivot_longer(-index) %>%
  mutate(name = factor(name, levels=paste0("V",1:length(methods)))) %>%
  ggplot(aes(x=as.factor(index),y=name,fill=value)) +
  geom_tile(col="black") +
  # geom_text(aes(label=round(value,2))) +
  scale_y_discrete(name="", labels=methods) +
  scale_x_discrete(name="",labels=methods) +
  scale_fill_gradient(limits=c(0,1.01)) +
  theme(legend.position="na", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text=element_text(size=16))
```

```{r tucker congruence for HM microbiome}
# NPLS_faeces_mode2 = read.csv("./Data/NPLS_milk_bmi_mode2.csv", header=FALSE) %>% as_tibble()

df = cbind(NPLS_milk$Fac[[2]], model_bmi80$Fac[[4]], model_bmi85$Fac[[4]], model_bmi90$Fac[[4]], model_bmi95$Fac[[4]], model_ACMTF$Fac[[4]])

congruence_matrix = matrix(NA, ncol=ncol(df), nrow=ncol(df))

for(i in 1:ncol(df)){
  for(j in 1:ncol(df)){
    congruence_matrix[i,j] = tucker_congruence(df[,i], df[,j])
  }
}

methods = c("NPLS Milk (1)", "pi=0.80 (1)","pi=0.80 (2)","pi=0.85 (1)","pi=0.85 (2)", "pi=0.90 (1)", "pi=0.95 (1)", "pi=1 (1)")

congruence_matrix %>%
  as_tibble() %>%
  mutate(index=1:length(methods)) %>%
  pivot_longer(-index) %>%
  mutate(name = factor(name, levels=paste0("V",1:length(methods)))) %>%
  ggplot(aes(x=as.factor(index),y=name,fill=value)) +
  geom_tile(col="black") +
  # geom_text(aes(label=round(value,2))) +
  scale_y_discrete(name="", labels=methods) +
  scale_x_discrete(name="",labels=methods) +
  scale_fill_gradient(limits=c(0,1.01)) +
  theme(legend.position="na", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text=element_text(size=16))
```

```{r tucker congruence for HM metabolome}
# NPLS_faeces_mode2 = read.csv("./Data/NPLS_milk_bmi_mode2.csv", header=FALSE) %>% as_tibble()

df = cbind(NPLS_milkMetab$Fac[[2]], model_bmi80$Fac[[6]], model_bmi85$Fac[[6]], model_bmi90$Fac[[6]], model_bmi95$Fac[[6]], model_ACMTF$Fac[[6]])

congruence_matrix = matrix(NA, ncol=ncol(df), nrow=ncol(df))

for(i in 1:ncol(df)){
  for(j in 1:ncol(df)){
    congruence_matrix[i,j] = tucker_congruence(df[,i], df[,j])
  }
}

methods = c("NPLS Metab (1)", "pi=0.80 (1)","pi=0.80 (2)","pi=0.85 (1)","pi=0.85 (2)", "pi=0.90 (1)", "pi=0.95 (1)", "pi=1 (1)")

congruence_matrix %>%
  as_tibble() %>%
  mutate(index=1:length(methods)) %>%
  pivot_longer(-index) %>%
  mutate(name = factor(name, levels=paste0("V",1:length(methods)))) %>%
  ggplot(aes(x=as.factor(index),y=name,fill=value)) +
  geom_tile(col="black") +
  # geom_text(aes(label=round(value,2))) +
  scale_y_discrete(name="", labels=methods) +
  scale_x_discrete(name="",labels=methods) +
  scale_fill_gradient(limits=c(0,1.01)) +
  theme(legend.position="na", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text=element_text(size=16))
```
```{r further examine the subject loadings}
comparisons = list(c("0","1"))

# NPLS
processedFaeces$mode1 %>%
  mutate(Component_1=NPLS_faecal$Fac[[1]][,1]) %>%
  ggplot(aes(x=as.factor(Secretor),y=Component_1,fill=as.factor(Secretor))) +
  geom_boxplot() +
  stat_compare_means(comparisons=comparisons,label="p.signif") +
  xlab("Secretor status") +
  scale_x_discrete(labels=c("Se-", "Se+")) +
  ylab("Component 1") +
  scale_fill_manual(name="Secretor status", labels=c("Se-", "Se+"), values=hue_pal()(2)) +
  ggtitle("NPLS faecal")

processedMilk$mode1 %>%
  mutate(Component_1=NPLS_milk$Fac[[1]][,1]) %>%
  ggplot(aes(x=as.factor(Secretor),y=Component_1,fill=as.factor(Secretor))) +
  geom_boxplot() +
  stat_compare_means(comparisons=comparisons,label="p.signif") +
  xlab("Secretor status") +
  scale_x_discrete(labels=c("Se-", "Se+")) +
  ylab("Component 1") +
  scale_fill_manual(name="Secretor status", labels=c("Se-", "Se+"), values=hue_pal()(2)) +
  ggtitle("NPLS milk")

processedMilkMetab$mode1 %>%
  mutate(Component_1=NPLS_milkMetab$Fac[[1]][,1]) %>%
  ggplot(aes(x=as.factor(Secretor),y=Component_1,fill=as.factor(Secretor))) +
  geom_boxplot() +
  stat_compare_means(comparisons=comparisons,label="p.signif") +
  xlab("Secretor status") +
  scale_x_discrete(labels=c("Se-", "Se+")) +
  ylab("Component 1") +
  scale_fill_manual(name="Secretor status", labels=c("Se-", "Se+"), values=hue_pal()(2)) +
  ggtitle("NPLS milkMetab")

# ACMTF-R
processedFaeces$mode1 %>%
  mutate(Component_1=model_bmi80$Fac[[1]][,1]) %>%
  ggplot(aes(x=as.factor(Secretor),y=Component_1,fill=as.factor(Secretor))) +
  geom_boxplot() +
  stat_compare_means(comparisons=comparisons,label="p.signif") +
  xlab("Secretor status") +
  scale_x_discrete(labels=c("Se-", "Se+")) +
  ylab("Component 1") +
  scale_fill_manual(name="Secretor status", labels=c("Se-", "Se+"), values=hue_pal()(2)) +
  ggtitle("ACMTF-R pi=0.80 (1)")

processedFaeces$mode1 %>%
  mutate(Component_2=model_bmi80$Fac[[1]][,2]) %>%
  ggplot(aes(x=as.factor(Secretor),y=Component_2,fill=as.factor(Secretor))) +
  geom_boxplot() +
  stat_compare_means(comparisons=comparisons,label="p.signif") +
  xlab("Secretor status") +
  scale_x_discrete(labels=c("Se-", "Se+")) +
  ylab("Component 2") +
  scale_fill_manual(name="Secretor status", labels=c("Se-", "Se+"), values=hue_pal()(2)) +
  ggtitle("ACMTF-R pi=0.80 (2)")

# ACMTF
processedFaeces$mode1 %>%
  mutate(Component_1=model_ACMTF$Fac[[1]][,1]) %>%
  ggplot(aes(x=as.factor(Secretor),y=Component_1,fill=as.factor(Secretor))) +
  geom_boxplot() +
  stat_compare_means(comparisons=comparisons,label="p.signif") +
  xlab("Secretor status") +
  scale_x_discrete(labels=c("Se-", "Se+")) +
  ylab("Component 1") +
  scale_fill_manual(name="Secretor status", labels=c("Se-", "Se+"), values=hue_pal()(2)) +
  ggtitle("ACMTF")

adonis2(NPLS_faecal$Fac[[1]] ~ BMI.group + C.section + Secretor + Lewis, data=processedFaeces$mode1, method="euclidean", by="margin", permutations=9999, na.action=na.omit)
adonis2(NPLS_milk$Fac[[1]] ~ BMI.group + C.section + Secretor + Lewis, data=processedMilk$mode1, method="euclidean", by="margin", permutations=9999, na.action=na.omit)
adonis2(NPLS_milkMetab$Fac[[1]] ~ BMI.group + C.section + Secretor + Lewis, data=processedMilkMetab$mode1, method="euclidean", by="margin", permutations=9999, na.action=na.omit)
adonis2(model_bmi80$Fac[[1]] ~ BMI.group + C.section + Secretor + Lewis, data=processedFaeces$mode1, method="euclidean", by="margin", permutations=9999, na.action=na.omit)
adonis2(model_bmi85$Fac[[1]] ~ BMI.group + C.section + Secretor + Lewis, data=processedFaeces$mode1, method="euclidean", by="margin", permutations=9999, na.action=na.omit)
adonis2(model_bmi90$Fac[[1]] ~ BMI.group + C.section + Secretor + Lewis, data=processedFaeces$mode1, method="euclidean", by="margin", permutations=9999, na.action=na.omit)
adonis2(model_bmi95$Fac[[1]] ~ BMI.group + C.section + Secretor + Lewis, data=processedFaeces$mode1, method="euclidean", by="margin", permutations=9999, na.action=na.omit)
adonis2(model_ACMTF$Fac[[1]] ~ BMI.group + C.section + Secretor + Lewis, data=processedFaeces$mode1, method="euclidean", by="margin", permutations=9999, na.action=na.omit)
```

```{r further examine the loadings for metabolomics}
# NPLS
temp = processedMilkMetab$mode2 %>%
  mutate(Component_1=NPLS_milkMetab$Fac[[2]][,1]) %>%
  arrange(desc(Component_1)) %>%
  mutate(index=1:nrow(.))

a = temp %>%
  ggplot(aes(x=Component_1,y=as.factor(index),fill=as.factor(Class))) +
  geom_bar(stat="identity") +
  scale_y_discrete(labels=temp$Metabolite) +
  ggtitle("NPLS")

# ACMTF
temp = processedMilkMetab$mode2 %>%
  mutate(Component_1=model_ACMTF$Fac[[6]][,1]) %>%
  arrange(desc(Component_1)) %>%
  mutate(index=1:nrow(.))

b = temp %>%
  ggplot(aes(x=Component_1,y=as.factor(index),fill=as.factor(Class))) +
  geom_bar(stat="identity") +
  scale_y_discrete(labels=temp$Metabolite) +
  ggtitle("ACMTF")

# ACMTF-R pi=0.8
temp = processedMilkMetab$mode2 %>%
  mutate(Component_1=model_bmi80$Fac[[6]][,1]) %>%
  arrange(desc(Component_1)) %>%
  mutate(index=1:nrow(.))

c = temp %>%
  ggplot(aes(x=Component_1,y=as.factor(index),fill=as.factor(Class))) +
  geom_bar(stat="identity") +
  scale_y_discrete(labels=temp$Metabolite) +
  ggtitle("ACMTF-R pi=0.80 (1)")

temp = processedMilkMetab$mode2 %>%
  mutate(Component_2=model_bmi80$Fac[[6]][,2]) %>%
  arrange(desc(Component_2)) %>%
  mutate(index=1:nrow(.))

d = temp %>%
  ggplot(aes(x=Component_2,y=as.factor(index),fill=as.factor(Class))) +
  geom_bar(stat="identity") +
  scale_y_discrete(labels=temp$Metabolite) +
  ggtitle("ACMTF-R pi=0.80 (2)")

ggarrange(a,b,c,d, common.legend=TRUE)
```

```{r plot the associations}
threshold = 0

# HM metabolome
df = Jakobsen2025$milk_metabolites %>% mutate(Component_1 = model_bmi95$Fac[[6]][,1])
colnames(df) = c("Metabolite", "CAS", "Component_1")

metaboliteCategories = read.csv("./Data/Metabolite_categories.txt", sep="\t") %>% as_tibble()
metaboliteCategories = metaboliteCategories %>% mutate(Metabolite = vctrs::vec_as_names(Metabolite, repair="universal_quiet"))
df = df %>% left_join(metaboliteCategories)

## Add mismatches by hand
df[df$Metabolite == "X2.Aminobutyrate","Class"] = "Amino acids and derivatives"
df[df$Metabolite == "X2.Fucosyllactose","Class"] = "Oligosaccharides"
df[df$Metabolite == "X2.Hydroxybutyrate","Class"] = "Amino acids and derivatives"
df[df$Metabolite == "X2.Oxoglutarate","Class"] = "Energy related"
df[df$Metabolite == "X3.Fucosyllactose","Class"] = "Oligosaccharides"
df[df$Metabolite == "X3SL.partial","Class"] = "Oligosaccharides"
df[df$Metabolite == "X6SL.partial","Class"] = "Oligosaccharides"
df[df$Metabolite == "Methionine","Class"] = "Amino acids and derivatives"

temp = df %>% arrange(Component_1) %>% filter(abs(Component_1) >= threshold) %>% mutate(index=1:nrow(.))
a = temp %>% ggplot(aes(x=Component_1,y=as.factor(index),fill=as.factor(Class))) + geom_bar_pattern(stat="identity", pattern_angle=45, pattern_density=0.05, pattern_spacing=0.02, pattern_key_scale_factor=0.6, col="black", pattern_fill="black") + ylab("Metabolite") + xlab("Component 1") + scale_y_discrete(labels=temp$Metabolite) + scale_fill_manual(name="Metabolite class", labels=c("Amino acids and derivatives", "Energy related", "Fatty acids and derivatives", "Food derived", "Microbially derived", "Oligosaccharides", "Pharmaceuticals", "Sugars"), values=phylum_cols) + theme(legend.position="none") + ylab("")


####

# Milk microbiome
df = Jakobsen2025$milk_microbiome_taxonomy %>% mutate(Component_1 = model_bmi95$Fac[[4]][,1]) %>% select(V3,V7,V8,Component_1)
colnames(df) = c("Phylum", "Genus", "Species", "Component_1")
temp = df %>% 
  arrange(Component_1) %>% 
  mutate(Genus = gsub("g__", "", Genus), Species = gsub("s__", "", Species)) %>% 
  mutate(Species = str_split_fixed(Species, "_", 2)[,2]) %>% 
  mutate(dplyr::across(.cols = Species, .fns = ~ dplyr::if_else(stringr::str_detect(.x, "sp."), "", .x))) %>%
  mutate(dplyr::across(.cols = Species, .fns = ~ dplyr::if_else(stringr::str_detect(.x, "organism"), "", .x))) %>%
  mutate(dplyr::across(.cols = Species, .fns = ~ dplyr::if_else(stringr::str_detect(.x, "bacterium"), "", .x)))

temp[temp$Species == "", "Species"] = "sp."
temp$name = paste0(temp$Genus, " ", temp$Species)
temp[temp$name == " sp.", "name"] = "Unclassified"
temp = temp %>% filter(abs(Component_1) >= threshold) %>% arrange(Component_1) %>% mutate(index=1:nrow(.))

b=temp %>% ggplot(aes(x=Component_1,y=as.factor(index),fill=as.factor(Phylum))) + geom_bar(stat="identity", col="black") + ylab("zOTU") + xlab("Component 1") + scale_y_discrete(labels=temp$name) + scale_fill_manual(name="Phylum", labels=c("Actinobacteriota", "Bacteroidota", "Firmicutes", "Proteobacteria"), values=phylum_cols[-3]) + theme(legend.position="none", axis.text.y = element_text(face="italic")) + ylab("")

# Faecal microbiome
df = Jakobsen2025$faecal_microbiome_taxonomy %>% mutate(Component_1 = model_bmi95$Fac[[2]][,1]) %>% select(V3,V7,V8,Component_1)
colnames(df) = c("Phylum", "Genus", "Species", "Component_1")
temp = df %>% 
  arrange(Component_1) %>% 
  mutate(Genus = gsub("g__", "", Genus), Species = gsub("s__", "", Species)) %>% 
  mutate(Species = str_split_fixed(Species, "_", 2)[,2]) %>% 
  mutate(dplyr::across(.cols = Species, .fns = ~ dplyr::if_else(stringr::str_detect(.x, "sp."), "", .x))) %>%
  mutate(dplyr::across(.cols = Species, .fns = ~ dplyr::if_else(stringr::str_detect(.x, "organism"), "", .x))) %>%
  mutate(dplyr::across(.cols = Species, .fns = ~ dplyr::if_else(stringr::str_detect(.x, "bacterium"), "", .x)))

temp[temp$Species == "", "Species"] = "sp."
temp$name = paste0(temp$Genus, " ", temp$Species)
temp[temp$name == " sp.", "name"] = "Unclassified"
temp = temp %>% filter(abs(Component_1) >= threshold) %>% arrange(Component_1) %>% mutate(index=1:nrow(.))

c=temp %>% ggplot(aes(x=Component_1,y=as.factor(index),fill=as.factor(Phylum))) + geom_bar(stat="identity", col="black") + ylab("zOTU") + xlab("Component 1") + scale_y_discrete(labels=temp$name) + scale_fill_manual(name="Phylum", labels=c("Actinobacteriota", "Bacteroidota", "Firmicutes", "Proteobacteria"), values=phylum_cols[-3]) + theme(legend.position="none", axis.text.y = element_text(face="italic")) + ylab("")

a
b
c
```
```{r loading loading plots}

# Faeces
NPLS_faeces = read.csv("./Data/NPLS_faeces_bmi_mode2.csv",header=FALSE) %>% as_tibble()
colnames(NPLS_faeces) = c("NPLS", "OTU", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")
ACMTFR_faeces = cbind(-1*model_bmi95$Fac[[2]][,1], Jakobsen2025$faecal_microbiome_taxonomy) %>% as_tibble()
colnames(ACMTFR_faeces) = c("ACMTFR", "OTU", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")

df = ACMTFR_faeces %>% left_join(NPLS_faeces)
  
temp = df %>% 
mutate(Genus = gsub("g__", "", Genus), Species = gsub("s__", "", Species)) %>% 
mutate(Species = str_split_fixed(Species, "_", 2)[,2]) %>% 
mutate(dplyr::across(.cols = Species, .fns = ~ dplyr::if_else(stringr::str_detect(.x, "sp."), "", .x))) %>%
mutate(dplyr::across(.cols = Species, .fns = ~ dplyr::if_else(stringr::str_detect(.x, "organism"), "", .x))) %>%
mutate(dplyr::across(.cols = Species, .fns = ~ dplyr::if_else(stringr::str_detect(.x, "bacterium"), "", .x)))

temp[temp$Species == "", "Species"] = "sp."
temp$name = paste0(temp$Genus, " ", temp$Species)
temp[temp$name == " sp.", "name"] = "Unclassified"

a = temp %>%
  ggplot(aes(x=ACMTFR,y=NPLS,col=as.factor(Phylum),label=name)) +
  geom_point() +
  # geom_text_repel(max.overlaps=10) +
  theme(legend.position="na")

# Milk
NPLS_milk = read.csv("./Data/NPLS_milk_bmi_mode2.csv",header=FALSE) %>% as_tibble()
colnames(NPLS_milk) = c("NPLS", "OTU", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")
ACMTFR_milk = cbind(model_bmi95$Fac[[4]][,1], Jakobsen2025$milk_microbiome_taxonomy) %>% as_tibble()
colnames(ACMTFR_milk) = c("ACMTFR", "OTU", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")

df = ACMTFR_milk %>% left_join(NPLS_milk)
  
temp = df %>% 
mutate(Genus = gsub("g__", "", Genus), Species = gsub("s__", "", Species)) %>% 
mutate(Species = str_split_fixed(Species, "_", 2)[,2]) %>% 
mutate(dplyr::across(.cols = Species, .fns = ~ dplyr::if_else(stringr::str_detect(.x, "sp."), "", .x))) %>%
mutate(dplyr::across(.cols = Species, .fns = ~ dplyr::if_else(stringr::str_detect(.x, "organism"), "", .x))) %>%
mutate(dplyr::across(.cols = Species, .fns = ~ dplyr::if_else(stringr::str_detect(.x, "bacterium"), "", .x)))

temp[temp$Species == "", "Species"] = "sp."
temp$name = paste0(temp$Genus, " ", temp$Species)
temp[temp$name == " sp.", "name"] = "Unclassified"

b = temp %>%
  ggplot(aes(x=ACMTFR,y=NPLS,col=as.factor(Phylum),label=name)) +
  geom_point() +
  # geom_text_repel(max.overlaps=10) +
  theme(legend.position="na")

# Milk metab
NPLS_milkMetab = read.csv("./Data/NPLS_milkMetab_bmi_mode2.csv", header=FALSE) %>% as_tibble()
colnames(NPLS_milkMetab) = c("NPLS", "Metabolite", "CAS")
ACMTFR_milkMetab = cbind(-1*model_bmi95$Fac[[6]][,1], Jakobsen2025$milk_metabolites) %>% as_tibble()
colnames(ACMTFR_milkMetab) = c("ACMTFR", "Metabolite", "CAS")

df = ACMTFR_milkMetab %>%
  left_join(NPLS_milkMetab, by="Metabolite") %>%
  left_join(metaboliteCategories)

## Add mismatches by hand
df[df$Metabolite == "X2.Aminobutyrate","Class"] = "Amino acids and derivatives"
df[df$Metabolite == "X2.Fucosyllactose","Class"] = "Oligosaccharides"
df[df$Metabolite == "X2.Hydroxybutyrate","Class"] = "Amino acids and derivatives"
df[df$Metabolite == "X2.Oxoglutarate","Class"] = "Energy related"
df[df$Metabolite == "X3.Fucosyllactose","Class"] = "Oligosaccharides"
df[df$Metabolite == "X3SL.partial","Class"] = "Oligosaccharides"
df[df$Metabolite == "X6SL.partial","Class"] = "Oligosaccharides"
df[df$Metabolite == "Methionine","Class"] = "Amino acids and derivatives"

c = df %>% 
  ggplot(aes(x=ACMTFR,y=NPLS,col=as.factor(Class),label=Metabolite)) +
  geom_point() +
  # geom_text_repel(max.overlaps=10) +
  theme(legend.position="na")

ggarrange(a,b,c, nrow=1)
```
```{r varExp plot}
# Load required packages
library(tidyverse)
library(ggpattern)
library(scales)  # for trans_new()

# 1. Define a custom transformation for a "broken" y axis.
#    Values <= breakpoint are unchanged; values > breakpoint are compressed.
#    Here we choose breakpoint = 15 and a factor = 5.67 so that 100 maps near 30.
broken_trans <- function(breakpoint = 15, factor = 5.67) {
    trans_new(
        name = paste0("broken_", breakpoint, "_", factor),
        transform = function(x) {
            ifelse(x <= breakpoint, x, breakpoint + (x - breakpoint) / factor)
        },
        inverse = function(x) {
            ifelse(x <= breakpoint, x, breakpoint + (x - breakpoint) * factor)
        },
        domain = c(0, Inf)
    )
}

# 2. Create the original 3x3 data matrix and assign column names.
df <- matrix(
    c(5.77, 5.31, 4.32,    # Block 1: values for NPLS, ACMTF, ACMTF-R
      12.85, 10.96, 5.90,    # Block 2
      1.08, 0.86, 1.15),    # Block 3
    nrow = 3, byrow = FALSE
)
colnames(df) <- c("NPLS", "ACMTF", "ACMTF-R")

# 3. Tidy the original data.
#    Create a column "orig_block" to track the original block number ("1", "2", or "3").
df_tidy <- as_tibble(df) %>%
    mutate(orig_block = as.character(1:3)) %>%  # original blocks
    pivot_longer(
        cols = -orig_block,
        names_to  = "method",
        values_to = "value"
    ) %>%
    # Here, the x-axis "block" is the original block.
    mutate(block = orig_block)

# 4. Add the extra block "Y" rows.
#    For NPLS: one extra row per block with the provided values.
df_extra_npls <- tibble(
    method     = "NPLS",
    block      = "Y",               # extra block
    value      = c(12.30, 11.22, 31.04),
    orig_block = c("1", "2", "3")    # so we know which NPLS facet it belongs to
)

#    For ACMTF-R: add one extra row.
df_extra_acmtfr <- tibble(
    method = "ACMTF-R",
    block  = "Y",
    value  = 98.86
)

#    For ACMTF: add one extra row with a value of 0.53.
df_extra_acmtf <- tibble(
    method = "ACMTF",
    block  = "Y",
    value  = 7.13
)

# 5. Combine all the data.
#    Specify the x-axis factor levels so that "Y" appears as the fourth level.
df_all <- bind_rows(df_tidy, df_extra_npls, df_extra_acmtfr, df_extra_acmtf) %>%
    mutate(block = factor(block, levels = c("1", "2", "3", "Y")))

# 6. Define custom x-axis labels.
#    Blocks 13 get descriptive labels; block "Y" is renamed to "Infant\n6-month\nWHZ".
block_labels <- c(
    "1" = "Infant\nfaecal\nmicrobiome",
    "2" = "Mother\nmilk\nmicrobiome",
    "3" = "Mother\nmilk\nmetabolome",
    "Y" = "Maternal\nppBMI"
)

# 7. Create a facet grouping variable.
#    For NPLS, each facet is labeled with the method and the corresponding original block label,
#    so that each NPLS facet only shows its own used blocks.
#    For ACMTF and ACMTF-R, the facet label remains simply the method name.
df_all <- df_all %>%
    mutate(facet_group = case_when(
        method == "NPLS" ~ paste("NPLS:", block_labels[orig_block]),
        TRUE           ~ method
    ))

# 8. Create the plot.
#    Here we use facet_grid with free x scales and free space so that the widths
#    of the facets are proportional to the number of x categories they display.
p <- ggplot(df_all, aes(x = block, y = value, fill = method)) +
  geom_col(position = position_dodge(width = 0.9), color = "black") +
  facet_grid(. ~ facet_group, scales = "free_x", space = "free_x") +
  scale_fill_manual(
    values = c("NPLS"    = "grey",
               "ACMTF"   = "grey",
               "ACMTF-R" = "grey")
  ) +
  scale_x_discrete(labels = block_labels, drop = TRUE) +
  xlab("") +
  ylab("Variance explained (%)") +
  # theme_bw(base_size = 12) +
  theme(legend.position = "none") +
  scale_y_continuous(
    limits = c(0, 100),
    trans  = broken_trans(breakpoint = 15, factor = 5.67),
    # Specify breaks in the original units.
    breaks = c(0, 5, 10, 15, 30, 50, 70, 90, 100),
    labels = c(0, 5, 10, 15, 30, 50, 70, 90, 100)
  )

p
``` 
