---
title: "20241203_ACMTF_validation"
author: "G.R. van der Ploeg"
date: "2024-12-03"
output: html_document
---

# Preamble
```{r setup, include=FALSE}
library(rTensor)
library(CMTFtoolbox)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(scales)
library(clue)
```

```{r define FMS}

calculateFMS <- function(modelFac, realFac, numComponents) {
  
  # Project modelFac onto realFac to make sure components are not split
  # modelFac = modelFac %*% pracma::pinv(t(modelFac) %*% modelFac) %*% t(modelFac) %*% realFac
  
  # Create a similarity matrix for the pairwise comparison
  similarity_matrix <- matrix(0, nrow = ncol(modelFac), ncol = ncol(modelFac))
  
  # Compute pairwise cosine similarity across all modes
  for (k in 1:ncol(modelFac)) {
    for (l in 1:ncol(realFac)) {
      vect1 <- as.matrix(modelFac[, k])
      vect2 <- as.matrix(realFac[, l])
      
      # Cosine similarity
      similarity_matrix[k, l] <- abs(t(vect1) %*% vect2) / (norm(vect1, "F") * norm(vect2, "F"))
    }
  }
  
  # Use Hungarian algorithm to find the best matching
  assignment <- clue::solve_LSAP(similarity_matrix, maximum = TRUE)
  
  # Permute columns in the model to fit the input components
  # modelFac_perm <- modelFac[,assignment]
  
  # Calculate FMS based on the best matching
  FMS <- sum(similarity_matrix[cbind(seq_along(assignment), assignment)])
  
  # Average over the number of components
  FMS <- FMS / numComponents
  return(FMS)
}

```

```{r lambda similarity function}
lambda_true = matrix(c(1,1,1,1,1,1,1,1,0,1,1,0,1,0,0,0,1,0,0,0,1), nrow=3, ncol=7)

lambda_similarity = function(lambda_hat){
  lambda_hat = abs(lambda_hat)
  similarity_matrix = matrix(NA, nrow=7, ncol=7)
  for(i in 1:7){
    for(j in 1:7){
      real = lambda_true[,i]
      hat = lambda_hat[,j]
      similarity_matrix[i,j] = sum((real - hat)^2)
    }
  }
  
  mapping = clue::solve_LSAP(similarity_matrix)
  lambda_hat_perm = lambda_hat[,mapping]
  SSR = sum((lambda_true - lambda_hat_perm)^2)
  return(SSR)
}
```

```{r load input loadings}
inputLoadings = readRDS("./Sim2_input_loadings_Y_inside.RDS")

# Reorganize into Fac object
inputLoadingsFac = inputLoadings
inputLoadingsFac[[2]] = inputLoadings[[2]][,c(1,4,7,9,11)]
inputLoadingsFac[[3]] = inputLoadings[[3]][,c(1,4,7,9,11)]
inputLoadingsFac[[4]] = inputLoadings[[2]][,c(2,5,8,10,12)]
inputLoadingsFac[[5]] = inputLoadings[[3]][,c(2,5,8,10,12)]
inputLoadingsFac[[6]] = inputLoadings[[2]][,c(3,6,13)]
inputLoadingsFac[[7]] = inputLoadings[[3]][,c(3,6,13)]

```

```{r load datasets}
X1_final = readRDS("./Sim2_X1_Y_inside.RDS")
X2_final = readRDS("./Sim2_X2_Y_inside.RDS")
X3_final = readRDS("./Sim2_X3_Y_inside.RDS")
Y_final = readRDS("./Sim2_Y_Y_inside.RDS")
```

# Sanity checks
```{r plot loadings}
a = inputLoadings[[1]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% ggplot(aes(x=index,y=value,col=as.factor(name))) + geom_line() + xlab("Subject index") + ylab("Value") + scale_colour_manual(name="Component", labels=c("a_global1", "a_global2", "a_local1", "a_local2", "a_distinct1", "a_distinct2", "a_distinct3"), values=hue_pal()(7))

b = inputLoadings[[2]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% ggplot(aes(x=index,y=value,col=as.factor(name))) + geom_line() + xlab("Feature index") + ylab("Value") + scale_colour_manual(name="Component", labels=c("b_global1_X1", "b_global1_X2", "b_global1_X3", "b_global2_X1", "b_global2_X2", "b_global2_X3", "b_local1_X1", "b_local1_X2", "b_local2_X1", "b_local2_X2", "b_distinct1", "b_distinct2", "b_distinct3"), values=hue_pal()(13))

c = inputLoadings[[3]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% ggplot(aes(x=index,y=value,col=as.factor(name))) + geom_line() + xlab("Time index") + ylab("Value") + scale_colour_manual(name="Component", labels=c("c_global1_X1", "c_global1_X2", "c_global1_X3", "c_global2_X1", "c_global2_X2", "c_global2_X3", "c_local1_X1", "c_local1_X2", "c_local2_X1", "c_local2_X2", "c_distinct1", "c_distinct2", "c_distinct3"), values=hue_pal()(13))

ggarrange(a,b,c,nrow=3)
```

# Analyze ACMTF results
```{r load ACMTF models}
ACMTF_CV_models = readRDS("./Sim2_ACMTF_CV_models_Y_inside.RDS")
ACMTF_CV_params = readRDS("./Sim2_ACMTF_CV_params_Y_inside.RDS")
ACMTF_YAS_models = readRDS("./Sim2_ACMTF_YAS_models_Y_inside.RDS")
ACMTF_YAS_params = readRDS("./Sim2_ACMTF_YAS_params_Y_inside.RDS")
ACMTFR_CV_models = readRDS("./Sim2_ACMTFR_CV_Y_inside.RDS")
ACMTFR_CV_params = readRDS("./Sim2_ACMTFR_CV_params_Y_inside.RDS")
```

```{r plot varExps for ACMTF}
defaultModels = which(ACMTF_CV_params == 1e-3)
ACMTF_models = ACMTF_CV_models[defaultModels]
numModes = length(ACMTF_models[[1]]$Fac) - 1

ACMTF_FMS1 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[1]], inputLoadingsFac[[1]], numComponents=7)})) %>% as_tibble()
ACMTF_FMS2 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[2]], inputLoadingsFac[[2]], numComponents=5)})) %>% as_tibble()
ACMTF_FMS3 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[3]], inputLoadingsFac[[3]], numComponents=5)})) %>% as_tibble()
ACMTF_FMS4 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[4]], inputLoadingsFac[[4]], numComponents=5)})) %>% as_tibble()
ACMTF_FMS5 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[5]], inputLoadingsFac[[5]], numComponents=5)})) %>% as_tibble()
ACMTF_FMS6 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[6]], inputLoadingsFac[[6]], numComponents=3)})) %>% as_tibble()
ACMTF_FMS7 = do.call(rbind, lapply(ACMTF_models, FUN=function(x){calculateFMS(x$Fac[[7]], inputLoadingsFac[[7]], numComponents=3)})) %>% as_tibble()

ACMTF_f = do.call(rbind, lapply(ACMTF_models, FUN=function(x){x$f}))
correctModels = ACMTF_f %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% filter(V1 < 0.80) %>% select(index) %>% pull()

ACMTF_FMS = cbind(ACMTF_FMS1, ACMTF_FMS2, ACMTF_FMS3, ACMTF_FMS4, ACMTF_FMS5, ACMTF_FMS6, ACMTF_FMS7)
colnames(ACMTF_FMS) = c("ACMTF_FMS1", "ACMTF_FMS2", "ACMTF_FMS3", "ACMTF_FMS4", "ACMTF_FMS5", "ACMTF_FMS6", "ACMTF_FMS7")

ACMTF_FMS = ACMTF_FMS %>%
  as_tibble() %>%
  mutate(index=1:nrow(.)) %>%
  mutate(correct = index %in% correctModels,
         FMS_X1 = ACMTF_FMS1 * ACMTF_FMS2 * ACMTF_FMS3,
         FMS_X2 = ACMTF_FMS1 * ACMTF_FMS4 * ACMTF_FMS5,
         FMS_X3 = ACMTF_FMS1 * ACMTF_FMS6 * ACMTF_FMS7)

ACMTF_FMS %>% as_tibble() %>%
  select(-FMS_X1, -FMS_X2, -FMS_X3) %>%
  pivot_longer(-c(index,correct)) %>%
  ggplot(aes(x=index,y=value,fill=as.factor(correct))) +
  facet_wrap(~name) +
  geom_bar(stat="identity")

ACMTF_FMS %>%
  select(index, correct, FMS_X1, FMS_X2, FMS_X3) %>%
  pivot_longer(-c(index,correct)) %>%
  ggplot(aes(x=index,y=value,fill=as.factor(correct))) +
  facet_wrap(~name) +
  geom_bar(stat="identity")

ACMTF_FMS %>% 
  select(-FMS_X1, -FMS_X2, -FMS_X3) %>%
  pivot_longer(-index) %>%
  ggplot(aes(x=as.factor(name),y=value)) +
  geom_boxplot()

ACMTF_FMS %>% 
  select(index, FMS_X1, FMS_X2, FMS_X3) %>%
  pivot_longer(-index) %>%
  ggplot(aes(x=as.factor(name),y=value)) +
  geom_boxplot()

ACMTF_varExps = do.call(rbind, lapply(ACMTF_models, FUN=function(x){(x$varExp)})) %>% as_tibble()
ACMTF_varExps = ACMTF_varExps * 100
colnames(ACMTF_varExps) = c("X1", "X2", "X3")
ACMTF_varExps = ACMTF_varExps %>% mutate(index=1:nrow(.))

# correctModels = ACMTF_varExps %>% filter(X1 > 99, X2 > 99, X3 > 99) %>% select(index) %>% pull()
ACMTF_varExps = ACMTF_varExps %>% mutate(correct = index %in% correctModels)

ACMTF_models_correct = ACMTF_models[ACMTF_varExps$index %in% correctModels]
ACMTF_models_incorrect = ACMTF_models[!ACMTF_varExps$index %in% correctModels]

a = ACMTF_varExps %>% ggplot(aes(x=index,y=X1,fill=as.factor(correct))) + geom_bar(stat="identity") + xlab("") + ylab("varExp X1 (%)")
b = ACMTF_varExps %>% ggplot(aes(x=index,y=X2,fill=as.factor(correct))) + geom_bar(stat="identity") + xlab("") + ylab("varExp X2 (%)")
c = ACMTF_varExps %>% ggplot(aes(x=index,y=X3,fill=as.factor(correct))) + geom_bar(stat="identity") + xlab("Model index") + ylab("varExp X3 (%)")
ggarrange(a,b,c,nrow=3, common.legend=TRUE)
```

```{r inspect lambdas for ACMTF}
ACMTF_models_correct[[1]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Lambdas (correct model)")

ACMTF_models_incorrect[[1]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Lambdas (incorrect model)")

#do.call(rbind, lapply(ACMTF_models, FUN=function(x){x$Fac[[8]]} %>% as_tibble() %>% mutate(index=1:nrow(.))))
```

# ACMTF CV
```{r plot varExps for ACMTF CV}
threshold = 99

ACMTF_CV_f = do.call(rbind, lapply(ACMTF_CV_models, FUN=function(x){x$f}))
ACMTF_CV_f = ACMTF_CV_f %>% as_tibble() %>% mutate(beta=ACMTF_CV_params, index=1:length(beta)) %>% mutate(correct = V1 < 0.90)

ACMTF_CV_varExps = do.call(rbind, lapply(ACMTF_CV_models, FUN=function(x){(x$varExp)})) %>% as_tibble()
ACMTF_CV_varExps = ACMTF_CV_varExps * 100
colnames(ACMTF_CV_varExps) = c("X1", "X2", "X3")
ACMTF_CV_varExps = ACMTF_CV_varExps %>% mutate(beta = ACMTF_CV_params)
ACMTF_CV_varExps = ACMTF_CV_varExps %>% mutate(minimum = apply(ACMTF_CV_varExps[,1:3], 1, min)) %>% mutate(correct = minimum >= threshold) %>% select(-minimum)

ACMTF_CV_FMS = do.call(rbind, lapply(ACMTF_CV_models, FUN=function(x){calculateFMS(x$Fac[[1]], inputLoadingsFac[[1]], 7) * calculateFMS(x$Fac[[2]], inputLoadingsFac[[2]], 5) * calculateFMS(x$Fac[[3]], inputLoadingsFac[[3]], 5) * calculateFMS(x$Fac[[4]], inputLoadingsFac[[4]], 5) * calculateFMS(x$Fac[[5]], inputLoadingsFac[[5]], 5) * calculateFMS(x$Fac[[6]], inputLoadingsFac[[6]], 3) * calculateFMS(x$Fac[[7]], inputLoadingsFac[[7]], 3)}))
ACMTF_CV_FMS = ACMTF_CV_FMS %>% as_tibble() %>% mutate(beta=ACMTF_CV_params, index=1:length(beta))

ACMTF_CV_varExps %>% as_tibble() %>% select(-correct) %>% pivot_longer(-beta) %>% ggplot(aes(x=as.factor(beta),y=value)) + facet_wrap(~name) + geom_boxplot() + xlab("Beta") + ylab("Variance explained (%)")
ACMTF_CV_FMS %>% ggplot(aes(x=as.factor(beta),y=V1)) + geom_boxplot() + xlab("Beta") + ylab("Overall FMS")
ACMTF_CV_f %>% ggplot(aes(x=as.factor(beta),y=V1)) + geom_boxplot() + geom_hline(yintercept=0.90, col="red") + xlab("Beta") + ylab("Loss value")
ACMTF_CV_f %>% ggplot(aes(x=as.factor(beta),fill=as.factor(correct))) + geom_bar(col="black") + xlab("Beta")
```

```{r how often are the components found}
projectAndCosine = function(Test, Ttrue){
  Tproj = Test %*% pracma::pinv(t(Test) %*% Test) %*% t(Test) %*% Ttrue
  similarity = sum(Tproj * Ttrue) / (norm(Tproj, "2") * norm(Ttrue, "2"))
  return(similarity)
}

threshold = 0.99
global1_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,1]) > threshold}))
global2_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,2]) > threshold}))
local1_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,3]) > threshold}))
local2_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,4]) > threshold}))
distinct1_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,5]) > threshold}))
distinct2_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,6]) > threshold}))
distinct3_found = unlist(lapply(ACMTF_CV_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,7]) > threshold}))

componentShapes = cbind(ACMTF_CV_FMS, global1_found, global2_found, local1_found, local2_found, distinct1_found, distinct2_found, distinct3_found) %>% as_tibble()

componentShapes %>% select(-V1,-index) %>% pivot_longer(-beta) %>% ggplot(aes(x=as.factor(beta),fill=as.factor(value))) + facet_wrap(~name,nrow=7) + geom_bar()

```

```{r stratify the models}
colours = hue_pal()(4)

a=componentShapes %>% mutate(numFound = global1_found + global2_found + local1_found + local2_found + distinct1_found + distinct2_found + distinct3_found) %>% mutate(numGlobalLost = 2 - (global1_found>=1) - (global2_found>=1)) %>% ggplot(aes(x=as.factor(beta),fill=as.factor(numGlobalLost))) + geom_bar(col="black") + xlab("beta") + ylab("Number of models") + scale_fill_manual(name="Number of components lost", labels=0:2, values=colours[-4]) + ggtitle("Global components lost") + ylim(c(0,100))

b=componentShapes %>% mutate(numFound = global1_found + global2_found + local1_found + local2_found + distinct1_found + distinct2_found + distinct3_found) %>% mutate(numLocalLost = 2 - (local1_found>=1) - (local2_found>=1)) %>% ggplot(aes(x=as.factor(beta),fill=as.factor(numLocalLost))) + geom_bar(col="black") + xlab("beta") + ylab("Number of models") + scale_fill_manual(name="Number of components lost", labels=0:2, values=colours[-4]) + ggtitle("Local components lost") + ylim(c(0,100))

c=componentShapes %>% mutate(numFound = global1_found + global2_found + local1_found + local2_found + distinct1_found + distinct2_found + distinct3_found) %>% mutate(numDistinctLost = 3 - distinct1_found - distinct2_found - distinct3_found) %>% ggplot(aes(x=as.factor(beta),fill=as.factor(numDistinctLost))) + geom_bar(col="black") + xlab("beta") + ylab("Number of models") + scale_fill_manual(name="Number of components lost", labels=0:3, values=colours) + ggtitle("Distinct components lost") + theme(legend.position="bottom") + ylim(c(0,100))

ggarrange(a,b,c,nrow=3,ncol=1,common.legend=TRUE, legend.grob=get_legend(c))
```

# ACMTF YAS

```{r plot varExps for ACMTF YAS}
threshold = 99

ACMTF_YAS_f = do.call(rbind, lapply(ACMTF_YAS_models, FUN=function(x){x$f}))
ACMTF_YAS_f = ACMTF_YAS_f %>% as_tibble() %>% mutate(beta=ACMTF_CV_params, index=1:length(beta)) %>% mutate(correct = V1 < 0.2)

ACMTF_YAS_varExps = do.call(rbind, lapply(ACMTF_YAS_models, FUN=function(x){(x$varExp)})) %>% as_tibble()
ACMTF_YAS_varExps = ACMTF_YAS_varExps * 100
colnames(ACMTF_YAS_varExps) = c("X1", "X2", "X3", "Y")
ACMTF_YAS_varExps = ACMTF_YAS_varExps %>% mutate(beta = ACMTF_YAS_params)
ACMTF_YAS_varExps = ACMTF_YAS_varExps %>% mutate(minimum = apply(ACMTF_YAS_varExps[,1:3], 1, min)) %>% mutate(correct = minimum >= threshold) %>% select(-minimum)

ACMTF_YAS_FMS = do.call(rbind, lapply(ACMTF_YAS_models, FUN=function(x){calculateFMS(x$Fac[[1]], inputLoadingsFac[[1]], 7) * calculateFMS(x$Fac[[2]], inputLoadingsFac[[2]], 5) * calculateFMS(x$Fac[[3]], inputLoadingsFac[[3]], 5) * calculateFMS(x$Fac[[4]], inputLoadingsFac[[4]], 5) * calculateFMS(x$Fac[[5]], inputLoadingsFac[[5]], 5) * calculateFMS(x$Fac[[6]], inputLoadingsFac[[6]], 3) * calculateFMS(x$Fac[[7]], inputLoadingsFac[[7]], 3)}))
ACMTF_YAS_FMS = ACMTF_YAS_FMS %>% as_tibble() %>% mutate(beta=ACMTF_YAS_params, index=1:length(beta))

ACMTF_YAS_varExps %>% as_tibble() %>% select(-correct) %>% pivot_longer(-beta) %>% ggplot(aes(x=as.factor(beta),y=value)) + facet_wrap(~name) + geom_boxplot() + xlab("Beta") + ylab("Variance explained (%)")
ACMTF_YAS_FMS %>% ggplot(aes(x=as.factor(beta),y=V1)) + geom_boxplot() + xlab("Beta") + ylab("Overall FMS")
ACMTF_YAS_f %>% ggplot(aes(x=as.factor(beta),y=V1)) + geom_boxplot() + geom_hline(yintercept=0.20, col="red") + xlab("Beta") + ylab("Loss value")
ACMTF_YAS_f %>% ggplot(aes(x=as.factor(beta),fill=as.factor(correct))) + geom_bar(col="black") + xlab("Beta")
```

```{r how often are the components found YAS}
projectAndCosine = function(Test, Ttrue){
  Tproj = Test %*% pracma::pinv(t(Test) %*% Test) %*% t(Test) %*% Ttrue
  similarity = sum(Tproj * Ttrue) / (norm(Tproj, "2") * norm(Ttrue, "2"))
  return(similarity)
}

threshold = 0.99
global1_found = unlist(lapply(ACMTF_YAS_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,1]) > threshold}))
global2_found = unlist(lapply(ACMTF_YAS_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,2]) > threshold}))
local1_found = unlist(lapply(ACMTF_YAS_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,3]) > threshold}))
local2_found = unlist(lapply(ACMTF_YAS_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,4]) > threshold}))
distinct1_found = unlist(lapply(ACMTF_YAS_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,5]) > threshold}))
distinct2_found = unlist(lapply(ACMTF_YAS_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,6]) > threshold}))
distinct3_found = unlist(lapply(ACMTF_YAS_models, FUN=function(x){projectAndCosine(x$Fac[[1]], inputLoadings[[1]][,7]) > threshold}))

componentShapes = cbind(ACMTF_YAS_FMS, global1_found, global2_found, local1_found, local2_found, distinct1_found, distinct2_found, distinct3_found) %>% as_tibble()

componentShapes %>% select(-V1,-index) %>% pivot_longer(-beta) %>% ggplot(aes(x=as.factor(beta),fill=as.factor(value))) + facet_wrap(~name,nrow=7) + geom_bar()

```

```{r stratify the models}
colours = hue_pal()(4)

a=componentShapes %>% mutate(numFound = global1_found + global2_found + local1_found + local2_found + distinct1_found + distinct2_found + distinct3_found) %>% mutate(numGlobalLost = 2 - (global1_found>=1) - (global2_found>=1)) %>% ggplot(aes(x=as.factor(beta),fill=as.factor(numGlobalLost))) + geom_bar(col="black") + xlab("beta") + ylab("Number of models") + scale_fill_manual(name="Number of components lost", labels=0:2, values=colours[-4]) + ggtitle("Global components lost") + ylim(c(0,100))

b=componentShapes %>% mutate(numFound = global1_found + global2_found + local1_found + local2_found + distinct1_found + distinct2_found + distinct3_found) %>% mutate(numLocalLost = 2 - (local1_found>=1) - (local2_found>=1)) %>% ggplot(aes(x=as.factor(beta),fill=as.factor(numLocalLost))) + geom_bar(col="black") + xlab("beta") + ylab("Number of models") + scale_fill_manual(name="Number of components lost", labels=0:2, values=colours[-4]) + ggtitle("Local components lost") + ylim(c(0,100))

c=componentShapes %>% mutate(numFound = global1_found + global2_found + local1_found + local2_found + distinct1_found + distinct2_found + distinct3_found) %>% mutate(numDistinctLost = 3 - (distinct1_found>=1) - (distinct2_found>=1) - (distinct3_found>=1)) %>% ggplot(aes(x=as.factor(beta),fill=as.factor(numDistinctLost))) + geom_bar(col="black") + xlab("beta") + ylab("Number of models") + scale_fill_manual(name="Number of components lost", labels=0:3, values=colours) + ggtitle("Distinct components lost") + theme(legend.position="bottom") + ylim(c(0,100))

ggarrange(a,b,c,nrow=3,ncol=1,common.legend=TRUE, legend.grob=get_legend(c))
```
# ACMTFR only beta=1e-3
```{r inspect only beta 1e-3 case}
mask = ACMTFR_CV_params[,1] == 1e-3
models = ACMTFR_CV_models[mask]

ACMTFR_varExpX = do.call(rbind, lapply(models, FUN=function(x){(x$varExp)})) * 100
ACMTFR_varExpY = do.call(rbind, lapply(models, FUN=function(x){x$varExpY}))
ACMTFR_varExps = cbind(ACMTFR_varExpX, ACMTFR_varExpY)
colnames(ACMTFR_varExps) = c("X1", "X2", "X3", "Y")
ACMTFR_varExps = ACMTFR_varExps %>% as_tibble() %>% mutate(index=1:nrow(.), pi = ACMTFR_CV_params[mask,2])

ACMTFR_f = do.call(rbind, lapply(models, FUN=function(x){x$f}))
ACMTFR_f = ACMTFR_f %>% as_tibble() %>% mutate(index=1:nrow(.), pi = ACMTFR_CV_params[mask,2])

ACMTFR_FMS1 = do.call(rbind, lapply(models, FUN=function(x){calculateFMS(x$Fac[[1]], inputLoadingsFac[[1]], numComponents=7)})) %>% as_tibble()
ACMTFR_FMS2 = do.call(rbind, lapply(models, FUN=function(x){calculateFMS(x$Fac[[2]], inputLoadingsFac[[2]], numComponents=5)})) %>% as_tibble()
ACMTFR_FMS3 = do.call(rbind, lapply(models, FUN=function(x){calculateFMS(x$Fac[[3]], inputLoadingsFac[[3]], numComponents=5)})) %>% as_tibble()
ACMTFR_FMS4 = do.call(rbind, lapply(models, FUN=function(x){calculateFMS(x$Fac[[4]], inputLoadingsFac[[4]], numComponents=5)})) %>% as_tibble()
ACMTFR_FMS5 = do.call(rbind, lapply(models, FUN=function(x){calculateFMS(x$Fac[[5]], inputLoadingsFac[[5]], numComponents=5)})) %>% as_tibble()
ACMTFR_FMS6 = do.call(rbind, lapply(models, FUN=function(x){calculateFMS(x$Fac[[6]], inputLoadingsFac[[6]], numComponents=3)})) %>% as_tibble()
ACMTFR_FMS7 = do.call(rbind, lapply(models, FUN=function(x){calculateFMS(x$Fac[[7]], inputLoadingsFac[[7]], numComponents=3)})) %>% as_tibble()

ACMTFR_FMS = cbind(ACMTFR_FMS1, ACMTFR_FMS2, ACMTFR_FMS3, ACMTFR_FMS4, ACMTFR_FMS5, ACMTFR_FMS6, ACMTFR_FMS7)
colnames(ACMTFR_FMS) = c("FMS1", "FMS2", "FMS3", "FMS4", "FMS5", "FMS6", "FMS7")
ACMTFR_FMS = ACMTFR_FMS %>% as_tibble() %>% mutate(X1 = FMS1 * FMS2 * FMS3, X2 = FMS1 * FMS4 * FMS5, X3 = FMS1 * FMS6 * FMS7, pi = ACMTFR_CV_params[mask,2], index=1:length(pi))

ACMTFR_lambda_similarity = do.call(rbind, lapply(models, FUN=function(x){lambda_similarity(x$Fac[[8]])}))
ACMTFR_lambda_similarity = ACMTFR_lambda_similarity %>% as_tibble() %>% mutate(index=1:nrow(.), pi = ACMTFR_CV_params[mask,2])

# Plots
ACMTFR_varExps %>% filter(pi != 0) %>% select(-index) %>% pivot_longer(-pi) %>% ggplot(aes(x=as.factor(pi),y=value)) + facet_wrap(~name) + geom_boxplot() + xlab("Pi") + ylab("Variance explained (%)")

ACMTFR_f %>% ggplot(aes(x=as.factor(pi),y=V1)) + geom_boxplot() + xlab("Pi") + ylab("Loss")

ACMTFR_FMS %>% filter(pi != 0) %>% select(X1,X2,X3,pi) %>% pivot_longer(-pi) %>% ggplot(aes(x=as.factor(pi),y=value)) + facet_wrap(~name) + geom_boxplot() + xlab("Pi") + ylab("FMS")

ACMTFR_lambda_similarity %>% ggplot(aes(x=as.factor(pi),y=V1)) + geom_boxplot() + xlab("Pi") + ylab("Lambda similarity") + scale_y_log10()

ACMTFR_FMS %>% mutate(lambda_similarity = ACMTFR_lambda_similarity$V1) %>% select(X1, X2, X3, pi, lambda_similarity) %>% pivot_longer(-c(pi, lambda_similarity)) %>% ggplot(aes(x=lambda_similarity,y=value)) + facet_grid(vars(name),vars(pi)) + geom_point() + xlab("Lambda similarity") + ylab("FMS") + scale_x_log10()

ACMTFR_FMS %>% mutate(lambda_similarity = ACMTFR_lambda_similarity$V1) %>% mutate(correct = (lambda_similarity<=1) & (X1>=0.9) & (X2>=0.9) & (X3>=0.9)) %>% ggplot(aes(x=as.factor(pi),fill=correct)) + geom_bar(col="black") + xlab("Pi") + ylab("Number of models")
```

```{r plot some lambda matrices}
a=models[[6]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Pi=1") + theme(legend.position="none")

b=models[[17]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Pi=0.8") + theme(legend.position="none")

c=models[[16]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Pi=0.6") + theme(legend.position="none")

d=models[[9]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Pi=0.4") + theme(legend.position="none")

e=models[[14]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Pi=0.2") + theme(legend.position="none")

f=models[[1]]$Fac[[8]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Pi=0") + theme(legend.position="none")

ggarrange(a,b,c,d,e,f,nrow=3,ncol=2)
```

```{r how often are the components found}
threshold = 0.95
colours = hue_pal()(4)

global1 = unlist(lapply(models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,1])))}))
global2 = unlist(lapply(models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,2])))}))
local1 = unlist(lapply(models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,3])))}))
local2 = unlist(lapply(models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,4])))}))
distinct1 = unlist(lapply(models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,5])))}))
distinct2 = unlist(lapply(models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,6])))}))
distinct3 = unlist(lapply(models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,7])))}))

componentShapes = cbind(ACMTFR_FMS, global1, global2, local1, local2, distinct1, distinct2, distinct3)

componentShapes %>% as_tibble() %>% select(pi, global1, global2, local1, local2, distinct1, distinct2, distinct3) %>% pivot_longer(-pi) %>% ggplot(aes(x=as.factor(pi),y=value)) + facet_wrap(~name) + geom_boxplot()

a=componentShapes %>% as_tibble() %>% mutate(global1 = global1 < threshold, global2 = global2 < threshold, local1 = local1 < threshold, local2 = local2 < threshold, distinct1 = distinct1 < threshold, distinct2 = distinct2 < threshold, distinct3 = distinct3 < threshold) %>% mutate(numGlobalLost = global1 + global2) %>% ggplot(aes(x=as.factor(pi),fill=as.factor(numGlobalLost))) + geom_bar(col="black") + xlab("Pi") + ylab("Number of models") + scale_fill_manual(name="Number of components lost", labels=0:2, values=colours[-4]) + ggtitle("Global components lost")

b=componentShapes %>% as_tibble() %>% mutate(global1 = global1 < threshold, global2 = global2 < threshold, local1 = local1 < threshold, local2 = local2 < threshold, distinct1 = distinct1 < threshold, distinct2 = distinct2 < threshold, distinct3 = distinct3 < threshold) %>% mutate(numLocalLost = local1 + local2) %>% ggplot(aes(x=as.factor(pi),fill=as.factor(numLocalLost))) + geom_bar(col="black") + xlab("Pi") + ylab("Number of models") + scale_fill_manual(name="Number of components lost", labels=0:2, values=colours[-4]) + ggtitle("Local components lost")

c=componentShapes %>% as_tibble() %>% mutate(global1 = global1 < threshold, global2 = global2 < threshold, local1 = local1 < threshold, local2 = local2 < threshold, distinct1 = distinct1 < threshold, distinct2 = distinct2 < threshold, distinct3 = distinct3 < threshold) %>% mutate(numDistinctLost = distinct1 + distinct2 + distinct3) %>% ggplot(aes(x=as.factor(pi),fill=as.factor(numDistinctLost))) + geom_bar(col="black") + xlab("Pi") + ylab("Number of models") + scale_fill_manual(name="Number of components lost", labels=0:3, values=colours) + ggtitle("Distinct components lost") + theme(legend.position="bottom")

ggarrange(a,b,c,nrow=3,ncol=1,common.legend=TRUE, legend.grob=get_legend(c))
```

# ACMTFR
```{r plot varExps for ACMTFR}
ACMTFR_CV_varExpX = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){(x$varExp)})) * 100
ACMTFR_CV_varExpY = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){x$varExpY}))
ACMTFR_CV_varExps = cbind(ACMTFR_CV_varExpX, ACMTFR_CV_varExpY)
colnames(ACMTFR_CV_varExps) = c("X1", "X2", "X3", "Y")
ACMTFR_CV_varExps = ACMTFR_CV_varExps %>% as_tibble() %>% mutate(index=1:nrow(.), beta=ACMTFR_CV_params[,1], pi = ACMTFR_CV_params[,2])

ACMTFR_CV_f = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){x$f}))
ACMTFR_CV_f = ACMTFR_CV_f %>% as_tibble() %>% mutate(index=1:nrow(.), beta=ACMTFR_CV_params[,1], pi = ACMTFR_CV_params[,2])

ACMTFR_CV_FMS1 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[1]], inputLoadingsFac[[1]], numComponents=7)})) %>% as_tibble()
ACMTFR_CV_FMS2 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[2]], inputLoadingsFac[[2]], numComponents=5)})) %>% as_tibble()
ACMTFR_CV_FMS3 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[3]], inputLoadingsFac[[3]], numComponents=5)})) %>% as_tibble()
ACMTFR_CV_FMS4 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[4]], inputLoadingsFac[[4]], numComponents=5)})) %>% as_tibble()
ACMTFR_CV_FMS5 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[5]], inputLoadingsFac[[5]], numComponents=5)})) %>% as_tibble()
ACMTFR_CV_FMS6 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[6]], inputLoadingsFac[[6]], numComponents=3)})) %>% as_tibble()
ACMTFR_CV_FMS7 = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){calculateFMS(x$Fac[[7]], inputLoadingsFac[[7]], numComponents=3)})) %>% as_tibble()

ACMTFR_FMS = cbind(ACMTFR_CV_FMS1, ACMTFR_CV_FMS2, ACMTFR_CV_FMS3, ACMTFR_CV_FMS4, ACMTFR_CV_FMS5, ACMTFR_CV_FMS6, ACMTFR_CV_FMS7)
colnames(ACMTFR_FMS) = c("FMS1", "FMS2", "FMS3", "FMS4", "FMS5", "FMS6", "FMS7")
ACMTFR_FMS = ACMTFR_FMS %>% as_tibble() %>% mutate(X1 = FMS1 * FMS2 * FMS3, X2 = FMS1 * FMS4 * FMS5, X3 = FMS1 * FMS6 * FMS7, beta=ACMTFR_CV_params[,1],pi = ACMTFR_CV_params[,2], index=1:length(pi))

ACMTFR_CV_lambda_similarity = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){lambda_similarity(x$Fac[[8]])}))
ACMTFR_CV_lambda_similarity = ACMTFR_CV_lambda_similarity %>% as_tibble() %>% mutate(index=1:nrow(.), beta=ACMTFR_CV_params[,1], pi = ACMTFR_CV_params[,2])

# Plots
ACMTFR_CV_varExps %>% filter(pi!=0) %>% select(-index) %>% pivot_longer(-c(beta,pi)) %>% ggplot(aes(x=as.factor(beta),y=value)) + facet_grid(vars(name),vars(pi)) + geom_boxplot() + xlab("Beta") + ylab("Variance explained (%)")

ACMTFR_CV_f %>% select(-index) %>% ggplot(aes(x=as.factor(beta),y=V1)) + facet_wrap(~pi) + geom_boxplot() + xlab("Beta") + ylab("Loss")

ACMTFR_FMS %>% select(X1,X2,X3,beta,pi) %>% pivot_longer(-c(beta,pi)) %>% ggplot(aes(x=as.factor(beta),y=value)) + facet_grid(vars(name),vars(pi)) + geom_boxplot() + xlab("Beta") + ylab("FMS")

ACMTFR_CV_lambda_similarity %>% ggplot(aes(x=as.factor(beta),y=V1)) + facet_wrap(~pi) + geom_boxplot() + xlab("Beta") + ylab("Lambda similarity") + scale_y_log10()

a=ACMTFR_FMS %>% mutate(lambda_similarity = ACMTFR_CV_lambda_similarity$V1) %>% filter(pi!=0,beta<0.5) %>% select(X1,beta,pi,lambda_similarity) %>% ggplot(aes(x=lambda_similarity,y=X1)) + facet_grid(vars(beta),vars(pi)) + geom_point() + xlab("Lambda similarity") + ylab("FMS") + ggtitle("X1") + scale_x_log10()
b=ACMTFR_FMS %>% mutate(lambda_similarity = ACMTFR_CV_lambda_similarity$V1) %>% filter(pi!=0,beta<0.5) %>% select(X2,beta,pi,lambda_similarity) %>% ggplot(aes(x=lambda_similarity,y=X2)) + facet_grid(vars(beta),vars(pi)) + geom_point() + xlab("Lambda similarity") + ylab("FMS") + ggtitle("X2") + scale_x_log10()
c=ACMTFR_FMS %>% mutate(lambda_similarity = ACMTFR_CV_lambda_similarity$V1) %>% filter(pi!=0,beta<0.5) %>% select(X3,beta,pi,lambda_similarity) %>% ggplot(aes(x=lambda_similarity,y=X3)) + facet_grid(vars(beta),vars(pi)) + geom_point() + xlab("Lambda similarity") + ylab("FMS") + ggtitle("X3") + scale_x_log10()
ggarrange(a,b,c,nrow=1)

ACMTFR_FMS %>% mutate(lambda_similarity = ACMTFR_CV_lambda_similarity$V1) %>% filter(pi!=0,beta<0.5) %>% select(X1,X2,X3,beta,pi,lambda_similarity) %>% mutate(correct = (lambda_similarity<=1) & (X1>=0.9) & (X2>=0.9) & (X3>=0.9)) %>% select(-X1,-X2,-X3,-lambda_similarity) %>% group_by(beta,pi) %>% summarize(fraction = sum(correct)/100) %>% ungroup() %>% ggplot(aes(x=as.factor(beta),y=as.factor(pi),fill=fraction)) + geom_tile(col="black") + labs(x="Beta",y="Pi",fill="Fraction correct")
```

```{r how often are the components found}
threshold = 0.95
colours = hue_pal()(4)

Yreal = readRDS("./Sim2_Y_Y_inside.RDS")
Yreal = Yreal@data
Yreal = as.matrix(Yreal)

global1 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,1])))}))
global2 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,2])))}))
local1 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,3])))}))
local2 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,4])))}))
distinct1 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,5])))}))
distinct2 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,6])))}))
distinct3 = unlist(lapply(ACMTFR_CV_models, FUN=function(x){max(abs(cor(x$Fac[[1]], inputLoadings[[1]][,7])))}))
y_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){abs(cor(x$Yhat, Yreal))}))

componentShapes = cbind(ACMTFR_FMS, global1, global2, local1, local2, distinct1, distinct2, distinct3, y_found)

componentShapes %>% as_tibble() %>% select(beta, pi, global1, global2, local1, local2, distinct1, distinct2, distinct3, y_found) %>% pivot_longer(-c(beta,pi)) %>% mutate(Found = value > threshold) %>% ggplot(aes(x=as.factor(beta),fill=Found)) + facet_grid(vars(name),vars(pi)) + geom_bar()

componentShapes %>% as_tibble() %>% mutate(global1 = global1 < threshold, global2 = global2 < threshold, local1 = local1 < threshold, local2 = local2 < threshold, distinct1 = distinct1 < threshold, distinct2 = distinct2 < threshold, distinct3 = distinct3 < threshold) %>% mutate(Global = global1 + global2, Local = local1 + local2, Distinct = distinct1 + distinct2 + distinct3) %>% select(beta, pi, Global, Local, Distinct) %>% pivot_longer(-c(beta,pi)) %>% mutate(name = factor(name, levels=c("Global", "Local", "Distinct"))) %>% ggplot(aes(x=as.factor(beta),fill=as.factor(value))) + facet_grid(vars(pi), vars(name)) + geom_bar(col="black") + labs(x="Beta",y="Number of models",fill="Number of components lost")
```


```{r comparison of some models}
modelA = ACMTFR_CV_models[[13]] # pi 0.0
modelB = ACMTFR_CV_models[[14]] # pi 0.2
modelC = ACMTFR_CV_models[[15]] # pi 0.4
modelD = ACMTFR_CV_models[[70]] # pi 0.6
modelE = ACMTFR_CV_models[[17]] # pi 0.8
modelF = ACMTFR_CV_models[[18]] # pi 1.0

# Y
df = cbind(modelA$Yhat, modelB$Yhat, modelC$Yhat, modelD$Yhat, modelE$Yhat, modelF$Yhat, Yreal) %>% as_tibble()
colnames(df) = c("0.0", "0.2", "0.4", "0.6", "0.8", "1.0", "true")
df %>% pivot_longer(-true) %>% ggplot(aes(x=true,y=value,col=as.factor(name))) + geom_point() + xlab("Y") + ylab("Yhat") + labs(color="Pi")

# Test
y_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){(sum(x$Yhat * Yreal) / (norm(x$Yhat, "2") * norm(Yreal, "2")))}))
y_found = cbind(ACMTFR_CV_params, y_found) %>% as_tibble()
colnames(y_found) = c("beta", "pi", "cosine")
y_found %>% filter(beta==1e-3) %>% ggplot(aes(x=as.factor(pi),y=cosine)) + geom_boxplot() + stat_compare_means()
```

```{r test real difference}
cosineOnly = function(Test, Ttrue){
  bestMatch = which(abs(cor(Test, Ttrue)) == max(abs(cor(Test,Ttrue))))
  Test = Test[,bestMatch]
  similarity = abs(sum(Test * Ttrue)) / (norm(Test, "2") * norm(Ttrue, "2"))
  return(similarity)
}

global1_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,1])}))
global2_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,2])}))
local1_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,3])}))
local2_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,4])}))
distinct1_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,5])}))
distinct2_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,6])}))
distinct3_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){cosineOnly(x$Fac[[1]], inputLoadings[[1]][,7])}))
y_found = unlist(lapply(ACMTFR_CV_models, FUN=function(x){abs(sum(x$Yhat * Yreal) / (norm(x$Yhat, "2") * norm(Yreal, "2")))}))

df = cbind(ACMTFR_FMS, global1_found, global2_found, local1_found, local2_found, distinct1_found, distinct2_found, distinct3_found, y_found) %>% as_tibble()
df %>% select(-FMS,-index) %>% pivot_longer(-c(beta,pi)) %>% ggplot(aes(x=as.factor(beta),y=value)) + facet_grid(vars(name),vars(pi)) + geom_boxplot()
```

```{r coeffs acmtfr}
coeffs = do.call(rbind, lapply(ACMTFR_CV_models, FUN=function(x){(t(x$rho))})) %>% as_tibble()
colnames(coeffs) = paste0("rho", 1:7)

cbind(ACMTFR_varExps, coeffs) %>% as_tibble() %>% filter(correct == TRUE,beta==1e-3) %>% select(-X1,-X2,-X3,-Y,-beta,-correct) %>% pivot_longer(-pi) %>% ggplot(aes(x=as.factor(pi),y=abs(value))) + facet_wrap(~name) + geom_boxplot(outliers=FALSE) + geom_point(position=position_jitter(width=0.05,height=0.0)) + ggtitle("Correct models")

cbind(ACMTFR_varExps, coeffs) %>% as_tibble() %>% filter(correct == FALSE,beta==1e-3) %>% select(-X1,-X2,-X3,-Y,-beta,-correct) %>% pivot_longer(-pi) %>% filter(abs(value)<=1) %>% ggplot(aes(x=as.factor(pi),y=abs(value))) + facet_wrap(~name) + geom_boxplot(outliers=FALSE) + geom_point(position=position_jitter(width=0.05,height=0.0)) + ggtitle("Incorrect models")
```
```{r inspect loss per iteration - beta}
# Use the same initialization across beta settings
model = ACMTF_CV_models[[201]]
init = fac_to_vect(model$init)
alpha = 1
# beta = rep(1e-3, 3) # Changes per model
epsilon = 1e-8
datasets = list(X1_final, X2_final, X3_final)
modes = list(c(1,2,3),c(1,4,5),c(1,6,7))
Z = setupCMTFdata(datasets, modes, normalize=FALSE)
abs_tol=1e-10
rel_tol=1e-10

# High beta
beta = rep(0.1, 3)
fg = list("fn"=function(x){return(CMTFtoolbox::acmtf_fun(x,Z,alpha,beta,epsilon))}, "gr"=function(x){return(CMTFtoolbox::acmtf_gradient(x,Z,alpha,beta,epsilon))})
# ACMTF_high_beta = CMTFtoolbox::mize_runner(init, fg, abs_tol=abs_tol, rel_tol=rel_tol)
ACMTF_high_beta = readRDS("./ACMTF_high_beta.RDS")

# Normal beta
beta = rep(1e-3, 3)
fg = list("fn"=function(x){return(CMTFtoolbox::acmtf_fun(x,Z,alpha,beta,epsilon))}, "gr"=function(x){return(CMTFtoolbox::acmtf_gradient(x,Z,alpha,beta,epsilon))})
# ACMTF_normal_beta = CMTFtoolbox::mize_runner(init, fg, abs_tol=abs_tol, rel_tol=rel_tol)
ACMTF_normal_beta = readRDS("./ACMTF_normal_beta.RDS")

# Low beta
beta = rep(1e-10, 3)
fg = list("fn"=function(x){return(CMTFtoolbox::acmtf_fun(x,Z,alpha,beta,epsilon))}, "gr"=function(x){return(CMTFtoolbox::acmtf_gradient(x,Z,alpha,beta,epsilon))})
# ACMTF_low_beta = CMTFtoolbox::mize_runner(init, fg, abs_tol=abs_tol, rel_tol=rel_tol)
ACMTF_low_beta = readRDS("./ACMTF_low_beta.RDS")

# Process result

## High
beta=rep(0.1,3)
f_per_block = apply(ACMTF_high_beta$all_iterations, 2, FUN=function(x){acmtf_fun(x,Z,alpha,beta,epsilon,manual=TRUE)[[1]]})
f_per_block = t(f_per_block) %>% as_tibble()

f_norm = apply(ACMTF_high_beta$all_iterations, 2, FUN=function(x){acmtf_fun(x,Z,alpha,beta,epsilon,manual=TRUE)[[2]]})
f_norm = colSums(f_norm)

f_lambda = apply(ACMTF_high_beta$all_iterations, 2, FUN=function(x){acmtf_fun(x,Z,alpha,beta,epsilon,manual=TRUE)[[3]]})
f_lambda = colSums(f_lambda)

df = cbind(f_per_block, f_norm, f_lambda)
colnames(df) = c("X1", "X2", "X3", "norm1", "lambda")
df = df %>% mutate(beta=0.1, f = sum(X1, X2, X3, norm1, lambda)) %>% mutate(iteration = 1:nrow(.))

df_high = df

## Medium
beta=rep(1e-3,3)
f_per_block = apply(ACMTF_normal_beta$all_iterations, 2, FUN=function(x){acmtf_fun(x,Z,alpha,beta,epsilon,manual=TRUE)[[1]]})
f_per_block = t(f_per_block) %>% as_tibble()

f_norm = apply(ACMTF_normal_beta$all_iterations, 2, FUN=function(x){acmtf_fun(x,Z,alpha,beta,epsilon,manual=TRUE)[[2]]})
f_norm = colSums(f_norm)

f_lambda = apply(ACMTF_normal_beta$all_iterations, 2, FUN=function(x){acmtf_fun(x,Z,alpha,beta,epsilon,manual=TRUE)[[3]]})
f_lambda = colSums(f_lambda)

df = cbind(f_per_block, f_norm, f_lambda)
colnames(df) = c("X1", "X2", "X3", "norm1", "lambda")
df = df %>% mutate(beta=1e-3, f = sum(X1, X2, X3, norm1, lambda)) %>% mutate(iteration = 1:nrow(.))

df_normal = df

## Low
beta=rep(1e-10,3)
f_per_block = apply(ACMTF_low_beta$all_iterations, 2, FUN=function(x){acmtf_fun(x,Z,alpha,beta,epsilon,manual=TRUE)[[1]]})
f_per_block = t(f_per_block) %>% as_tibble()

f_norm = apply(ACMTF_low_beta$all_iterations, 2, FUN=function(x){acmtf_fun(x,Z,alpha,beta,epsilon,manual=TRUE)[[2]]})
f_norm = colSums(f_norm)

f_lambda = apply(ACMTF_low_beta$all_iterations, 2, FUN=function(x){acmtf_fun(x,Z,alpha,beta,epsilon,manual=TRUE)[[3]]})
f_lambda = colSums(f_lambda)

df = cbind(f_per_block, f_norm, f_lambda)
colnames(df) = c("X1", "X2", "X3", "norm1", "lambda")
df = df %>% mutate(beta=1e-10, f = sum(X1, X2, X3, norm1, lambda)) %>% mutate(iteration = 1:nrow(.))

df_low = df

# Plot
df = rbind(df_high, df_normal, df_low) %>% as_tibble()
a=df %>% select(-f) %>% pivot_longer(-c(iteration,beta)) %>% ggplot(aes(x=iteration,y=value,col=as.factor(name))) + facet_wrap(~beta, scales="free_x") + geom_line() + scale_y_log10()

# check lambdas
b=matrix(ACMTF_low_beta$par[1821:1841], nrow=3, ncol=7) %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Low beta") + theme(legend.position = "none")

c=matrix(ACMTF_normal_beta$par[1821:1841], nrow=3, ncol=7) %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Normal beta") + theme(legend.position = "none")

d=matrix(ACMTF_high_beta$par[1821:1841], nrow=3, ncol=7) %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("High beta") + theme(legend.position = "none")

a
ggarrange(b,c,d, nrow=1)

df %>% select(lambda, beta, iteration) %>% ggplot(aes(x=iteration,y=lambda)) + facet_wrap(~beta, scales="free_x") + geom_line()
df %>% select(-f) %>% pivot_longer(-c(iteration,beta)) %>% ggplot(aes(x=iteration,y=value)) + facet_grid(vars(name),vars(beta), scales="free") + geom_line() + scale_y_log10()
```

```{r inspect loss per iteration - pi}
# Use the same initialization across pi settings
model = ACMTFR_CV_models[[18]]
init = fac_to_vect(model$init)
alpha = 1
beta = rep(1e-3, 3)
epsilon = 1e-8
# pi is set per model
datasets = list(X1_final, X2_final, X3_final)
Y = as.matrix(Y_final@data)
modes = list(c(1,2,3),c(1,4,5),c(1,6,7))
Z = setupCMTFdata(datasets, modes, normalize=FALSE)

abs_tol=1e-10
rel_tol=1e-10

# High pi
pi = 0.9
fg = list("fn"=function(x){return(CMTFtoolbox::acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi))}, "gr"=function(x){return(CMTFtoolbox::acmtfr_gradient(x,Z,Y,alpha,beta,epsilon,pi))})
# ACMTF_high_pi = CMTFtoolbox::mize_runner(init, fg, abs_tol=abs_tol, rel_tol=rel_tol)
ACMTF_high_pi = readRDS("./ACMTF_high_pi.RDS")

# Normal pi
pi = 0.5
fg = list("fn"=function(x){return(CMTFtoolbox::acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi))}, "gr"=function(x){return(CMTFtoolbox::acmtfr_gradient(x,Z,Y,alpha,beta,epsilon,pi))})
# ACMTF_normal_pi = CMTFtoolbox::mize_runner(init, fg, abs_tol=abs_tol, rel_tol=rel_tol)
ACMTF_normal_pi = readRDS("./ACMTF_normal_beta.RDS")

# Low beta
pi = 0.1
fg = list("fn"=function(x){return(CMTFtoolbox::acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi))}, "gr"=function(x){return(CMTFtoolbox::acmtfr_gradient(x,Z,Y,alpha,beta,epsilon,pi))})
# ACMTF_low_pi = CMTFtoolbox::mize_runner(init, fg, abs_tol=abs_tol, rel_tol=rel_tol)
# ACMTF_low_pi = readRDS("./ACMTF_low_pi.RDS")

# Pi = 1
pi = 1
fg = list("fn"=function(x){return(CMTFtoolbox::acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi))}, "gr"=function(x){return(CMTFtoolbox::acmtfr_gradient(x,Z,Y,alpha,beta,epsilon,pi))})
# ACMTF_no_pi = CMTFtoolbox::mize_runner(init, fg, abs_tol=abs_tol, rel_tol=rel_tol)
ACMTF_no_pi = readRDS("./ACMTF_no_pi.RDS")

# Process result

## High pi
pi = 0.9
f_per_block = apply(ACMTF_high_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[1]]})
f_per_block = t(f_per_block) %>% as_tibble()

f_y = apply(ACMTF_high_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[2]]})
f_y = f_y %>% as_tibble()

f_norm = apply(ACMTF_high_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[3]]})
f_norm = colSums(f_norm)

f_lambda = apply(ACMTF_high_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[4]]})
f_lambda = colSums(f_lambda)

df = cbind(f_per_block, f_y, f_norm, f_lambda)
colnames(df) = c("X1", "X2", "X3", "Y", "norm1", "lambda")
df = df %>% mutate(pi=pi, f = sum(X1, X2, X3, Y, norm1, lambda))

df_high = df

## Medium
pi=0.5
f_per_block = apply(ACMTF_normal_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[1]]})
f_per_block = t(f_per_block) %>% as_tibble()

f_y = apply(ACMTF_normal_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[2]]})
f_y = f_y %>% as_tibble()

f_norm = apply(ACMTF_normal_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[3]]})
f_norm = colSums(f_norm)

f_lambda = apply(ACMTF_normal_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[4]]})
f_lambda = colSums(f_lambda)

df = cbind(f_per_block, f_y, f_norm, f_lambda)
colnames(df) = c("X1", "X2", "X3", "Y", "norm1", "lambda")
df = df %>% mutate(pi=pi, f = sum(X1, X2, X3, Y, norm1, lambda))

df_normal = df

## Low
pi=0.1
f_per_block = apply(ACMTF_low_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[1]]})
f_per_block = t(f_per_block) %>% as_tibble()

f_y = apply(ACMTF_low_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[2]]})
f_y = f_y %>% as_tibble()

f_norm = apply(ACMTF_low_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[3]]})
f_norm = colSums(f_norm)

f_lambda = apply(ACMTF_low_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[4]]})
f_lambda = colSums(f_lambda)

df = cbind(f_per_block, f_y, f_norm, f_lambda)
colnames(df) = c("X1", "X2", "X3", "Y", "norm1", "lambda")
df = df %>% mutate(pi=pi, f = sum(X1, X2, X3, Y, norm1, lambda))

df_low = df

# No pi
pi=1
f_per_block = apply(ACMTF_no_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[1]]})
f_per_block = t(f_per_block) %>% as_tibble()

f_y = apply(ACMTF_no_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[2]]})
f_y = f_y %>% as_tibble()

f_norm = apply(ACMTF_no_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[3]]})
f_norm = colSums(f_norm)

f_lambda = apply(ACMTF_no_pi$all_iterations, 2, FUN=function(x){acmtfr_fun(x,Z,Y,alpha,beta,epsilon,pi,manual=TRUE)[[4]]})
f_lambda = colSums(f_lambda)

df = cbind(f_per_block, f_y, f_norm, f_lambda)
colnames(df) = c("X1", "X2", "X3", "Y", "norm1", "lambda")
df = df %>% mutate(pi=pi, f = sum(X1, X2, X3, Y, norm1, lambda))

df_no = df

# Plot
df_high = df_high %>% mutate(iteration = 1:nrow(.))
df_normal = df_normal %>% mutate(iteration = 1:nrow(.))
df_low = df_low %>% mutate(iteration = 1:nrow(.))
df_no = df_no %>% mutate(iteration = 1:nrow(.), Y = Y + 1e-10)

df = rbind(df_high, df_normal, df_low, df_no) %>% as_tibble()
a=df %>% select(-f) %>% pivot_longer(-c(iteration,pi)) %>% ggplot(aes(x=iteration,y=value,col=as.factor(name))) + facet_wrap(~pi, scales="free_x", nrow=1) + geom_line() + scale_y_log10()

# check lambdas
c=matrix(ACMTF_low_pi$par[1821:1841], nrow=3, ncol=7) %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Low pi") + theme(legend.position = "none")

d=matrix(ACMTF_normal_pi$par[1821:1841], nrow=3, ncol=7) %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Normal pi") + theme(legend.position = "none")

e=matrix(ACMTF_high_pi$par[1821:1841], nrow=3, ncol=7) %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("High pi") + theme(legend.position = "none")

f=matrix(ACMTF_no_pi$par[1821:1841], nrow=3, ncol=7) %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% pivot_longer(-index) %>% mutate(index = factor(index, levels=c(3,2,1))) %>% ggplot(aes(y=index,x=as.factor(name),fill=value)) + geom_tile(col="black") + ylab("X block") + scale_x_discrete(name="Component number", labels=1:7) + scale_fill_gradient2(low="red",high="green",mid="grey",midpoint=0) + geom_text(aes(label=round(value,2))) + scale_y_discrete(name="X block", labels=c("X3", "X2", "X1")) + ggtitle("Pi=1") + theme(legend.position = "none")

a
ggarrange(c,d,e,f, nrow=1)

df %>% select(lambda, beta, iteration) %>% ggplot(aes(x=iteration,y=lambda)) + facet_wrap(~beta, scales="free_x") + geom_line()
df %>% select(-f) %>% pivot_longer(-c(iteration,pi)) %>% ggplot(aes(x=iteration,y=value)) + facet_grid(vars(name),vars(pi), scales="free") + geom_line() + scale_y_log10()
```
